//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CMMotionManager;

@interface ACParallaxView : UIView
{
    BOOL _parallax;
    BOOL _refocusParallax;
    id <ACParallaxViewDelegate> _parallaxDelegate;
    CMMotionManager *_sharedMotionManager;
    struct ACAttitude _referenceAttitude;
    struct ACAttitude _relativeAttitude;
}

+ (void)setSharedMotionManager:(id)arg1;
+ (id)sharedMotionManager;
@property(nonatomic) struct ACAttitude relativeAttitude; // @synthesize relativeAttitude=_relativeAttitude;
@property(nonatomic) struct ACAttitude referenceAttitude; // @synthesize referenceAttitude=_referenceAttitude;
@property(readonly, nonatomic) CMMotionManager *sharedMotionManager; // @synthesize sharedMotionManager=_sharedMotionManager;
@property(nonatomic) BOOL refocusParallax; // @synthesize refocusParallax=_refocusParallax;
@property(nonatomic, getter=isParallax) BOOL parallax; // @synthesize parallax=_parallax;
@property(nonatomic) __weak id <ACParallaxViewDelegate> parallaxDelegate; // @synthesize parallaxDelegate=_parallaxDelegate;
- (void).cxx_destruct;
- (void)endParallaxUpdates;
- (void)beginParallaxUpdates;

@end

