//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFAdjustButton, AFAdjustToolLabel, NSString;

@interface AFAdjustToolWrapper : NSObject
{
    float _value;
    NSString *_processorKey;
    AFAdjustButton *_button;
    AFAdjustToolLabel *_label;
}

@property(retain, nonatomic) AFAdjustToolLabel *label; // @synthesize label=_label;
@property(retain, nonatomic) AFAdjustButton *button; // @synthesize button=_button;
@property(retain, nonatomic) NSString *processorKey; // @synthesize processorKey=_processorKey;
@property(nonatomic) float value; // @synthesize value=_value;
- (void).cxx_destruct;
- (void)setSelected:(BOOL)arg1;

@end

