//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFView.h"

@class NSString, UIColor, UILabel;

@interface AFAdjustTitleView : AFView
{
    BOOL _changedTitle;
    UILabel *_titleLabel;
    UILabel *_offscreenTitleLabel;
}

@property(retain, nonatomic) UILabel *offscreenTitleLabel; // @synthesize offscreenTitleLabel=_offscreenTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic, getter=hasChangedTitle) BOOL changedTitle; // @synthesize changedTitle=_changedTitle;
- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *textShadowColor; // @dynamic textShadowColor;
@property(retain, nonatomic) UIColor *textColor; // @dynamic textColor;
@property(retain, nonatomic) NSString *title; // @dynamic title;
- (void)setTitle:(id)arg1 withAnimation:(unsigned int)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)prepareView;

@end

