//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSOperationQueue;

@interface AFAssetManager : NSObject
{
    NSOperationQueue *_downloadQueue;
    NSOperationQueue *_callbackQueue;
    NSMutableDictionary *_resourceProviders;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableDictionary *resourceProviders; // @synthesize resourceProviders=_resourceProviders;
@property(retain, nonatomic) NSOperationQueue *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
@property(retain, nonatomic) NSOperationQueue *downloadQueue; // @synthesize downloadQueue=_downloadQueue;
- (void).cxx_destruct;
- (void)resourceProvider:(id)arg1 didUpdateKeyPath:(id)arg2;
- (void)startDownload:(id)arg1;
- (void)uncacheResourceProvider:(id)arg1;
- (id)resourceProviderForContentPack:(id)arg1 withType:(int)arg2;
- (void)downloadThumbnailAssets;
- (id)init;

@end

