//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class AFOpenGLView, UIImageView;

@interface AFAviaryGLImageView : UIScrollView <UIScrollViewDelegate>
{
    BOOL _positionLocked;
    BOOL _useImageViewSizeForScaling;
    UIImageView *_imageView;
    AFOpenGLView *_openGLView;
    float _calculatedMinimumZoomScale;
    float _calculatedMaximumZoomScale;
    float _calculatedRelativeZoomScale;
    struct CGRect _minimumImageRect;
}

+ (void)forceLinkerLoad_;
@property(nonatomic) BOOL useImageViewSizeForScaling; // @synthesize useImageViewSizeForScaling=_useImageViewSizeForScaling;
@property(nonatomic, getter=isPositionLocked) BOOL positionLocked; // @synthesize positionLocked=_positionLocked;
@property(nonatomic) struct CGRect minimumImageRect; // @synthesize minimumImageRect=_minimumImageRect;
@property(nonatomic) float calculatedRelativeZoomScale; // @synthesize calculatedRelativeZoomScale=_calculatedRelativeZoomScale;
@property(nonatomic) float calculatedMaximumZoomScale; // @synthesize calculatedMaximumZoomScale=_calculatedMaximumZoomScale;
@property(nonatomic) float calculatedMinimumZoomScale; // @synthesize calculatedMinimumZoomScale=_calculatedMinimumZoomScale;
@property(retain, nonatomic) AFOpenGLView *openGLView; // @synthesize openGLView=_openGLView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)dealloc;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)showOpenGLViewInternal:(BOOL)arg1;
- (void)showOpenGLView:(BOOL)arg1;
- (id)image;
- (void)setImage:(id)arg1;
- (void)setImage:(id)arg1 animated:(BOOL)arg2;
- (void)setImage:(id)arg1 needsLayout:(BOOL)arg2 animated:(BOOL)arg3;
- (void)setImage:(id)arg1 needsLayout:(BOOL)arg2;
- (void)zoomOutAnimated:(BOOL)arg1;
- (void)recalculateAndSetZoomBoundaries;
- (void)calculateZoomBoundariesForImageSize:(struct CGSize)arg1 returnedMin:(float *)arg2 returnedMax:(float *)arg3;
- (void)centerImageView;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setup;

@end

