//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFImageServer.h"

@interface AFBitmapImageServer : AFImageServer
{
    BOOL _stopped;
    struct __CFData *_data;
    unsigned int _lastOperationHash;
    int _queueID;
}

@property int queueID; // @synthesize queueID=_queueID;
@property unsigned int lastOperationHash; // @synthesize lastOperationHash=_lastOperationHash;
@property(getter=isStopped) BOOL stopped; // @synthesize stopped=_stopped;
- (void)releaseInputImage;
- (void)cleanup;
- (void)cancelProcessing;
- (void)runBlock:(CDUnknownBlockType)arg1;
- (void)getProcessedImageSizeAndDataOnCurrentThread:(CDUnknownBlockType)arg1;
- (void)getProcessedImageSizeAndData:(CDUnknownBlockType)arg1;
- (void)getProcessedImageAndDataOnCurrentThread:(CDUnknownBlockType)arg1;
- (void)getProcessedImageAndData:(CDUnknownBlockType)arg1;
- (void)getProcessedImage:(CDUnknownBlockType)arg1;
- (void)runProcessor:(id)arg1;
- (void)runModuleFromImageServerThread:(id)arg1;
- (void)resetOrientation;
- (void)setPixelsWithSnapshot:(id)arg1;
- (void)takeSnapshot:(CDUnknownBlockType)arg1;
- (void)commit;
- (void)cropImageToRect:(struct CGRect)arg1;
- (void)drawImageOnCurrentThread;
- (void)drawImage;
- (void)drawImageWithOrientation:(int)arg1;
- (void)configureForOrientation:(int)arg1;
- (void)doConfigureForOrientation:(int)arg1;
- (void)drawTransformedImageWithOrientation:(int)arg1;
- (void)drawStraightenedwithRotation:(float)arg1 scale:(float)arg2 orientation:(int)arg3;
- (void)enqueueMoaBlock:(CDUnknownBlockType)arg1;
- (void)enqueueBlock:(CDUnknownBlockType)arg1;
- (void)doWithMoaBitmap:(CDUnknownBlockType)arg1;
- (void)doWithContext:(CDUnknownBlockType)arg1;
@property(readonly) struct __CFData *data; // @synthesize data=_data;
- (id)initWithCGImage:(struct CGImage *)arg1 scale:(float)arg2 orientation:(int)arg3 glInstance:(id)arg4 fromGLQueue:(BOOL)arg5;
- (id)initWithCGImage:(struct CGImage *)arg1 scale:(float)arg2 orientation:(int)arg3 glInstance:(id)arg4;
- (id)initWithCGImage:(struct CGImage *)arg1 scale:(float)arg2 orientation:(int)arg3 glData:(id)arg4;
- (id)initHeadlessWithCGImage:(struct CGImage *)arg1 scale:(float)arg2 orientation:(int)arg3;
- (id)initWithCGImage:(struct CGImage *)arg1 scale:(float)arg2 orientation:(int)arg3;
- (id)initWithGLInstance:(id)arg1;
- (void)dealloc;

@end

