//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFModule.h"

@interface AFBlockModule : AFModule
{
    BOOL _shouldCallSuperPreprocess;
    CDUnknownBlockType _createProcessors;
    CDUnknownBlockType _preprocess;
}

+ (id)moduleWithBlock:(CDUnknownBlockType)arg1 andPreprocessBlock:(CDUnknownBlockType)arg2 callSuperPreprocess:(BOOL)arg3;
+ (id)moduleWithBlock:(CDUnknownBlockType)arg1;
@property(nonatomic) BOOL shouldCallSuperPreprocess; // @synthesize shouldCallSuperPreprocess=_shouldCallSuperPreprocess;
@property(copy, nonatomic) CDUnknownBlockType preprocess; // @synthesize preprocess=_preprocess;
@property(copy, nonatomic) CDUnknownBlockType createProcessors; // @synthesize createProcessors=_createProcessors;
- (void).cxx_destruct;
- (void)createProcessors:(id)arg1;
- (void)preprocess:(id)arg1;

@end

