//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFProcessor.h"

@class NSArray;

@interface AFBrushStrokesProcessor : AFProcessor
{
    NSArray *_strokes;
}

@property(retain, nonatomic) NSArray *strokes; // @synthesize strokes=_strokes;
- (void).cxx_destruct;
- (void)setScaleFactor:(float)arg1;

@end

