//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFContentPack, AFContentPackShelfView;

@protocol AFContentPackShelfViewDelegate <NSObject>
- (void)contentPackShelfDidUpdateContentPacks:(AFContentPackShelfView *)arg1;
- (void)contentPackShelfDidCancelSelection:(AFContentPackShelfView *)arg1;
- (void)contentPackShelf:(AFContentPackShelfView *)arg1 didSelectContentPack:(AFContentPack *)arg2;
- (void)contentPackShelfDidSelectGetMore:(AFContentPackShelfView *)arg1;
@end

