//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFContentPack, AFContentPackListIAPViewController;

@protocol AFContentPackListIAPViewControllerDelegate <NSObject>
- (void)listIAPViewController:(AFContentPackListIAPViewController *)arg1 beganPurchasingPack:(AFContentPack *)arg2;
- (void)listIAPViewControllerFinished:(AFContentPackListIAPViewController *)arg1;
@end

