//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class AFContentPack, UIButton, UILabel, UIProgressView;

@interface AFContentPackListIAPViewProductCell : UITableViewCell
{
    BOOL _purchasing;
    int _cellColor;
    AFContentPack *_contentPack;
    id <AFContentPackListIAPViewProductCellDelegate> _delegate;
    UIButton *_purchaseButton;
    UIProgressView *_downloadProgressView;
    UILabel *_countLabel;
    UILabel *_installedLabel;
}

@property(retain, nonatomic) UILabel *installedLabel; // @synthesize installedLabel=_installedLabel;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UIProgressView *downloadProgressView; // @synthesize downloadProgressView=_downloadProgressView;
@property(retain, nonatomic) UIButton *purchaseButton; // @synthesize purchaseButton=_purchaseButton;
@property(nonatomic) __weak id <AFContentPackListIAPViewProductCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isPurchasing) BOOL purchasing; // @synthesize purchasing=_purchasing;
@property(retain, nonatomic) AFContentPack *contentPack; // @synthesize contentPack=_contentPack;
@property(nonatomic) int cellColor; // @synthesize cellColor=_cellColor;
- (void).cxx_destruct;
- (void)purchasePack;
- (void)refresh;
- (void)updateProgessViewAnimated:(BOOL)arg1;
- (void)configureForPackState;
- (void)configureCellForContentPack;
- (void)configureCellForContentPack_iPhone;
- (void)configureCellForContentPack_iPad;
- (void)setCellColorForHighlightedState:(BOOL)arg1;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (void)layoutSubviews_iPad;
- (void)layoutSubviews_iPhone;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

