//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackUnifiedSelectionViewCell.h"

@class UIProgressView;

@interface AFContentPackDownloadSelectionViewCell : AFContentPackUnifiedSelectionViewCell
{
    UIProgressView *_downloadProgressView;
}

@property(retain, nonatomic) UIProgressView *downloadProgressView; // @synthesize downloadProgressView=_downloadProgressView;
- (void).cxx_destruct;
- (void)updateProgressViewAnimated:(BOOL)arg1;
- (void)update;
- (void)setContentPackItem:(id)arg1;
- (void)setContentPack:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

