//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackSelectionViewController.h"

@class AFContentPack, AFContentPackListSelectionViewController, NSString;

@interface AFContentPackDetailSelectionViewController : AFContentPackSelectionViewController
{
    AFContentPackListSelectionViewController *_listViewController;
    AFContentPack *_contentPack;
    NSString *_contentPackKey;
}

@property(copy, nonatomic) NSString *contentPackKey; // @synthesize contentPackKey=_contentPackKey;
@property(retain, nonatomic) AFContentPack *contentPack; // @synthesize contentPack=_contentPack;
@property(nonatomic) __weak AFContentPackListSelectionViewController *listViewController; // @synthesize listViewController=_listViewController;
- (void).cxx_destruct;
- (void)reportCanceled;
- (void)reportOpened;
- (void)setRenderEndDate;
- (void)setRenderStartDate;
- (void)selectionViewDidSelectContentPackItem:(id)arg1;
- (id)selectionViewCellForContentPackItem:(id)arg1;
- (void)selectionView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)selectionView:(id)arg1 selectionViewCellForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInSelectionView:(id)arg1;
- (int)selectionView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (BOOL)inAppPurchaseEnabled;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)applyButtonPressed:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)scrollableImageView;
- (id)scrollableOverlayView;
- (id)staticOverlayView;
- (void)loadView;
- (id)initWithGLInstance:(id)arg1 contentPack:(id)arg2 selectionView:(BOOL)arg3;

@end

