//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFViewController.h"

#import "AFContentPackDetailIAPViewControllerDelegate.h"
#import "AFContentPackListIAPViewProductCellDelegate.h"
#import "AFContentPackListIAPViewRestoreCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AFContentPack, AFContentPackDetailIAPViewController, AFProgressHUDView, NSArray, UIBarButtonItem, UITableView;

@interface AFContentPackListIAPViewController : AFViewController <AFContentPackListIAPViewProductCellDelegate, AFContentPackDetailIAPViewControllerDelegate, AFContentPackListIAPViewRestoreCellDelegate, UITableViewDataSource, UITableViewDelegate>
{
    BOOL _purchasing;
    BOOL _displayingFetchingMessage;
    id <AFContentPackListIAPViewControllerDelegate> _delegate;
    NSArray *_packs;
    AFProgressHUDView *_hudView;
    AFContentPack *_purchasingContentPack;
    UITableView *_tableView;
    AFContentPackDetailIAPViewController *_detailViewController;
    UIBarButtonItem *_closeButton;
    UIBarButtonItem *_restoreButton;
}

+ (BOOL)isStoreManagerFetching;
+ (id)typeDescriptor;
@property(retain, nonatomic) UIBarButtonItem *restoreButton; // @synthesize restoreButton=_restoreButton;
@property(retain, nonatomic) UIBarButtonItem *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) AFContentPackDetailIAPViewController *detailViewController; // @synthesize detailViewController=_detailViewController;
@property(nonatomic, getter=isDisplayingFetchingMessage) BOOL displayingFetchingMessage; // @synthesize displayingFetchingMessage=_displayingFetchingMessage;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) AFContentPack *purchasingContentPack; // @synthesize purchasingContentPack=_purchasingContentPack;
@property(retain, nonatomic) AFProgressHUDView *hudView; // @synthesize hudView=_hudView;
@property(nonatomic, getter=isPurchasing) BOOL purchasing; // @synthesize purchasing=_purchasing;
@property(retain, nonatomic) NSArray *packs; // @synthesize packs=_packs;
@property(nonatomic) __weak id <AFContentPackListIAPViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)finishedDownloadingContentPack:(id)arg1;
- (void)updatedDownloadProgressForContentPack:(id)arg1;
- (void)beganDownloadingPack:(id)arg1;
- (void)updateCellsForRestore;
- (void)reloadPurchasedCell;
- (void)didFail;
- (void)didRestore;
- (void)didPurchase;
- (void)willPurchase;
- (void)detailIAPViewController:(id)arg1 beganPurchasing:(id)arg2;
- (void)restore;
- (void)contentPackListViewRestoreCellDidPressRestore:(id)arg1;
- (void)listIAPCell:(id)arg1 beganPurchasing:(id)arg2;
- (void)doneButtonPressed:(id)arg1;
- (void)restoreButtonPressed:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)productCellForContentPack:(id)arg1;
- (id)loadDetailViewControllerWithContentPack:(id)arg1;
- (void)updatePacks:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithPacks:(id)arg1;

@end

