//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFColorConveyorController, UIColor;

@protocol AFColorConveyorControllerDelegate <NSObject>
- (void)colorController:(AFColorConveyorController *)arg1 didScrollToEraser:(BOOL)arg2;
- (void)colorController:(AFColorConveyorController *)arg1 didSelectEraser:(BOOL)arg2;
- (void)colorController:(AFColorConveyorController *)arg1 didScrollToColor:(UIColor *)arg2 atIndex:(int)arg3;
- (void)colorController:(AFColorConveyorController *)arg1 didSelectColor:(UIColor *)arg2 atIndex:(int)arg3;
@end

