//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackIAPSelectionViewController.h"

#import "NSFetchedResultsControllerDelegate.h"

@class AFContentPackItem;

@interface AFContentPackUnifiedSelectionViewController : AFContentPackIAPSelectionViewController <NSFetchedResultsControllerDelegate>
{
    BOOL _hasSectionForOriginalItem;
    AFContentPackItem *_selectedItem;
    AFContentPackItem *_originalContentPackItem;
    int _shouldAnimateSection;
}

+ (Class)contentPackItemType;
@property(nonatomic) int shouldAnimateSection; // @synthesize shouldAnimateSection=_shouldAnimateSection;
@property(nonatomic) BOOL hasSectionForOriginalItem; // @synthesize hasSectionForOriginalItem=_hasSectionForOriginalItem;
@property(retain, nonatomic) AFContentPackItem *originalContentPackItem; // @synthesize originalContentPackItem=_originalContentPackItem;
@property(retain, nonatomic) AFContentPackItem *selectedItem; // @synthesize selectedItem=_selectedItem;
- (void).cxx_destruct;
- (void)reportApplied;
- (void)selectRowAtIndexPath:(id)arg1;
- (id)selectionView:(id)arg1 headerTitleForSection:(int)arg2;
- (BOOL)selectionView:(id)arg1 hasHeaderInSection:(int)arg2;
- (void)displayPreviewForContentPackItem:(id)arg1;
- (void)didSelectContentPackItem:(id)arg1;
- (void)selectionView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)cellForContentPackItem:(id)arg1;
- (id)selectionView:(id)arg1 selectionViewCellForRowAtIndexPath:(id)arg2;
- (int)selectionView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInSelectionView:(id)arg1;
- (id)contentPackItemForIndexPath:(id)arg1;
- (id)indexPathForContentPackItem:(id)arg1;
- (BOOL)hasLockedContent;
- (BOOL)requiresSectionForOriginalItem;
- (void)selectionViewDidEndScrollingAnimation:(id)arg1;
- (void)updateContentPackSelectionViewAnimated:(BOOL)arg1;
- (void)applyButtonPressed:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;

@end

