//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFViewController.h"

#import "AFScrollBarViewDelegate.h"

@class AFContentPack, AFPageControl, AFProgressHUDView, AFScrollBarView, UIBarButtonItem, UIButton, UIImageView, UILabel, UIProgressView;

@interface AFContentPackDetailIAPViewController : AFViewController <AFScrollBarViewDelegate>
{
    BOOL _purchasing;
    AFContentPack *_contentPack;
    id <AFContentPackDetailIAPViewControllerDelegate> _delegate;
    UIImageView *_packPreviewImageView;
    UILabel *_packNameLabel;
    UILabel *_countLabel;
    UILabel *_descriptionLabel;
    UIButton *_purchaseButton;
    AFPageControl *_pageControl;
    AFScrollBarView *_scrollBarView;
    int _type;
    AFProgressHUDView *_hudView;
    UIProgressView *_downloadProgressView;
    UIBarButtonItem *_dismissButton;
    UILabel *_installLabel;
}

+ (Class)pageItemClass;
+ (id)countDescriptor;
+ (id)titleDescriptor;
@property(retain, nonatomic) UILabel *installLabel; // @synthesize installLabel=_installLabel;
@property(retain, nonatomic) UIBarButtonItem *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(retain, nonatomic) UIProgressView *downloadProgressView; // @synthesize downloadProgressView=_downloadProgressView;
@property(retain, nonatomic) AFProgressHUDView *hudView; // @synthesize hudView=_hudView;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic, getter=isPurchasing) BOOL purchasing; // @synthesize purchasing=_purchasing;
@property(retain, nonatomic) AFScrollBarView *scrollBarView; // @synthesize scrollBarView=_scrollBarView;
@property(retain, nonatomic) AFPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIButton *purchaseButton; // @synthesize purchaseButton=_purchaseButton;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UILabel *packNameLabel; // @synthesize packNameLabel=_packNameLabel;
@property(retain, nonatomic) UIImageView *packPreviewImageView; // @synthesize packPreviewImageView=_packPreviewImageView;
@property(nonatomic) __weak id <AFContentPackDetailIAPViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AFContentPack *contentPack; // @synthesize contentPack=_contentPack;
- (void).cxx_destruct;
- (id)scrollBar:(id)arg1 itemViewForContentPackItems:(id)arg2;
- (void)purchaseButtonPress:(id)arg1;
- (id)scrollBar:(id)arg1 itemViewForColumnAtIndex:(unsigned int)arg2;
- (unsigned int)numberOfItemsInScrollBar:(id)arg1;
- (void)finishedDownloading;
- (void)updateDownloadProgress;
- (void)beganDownloading;
- (void)didRestore;
- (void)didPurchase;
- (void)didFail;
- (void)willPurchase;
- (void)backButtonPressed:(id)arg1;
- (void)purchaseButtonPressed:(id)arg1;
- (void)updateProgessViewAnimated:(BOOL)arg1;
- (void)configureForPackState;
- (void)reloadData;
- (void)configurePurchaseButtonForPrice;
- (id)packPreviewImage;
- (int)numberOfItems;
- (int)numberOfColumnsPerPage;
- (int)numberOfRows;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)updateViewForContentPack;
- (void)layoutContentPackInformation;
- (void)layoutScrollBarViews;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithType:(int)arg1 contentPack:(id)arg2;

@end

