//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFView.h"

@class UIImageView;

@interface AFContentPackSelectionViewSectionFooterView : AFView
{
    UIImageView *_footerImageView;
}

@property(retain, nonatomic) UIImageView *footerImageView; // @synthesize footerImageView=_footerImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)prepareView;

@end

