//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackUnifiedSelectionViewController.h"

@interface AFContentPackDownloadUnifiedSelectionViewController : AFContentPackUnifiedSelectionViewController
{
}

- (void)didFinishDownloadingContentPack:(id)arg1;
- (void)didSelectContentPack:(id)arg1;
- (id)selectionView:(id)arg1 headerTitleForSection:(int)arg2;
- (void)selectionView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)selectionView:(id)arg1 selectionViewCellForRowAtIndexPath:(id)arg2;
- (int)selectionView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfRowsForUnlockedPackWithIndex:(int)arg1 originalItem:(BOOL)arg2;
- (int)numberOfSectionsInSelectionView:(id)arg1;
- (id)contentPackItemForIndexPath:(id)arg1;
- (id)contentPackForIndexPath:(id)arg1;
- (id)indexPathForContentPackItem:(id)arg1;
- (int)currentSectionShift;
- (BOOL)requiresSectionForOriginalItem;
- (id)cellForContentPack:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

