//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackIAPSelectionViewController.h"

#import "AFToolViewControllerDelegate.h"

@class AFContentPackDetailSelectionViewController, AFModule, UIActivityIndicatorView;

@interface AFContentPackListSelectionViewController : AFContentPackIAPSelectionViewController <AFToolViewControllerDelegate>
{
    BOOL _shouldAnimateCells;
    BOOL _shouldForwardButttonMessagesToDetailController;
    AFContentPackDetailSelectionViewController *_contentPackDetailViewController;
    AFModule *_contentPackDetailViewControllerOutputModule;
    UIActivityIndicatorView *_indicatorView;
}

+ (Class)detailViewControllerClass;
+ (Class)contentPackClass;
+ (BOOL)needsLayoutOnFailure;
@property(nonatomic) BOOL shouldForwardButttonMessagesToDetailController; // @synthesize shouldForwardButttonMessagesToDetailController=_shouldForwardButttonMessagesToDetailController;
@property(nonatomic) BOOL shouldAnimateCells; // @synthesize shouldAnimateCells=_shouldAnimateCells;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) AFModule *contentPackDetailViewControllerOutputModule; // @synthesize contentPackDetailViewControllerOutputModule=_contentPackDetailViewControllerOutputModule;
@property(retain, nonatomic) AFContentPackDetailSelectionViewController *contentPackDetailViewController; // @synthesize contentPackDetailViewController=_contentPackDetailViewController;
- (void).cxx_destruct;
- (id)outputModule;
- (void)finishApplying;
- (void)detailControllerApplied:(id)arg1;
- (void)toolController:(id)arg1 finishedWithStatus:(unsigned int)arg2;
- (void)dismissDetailSelectionViewController;
- (void)presentDetailSelectionViewControllerWithContentPack:(id)arg1 animated:(BOOL)arg2;
- (id)createDetailViewControllerWithPack:(id)arg1 ownSelectionView:(BOOL)arg2;
- (BOOL)transitionToDetailViewControllerOnLaunchIfNecessary;
- (void)applyButtonPressed:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)didSelectContentPack:(id)arg1;
- (void)selectionView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)cellForContentPack:(id)arg1;
- (id)selectionView:(id)arg1 selectionViewCellForRowAtIndexPath:(id)arg2;
- (int)selectionView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInSelectionView:(id)arg1;
- (void)didFinishDownloadingContentPack:(id)arg1;
- (void)updateContentPackSelectionViewAnimated:(BOOL)arg1;
- (id)contentPackForIndexPath:(id)arg1;
- (id)indexPathForContentPack:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)layoutSelectionViews;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;

@end

