//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFContentPackSelectionView, AFContentPackSelectionViewCell, NSIndexPath, NSString;

@protocol AFContentPackSelectionViewDelegate <NSObject>
- (int)numberOfRowsInFeaturedTrayInSelectionView:(AFContentPackSelectionView *)arg1;
- (NSString *)selectionView:(AFContentPackSelectionView *)arg1 headerTitleForSection:(int)arg2;
- (BOOL)selectionView:(AFContentPackSelectionView *)arg1 hasHeaderInSection:(int)arg2;
- (void)selectionView:(AFContentPackSelectionView *)arg1 didSelectRowAtIndexPath:(NSIndexPath *)arg2;
- (AFContentPackSelectionViewCell *)selectionView:(AFContentPackSelectionView *)arg1 selectionViewCellForRowAtIndexPath:(NSIndexPath *)arg2;
- (int)selectionView:(AFContentPackSelectionView *)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInSelectionView:(AFContentPackSelectionView *)arg1;

@optional
- (void)selectionViewWillEndDragging:(AFContentPackSelectionView *)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(struct CGPoint *)arg3;
- (void)selectionViewDidEndScrollingAnimation:(AFContentPackSelectionView *)arg1;
- (void)selectionViewDidPressGetMore:(AFContentPackSelectionView *)arg1 side:(int)arg2;
- (float)selectionView:(AFContentPackSelectionView *)arg1 heightForRowAtIndexPath:(NSIndexPath *)arg2;
@end

