//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackDetailIAPViewController.h"

@class AFEffectContentPackThumnailGenerator;

@interface AFEffectContentPackDetailIAPViewController : AFContentPackDetailIAPViewController
{
    AFEffectContentPackThumnailGenerator *_thumbnailGenerator;
}

+ (id)titleDescriptor;
+ (id)countDescriptor;
@property(retain, nonatomic) AFEffectContentPackThumnailGenerator *thumbnailGenerator; // @synthesize thumbnailGenerator=_thumbnailGenerator;
- (void).cxx_destruct;
- (void)viewDidAppear:(BOOL)arg1;
- (id)scrollBar:(id)arg1 itemViewForContentPackItems:(id)arg2;

@end

