//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFBitmapImageServer, AFOpenGLInstance, NSCache, UIImage;

@interface AFEffectContentPackThumnailGenerator : NSObject
{
    NSCache *_thumbnailCache;
    UIImage *_originalImage;
    AFOpenGLInstance *_glInstance;
    AFBitmapImageServer *_imageServer;
    struct CGSize _thumbnailSize;
}

@property(retain, nonatomic) AFBitmapImageServer *imageServer; // @synthesize imageServer=_imageServer;
@property(nonatomic) struct CGSize thumbnailSize; // @synthesize thumbnailSize=_thumbnailSize;
@property(retain, nonatomic) AFOpenGLInstance *glInstance; // @synthesize glInstance=_glInstance;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(retain, nonatomic) NSCache *thumbnailCache; // @synthesize thumbnailCache=_thumbnailCache;
- (void).cxx_destruct;
- (void)thumbnailForEffectContentPackItem:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithGLInstance:(id)arg1 andThumbnailSize:(struct CGSize)arg2;

@end

