//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackUnifiedSelectionViewCell.h"

@class AFImageView, UIActivityIndicatorView, UIImageView;

@interface AFEffectContentPackUnifiedSelectionViewCell : AFContentPackUnifiedSelectionViewCell
{
    AFImageView *_previewImageView;
    UIImageView *_outlineImageView;
    UIActivityIndicatorView *_activityIndicator;
}

@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UIImageView *outlineImageView; // @synthesize outlineImageView=_outlineImageView;
@property(retain, nonatomic) AFImageView *previewImageView; // @synthesize previewImageView=_previewImageView;
- (void).cxx_destruct;
- (void)finishedLoadingPreviewWithContext:(id)arg1;
- (void)setImageViewContext:(id)arg1;
- (void)setContentPackItem:(id)arg1;
- (void)setContentPack:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

