//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackItem.h"

@class AFModule, NSString, UIImage;

@interface AFEffectContentPackItem : AFContentPackItem
{
    UIImage *_previewImage;
}

+ (id)entityName;
+ (void)initialize;
- (void).cxx_destruct;
- (void)willTurnIntoFault;
@property(readonly, nonatomic) UIImage *previewImage; // @synthesize previewImage=_previewImage;
@property(readonly, nonatomic) AFModule *module; // @dynamic module;

// Remaining properties
@property(retain, nonatomic) NSString *effectJSON; // @dynamic effectJSON;

@end

