//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFToolViewController.h"

#import "AFSegmentedControlDelegate.h"

@class AFModule, AFSegmentedControl, NSArray;

@interface AFEnhanceViewController : AFToolViewController <AFSegmentedControlDelegate>
{
    AFModule *_activeModule;
    NSArray *_modules;
    NSArray *_moduleKeyNames;
    AFSegmentedControl *_segmentedControl;
    int _selectedIndex;
}

+ (id)customizationKeyPath;
+ (BOOL)needsLayoutOnFailure;
@property(nonatomic) int selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(retain, nonatomic) AFSegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(retain, nonatomic) NSArray *moduleKeyNames; // @synthesize moduleKeyNames=_moduleKeyNames;
@property(retain, nonatomic) NSArray *modules; // @synthesize modules=_modules;
@property(retain, nonatomic) AFModule *activeModule; // @synthesize activeModule=_activeModule;
- (void).cxx_destruct;
- (BOOL)supportsViewOriginalWithTouch;
- (void)reportApplied;
- (id)outputModule;
- (void)segmentedControl:(id)arg1 didDeselectItemAtIndex:(int)arg2;
- (void)segmentedControl:(id)arg1 didSelectItemAtIndex:(int)arg2;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)viewWillDisappear:(BOOL)arg1;
- (id)initWithGLInstance:(id)arg1 settings:(id)arg2 quickLaunch:(BOOL)arg3;

@end

