//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackItem.h"

@class NSNumber, UIImage;

@interface AFFrameContentPackItem : AFContentPackItem
{
    UIImage *_topImage;
    UIImage *_topRightImage;
    UIImage *_rightImage;
    UIImage *_bottomRightImage;
    UIImage *_bottomImage;
    UIImage *_bottomLeftImage;
    UIImage *_leftImage;
    UIImage *_topLeftImage;
    UIImage *_topImageEditing;
    UIImage *_topRightImageEditing;
    UIImage *_rightImageEditing;
    UIImage *_bottomRightImageEditing;
    UIImage *_bottomImageEditing;
    UIImage *_bottomLeftImageEditing;
    UIImage *_leftImageEditing;
    UIImage *_topLeftImageEditing;
}

+ (id)entityName;
@property(retain, nonatomic) UIImage *topLeftImageEditing; // @synthesize topLeftImageEditing=_topLeftImageEditing;
@property(retain, nonatomic) UIImage *leftImageEditing; // @synthesize leftImageEditing=_leftImageEditing;
@property(retain, nonatomic) UIImage *bottomLeftImageEditing; // @synthesize bottomLeftImageEditing=_bottomLeftImageEditing;
@property(retain, nonatomic) UIImage *bottomImageEditing; // @synthesize bottomImageEditing=_bottomImageEditing;
@property(retain, nonatomic) UIImage *bottomRightImageEditing; // @synthesize bottomRightImageEditing=_bottomRightImageEditing;
@property(retain, nonatomic) UIImage *rightImageEditing; // @synthesize rightImageEditing=_rightImageEditing;
@property(retain, nonatomic) UIImage *topRightImageEditing; // @synthesize topRightImageEditing=_topRightImageEditing;
@property(retain, nonatomic) UIImage *topImageEditing; // @synthesize topImageEditing=_topImageEditing;
@property(retain, nonatomic) UIImage *topLeftImage; // @synthesize topLeftImage=_topLeftImage;
@property(retain, nonatomic) UIImage *leftImage; // @synthesize leftImage=_leftImage;
@property(retain, nonatomic) UIImage *bottomLeftImage; // @synthesize bottomLeftImage=_bottomLeftImage;
@property(retain, nonatomic) UIImage *bottomImage; // @synthesize bottomImage=_bottomImage;
@property(retain, nonatomic) UIImage *bottomRightImage; // @synthesize bottomRightImage=_bottomRightImage;
@property(retain, nonatomic) UIImage *rightImage; // @synthesize rightImage=_rightImage;
@property(retain, nonatomic) UIImage *topRightImage; // @synthesize topRightImage=_topRightImage;
@property(retain, nonatomic) UIImage *topImage; // @synthesize topImage=_topImage;
- (void).cxx_destruct;
- (void)willTurnIntoFault;
- (id)thumbnailImage;

// Remaining properties
@property(retain, nonatomic) NSNumber *width; // @dynamic width;

@end

