//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AFImageViewContext : NSObject
{
    id <AFImageViewContextDelegate> _delegate;
}

@property(nonatomic) __weak id <AFImageViewContextDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setImage:(id)arg1;

@end

