//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFOpenGLInstance;

@interface AFImageServer : NSObject
{
    struct CGImage *_inputImage;
    struct CGSize _size;
    float _scale;
    int _originalOrientation;
    int _orientation;
    BOOL _bordersEnabled;
    AFOpenGLInstance *_glInstance;
}

@property(retain, nonatomic) AFOpenGLInstance *glInstance; // @synthesize glInstance=_glInstance;
@property(nonatomic) BOOL bordersEnabled; // @synthesize bordersEnabled=_bordersEnabled;
@property int orientation; // @synthesize orientation=_orientation;
@property int originalOrientation; // @synthesize originalOrientation=_originalOrientation;
@property float scale; // @synthesize scale=_scale;
@property struct CGSize size; // @synthesize size=_size;
@property(readonly, nonatomic) struct CGImage *inputImage; // @synthesize inputImage=_inputImage;
- (void).cxx_destruct;
- (void)releaseInputImage;
- (void)commit;
- (void)cleanup;
- (void)setPixelsWithSnapshot:(id)arg1;
- (void)takeSnapshot:(CDUnknownBlockType)arg1;
- (void)cancelProcessing;
- (void)getProcessedImageSizeAndDataOnCurrentThread:(CDUnknownBlockType)arg1;
- (void)getProcessedImageSizeAndData:(CDUnknownBlockType)arg1;
- (void)getProcessedImageAndDataOnCurrentThread:(CDUnknownBlockType)arg1;
- (void)getProcessedImageAndData:(CDUnknownBlockType)arg1;
- (void)getProcessedImage:(CDUnknownBlockType)arg1;
- (void)runModule:(id)arg1;
- (void)runModule:(id)arg1 preprocess:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)runProcessor:(id)arg1;
- (void)resetOrientation;
- (void)cropImageToRect:(struct CGRect)arg1;
- (void)drawImageWithOrientation:(int)arg1;
- (void)drawStraightenedwithRotation:(float)arg1 scale:(float)arg2 orientation:(int)arg3;
- (void)drawTransformedImageWithOrientation:(int)arg1;
- (void)drawImageOnCurrentThread;
- (void)drawImage;
- (void)setInputImage:(struct CGImage *)arg1;
- (id)initWithCGImage:(struct CGImage *)arg1;
- (id)initWithCGImage:(struct CGImage *)arg1 scale:(float)arg2;
- (id)initHeadlessWithCGImage:(struct CGImage *)arg1 scale:(float)arg2 orientation:(int)arg3;
- (id)initWithCGImage:(struct CGImage *)arg1 scale:(float)arg2 orientation:(int)arg3;
- (id)initWithCGImage:(struct CGImage *)arg1 scale:(float)arg2 orientation:(int)arg3 glInstance:(id)arg4 fromGLQueue:(BOOL)arg5;
- (id)initWithCGImage:(struct CGImage *)arg1 scale:(float)arg2 orientation:(int)arg3 glInstance:(id)arg4;
- (id)initWithGLInstance:(id)arg1;
- (void)dealloc;

@end

