//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFOverlayView.h"

#import "AFTextFieldDelegate.h"

@class AFMemeTextView, AFScrollingImageView;

@interface AFMemeOverlayView : AFOverlayView <AFTextFieldDelegate>
{
    BOOL _observingKeyboard;
    BOOL _keyboardShowing;
    AFMemeTextView *_textView;
    AFMemeTextView *_bottomTextView;
    AFScrollingImageView *_scrollingImageView;
    id <AFMemeOverlayViewDelegate> _delegate;
    int _currentTextView;
    float _keyboardOverlap;
}

@property(nonatomic) float keyboardOverlap; // @synthesize keyboardOverlap=_keyboardOverlap;
@property(nonatomic) int currentTextView; // @synthesize currentTextView=_currentTextView;
@property(nonatomic) __weak id <AFMemeOverlayViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak AFScrollingImageView *scrollingImageView; // @synthesize scrollingImageView=_scrollingImageView;
@property(retain, nonatomic) AFMemeTextView *bottomTextView; // @synthesize bottomTextView=_bottomTextView;
@property(nonatomic, getter=isKeyboardShowing) BOOL keyboardShowing; // @synthesize keyboardShowing=_keyboardShowing;
@property(nonatomic, getter=isObservingKeyboard) BOOL observingKeyboard; // @synthesize observingKeyboard=_observingKeyboard;
@property(retain, nonatomic) AFMemeTextView *topTextView; // @synthesize topTextView=_textView;
- (void).cxx_destruct;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)resizeForKeyboard:(id)arg1 up:(BOOL)arg2;
- (void)keyboardDidHide_AF:(id)arg1;
- (void)keyboardWillHide_AF:(id)arg1;
- (void)keyboardWillShow_AF:(id)arg1;
- (void)stopObservingKeyboard;
- (void)startObservingKeyboard;
- (void)scrollToOriginalPosition;
- (void)drawTextBox:(int)arg1 inRect:(struct CGRect)arg2;
- (void)setUserInteractionEnabled:(BOOL)arg1;
- (void)createFont;
- (void)setScale:(float)arg1;
- (void)setInputAccessoryView:(id)arg1;
- (void)layoutSubviews;
- (void)prepareView;

@end

