//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFView.h"

@class UIButton, UILabel;

@interface AFMemeTextField : AFView
{
    BOOL _topTextField;
    UILabel *_label;
    id <AFMemeTextFieldDelegate> _delegate;
    AFView *_contentView;
    UIButton *_clearButton;
}

@property(retain, nonatomic) UIButton *clearButton; // @synthesize clearButton=_clearButton;
@property(retain, nonatomic) AFView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic, getter=isTopTextField) BOOL topTextField; // @synthesize topTextField=_topTextField;
@property(nonatomic) __weak id <AFMemeTextFieldDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)textFieldTouched;
- (void)clearButtonPressed;
- (void)setText:(id)arg1;
- (id)configLabel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

