//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFManagedObject.h"

@class AFContentPack, AFMessageText, NSArray, NSDate, NSNumber, NSSet, NSString;

@interface AFMessage : AFManagedObject
{
}

+ (id)entityName;
+ (id)messageToDisplay;
- (void)deletePropertyIfNecessary:(id)arg1;
- (void)cleanupAssetsWithSave:(BOOL)arg1;
- (void)cleanupAssets;
- (BOOL)availableForUse;
@property(readonly, nonatomic) AFContentPack *targetPack;
- (void)updateRelationship:(id)arg1 withValue:(id)arg2;
- (void)updateAttribute:(id)arg1 withValue:(id)arg2;
@property(readonly, nonatomic) NSString *bannerImageFilename; // @dynamic bannerImageFilename;
@property(readonly, nonatomic) NSArray *orderedBullets;
- (void)awakeFromInsert;

// Remaining properties
@property(retain, nonatomic) NSString *action; // @dynamic action;
@property(retain, nonatomic) AFMessageText *actionButtonText; // @dynamic actionButtonText;
@property(retain, nonatomic) NSNumber *assetsRemoved; // @dynamic assetsRemoved;
@property(retain, nonatomic) NSString *bannerImageIdentifier; // @dynamic bannerImageIdentifier;
@property(retain, nonatomic) NSDate *beginDate; // @dynamic beginDate;
@property(retain, nonatomic) NSSet *bullets; // @dynamic bullets;
@property(retain, nonatomic) NSString *contentIdentifier; // @dynamic contentIdentifier;
@property(retain, nonatomic) AFMessageText *dismissButtonText; // @dynamic dismissButtonText;
@property(retain, nonatomic) NSDate *endDate; // @dynamic endDate;
@property(retain, nonatomic) NSNumber *hasBeenShown; // @dynamic hasBeenShown;
@property(retain, nonatomic) AFMessageText *header; // @dynamic header;
@property(retain, nonatomic) NSString *identifier; // @dynamic identifier;
@property(retain, nonatomic) NSNumber *isSplitButton; // @dynamic isSplitButton;
@property(retain, nonatomic) NSString *layoutStyle; // @dynamic layoutStyle;
@property(retain, nonatomic) AFMessageText *paragraph; // @dynamic paragraph;
@property(retain, nonatomic) NSNumber *shouldDelete; // @dynamic shouldDelete;
@property(retain, nonatomic) NSNumber *showsNewBanner; // @dynamic showsNewBanner;
@property(retain, nonatomic) NSArray *targetPacks; // @dynamic targetPacks;
@property(retain, nonatomic) NSDate *timestamp; // @dynamic timestamp;
@property(retain, nonatomic) AFMessageText *title; // @dynamic title;

@end

