//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFErrorOperation.h"

@interface AFMessageUpdateCompletionOperation : AFErrorOperation
{
    int _pendingVersion;
    CDUnknownBlockType _completionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(nonatomic) int pendingVersion; // @synthesize pendingVersion=_pendingVersion;
- (void).cxx_destruct;
- (void)main;
- (id)initWithPendingManifestVersion:(int)arg1 fetchOperations:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;

@end

