//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AFMessage, UIButton, UIImageView;

@interface AFMessageView : UIView
{
    AFMessage *_message;
    CDUnknownBlockType _actionBlock;
    UIView *_bannerContainerView;
    UIImageView *_bannerView;
    UIImageView *_flagView;
    UIImageView *_buttonContainerView;
    UIButton *_dismissButton;
    UIButton *_actionButton;
    UIView *_dimmerView;
    UIView *_bodyView;
}

+ (id)messageViewWithMessage:(id)arg1;
@property(retain, nonatomic) UIView *bodyView; // @synthesize bodyView=_bodyView;
@property(retain, nonatomic) UIView *dimmerView; // @synthesize dimmerView=_dimmerView;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UIButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(retain, nonatomic) UIImageView *buttonContainerView; // @synthesize buttonContainerView=_buttonContainerView;
@property(retain, nonatomic) UIImageView *flagView; // @synthesize flagView=_flagView;
@property(retain, nonatomic) UIImageView *bannerView; // @synthesize bannerView=_bannerView;
@property(retain, nonatomic) UIView *bannerContainerView; // @synthesize bannerContainerView=_bannerContainerView;
@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
@property(retain, nonatomic) AFMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (void)dismiss;
- (void)presentInView:(id)arg1;
- (void)actionButtonPressed:(id)arg1;
- (void)dismissButtonPressed:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (float)bodyHeight;
- (id)bodyViewForWidth:(float)arg1;
- (void)layoutButtons;
- (void)layoutSubviews;
- (void)createDismissButtonWithActionColor:(BOOL)arg1 text:(id)arg2;
- (void)createActionButtonWithText:(id)arg1;
- (void)prepareView;
- (id)initWithMessage:(id)arg1;

@end

