//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary;

@interface AFModule : NSObject
{
    BOOL _bordersEnabled;
    BOOL _willRunOnCPU;
    NSMutableDictionary *_options;
    float _scaleFactor;
    unsigned int _parameterSeed;
}

+ (id)name;
+ (void)forceLinkerLoad_;
@property(nonatomic) BOOL willRunOnCPU; // @synthesize willRunOnCPU=_willRunOnCPU;
@property(nonatomic) unsigned int parameterSeed; // @synthesize parameterSeed=_parameterSeed;
@property(nonatomic) BOOL bordersEnabled; // @synthesize bordersEnabled=_bordersEnabled;
@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(retain, nonatomic) NSMutableDictionary *options; // @synthesize options=_options;
- (void).cxx_destruct;
- (void)setOption:(id)arg1 toFloatValue:(float)arg2;
- (float)getOption:(id)arg1;
@property(readonly, nonatomic) NSArray *processors; // @dynamic processors;
- (void)preprocess:(id)arg1;
- (void)createBorderProcessors:(id)arg1;
- (void)createProcessors:(id)arg1;
- (id)init;

@end

