//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSString, UIImage, UIImageView, UILabel;

@interface AFNavigationItemButton : UIControl
{
    BOOL _showsDisabledState;
    UILabel *_titleLabel;
    unsigned int _style;
    UIImage *_backgroundImage;
    UIImage *_highlightedBackgroundImage;
    UIImageView *_imageView;
    UIImageView *_iconView;
}

+ (id)buttonWithTitle:(id)arg1 style:(unsigned int)arg2 target:(id)arg3 action:(SEL)arg4;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIImage *highlightedBackgroundImage; // @synthesize highlightedBackgroundImage=_highlightedBackgroundImage;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(nonatomic) unsigned int style; // @synthesize style=_style;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) BOOL showsDisabledState; // @synthesize showsDisabledState=_showsDisabledState;
- (void).cxx_destruct;
- (id)highlightedImageForStyle:(unsigned int)arg1;
- (id)defaultImageForStyle:(unsigned int)arg1;
@property(copy, nonatomic) NSString *title; // @dynamic title;
- (void)setHighlighted:(BOOL)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1 andStyle:(unsigned int)arg2;

@end

