//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationBar.h"

@class CAGradientLayer, UIImage;

@interface AFNavigationBar : UINavigationBar
{
    CAGradientLayer *_gradientLayer;
    UIImage *_backgroundImage;
}

+ (void)forceLinkerLoad_;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)backIndicatorImage;
- (void)prepareView;
- (void)prepareLayer:(id)arg1;

@end

