//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface AFOption : NSObject
{
    id _defaultValue;
    CDUnknownBlockType _validator;
    NSMutableDictionary *_values;
}

+ (id)optionWithOption:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *values; // @synthesize values=_values;
@property(copy, nonatomic) CDUnknownBlockType validator; // @synthesize validator=_validator;
@property(retain, nonatomic) id defaultValue; // @synthesize defaultValue=_defaultValue;
- (void).cxx_destruct;
- (BOOL)validateValue:(id)arg1;
- (id)valueWithModifier:(id)arg1;
- (BOOL)isEmpty;
- (void)removeValueForModifier:(id)arg1;
- (BOOL)hasValueForModifier:(id)arg1;
- (void)setValueWithBlock:(CDUnknownBlockType)arg1 withModifier:(id)arg2;
- (void)setValue:(id)arg1 withModifier:(id)arg2;
- (id)initWithDefaultValue:(id)arg1 expectedClass:(Class)arg2;
- (id)initWithDefaultValue:(id)arg1;
- (id)initWithDefaultValue:(id)arg1 validate:(CDUnknownBlockType)arg2;

@end

