//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFModule.h"

@interface AFOrientationModule : AFModule
{
    BOOL _basedOnCurrentOrientation;
    BOOL _isHiRes;
    int _orientation;
    float _rotation;
    float _scale;
    struct CGSize _originalSize;
    struct CGAffineTransform _transform;
}

@property(nonatomic) BOOL isHiRes; // @synthesize isHiRes=_isHiRes;
@property(nonatomic) struct CGSize originalSize; // @synthesize originalSize=_originalSize;
@property(nonatomic) struct CGAffineTransform transform; // @synthesize transform=_transform;
@property(nonatomic) float scale; // @synthesize scale=_scale;
@property(nonatomic) float rotation; // @synthesize rotation=_rotation;
@property(nonatomic) BOOL basedOnCurrentOrientation; // @synthesize basedOnCurrentOrientation=_basedOnCurrentOrientation;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
- (void)createProcessors:(id)arg1;
- (void)preprocess:(id)arg1;
- (id)init;

@end

