//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AFHorizontalTableView, AFPageControl;

@interface AFPagingView : AFView <UITableViewDelegate, UITableViewDataSource>
{
    AFHorizontalTableView *_horizontalTableView;
    int _numberOfItems;
    int _numberOfItemsPerPage;
    int _numberOfPages;
    int _numberOfColumns;
    int _currentPage;
    float _extraColumnWidth;
    id <AFPagingViewDelegate> _delegate;
    float _cellWidth;
    int _maximumItemsPerPage;
    AFPageControl *_pageControl;
}

@property(nonatomic) __weak AFPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) int maximumItemsPerPage; // @synthesize maximumItemsPerPage=_maximumItemsPerPage;
@property(nonatomic) float cellWidth; // @synthesize cellWidth=_cellWidth;
@property(nonatomic) __weak id <AFPagingViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) float extraColumnWidth; // @synthesize extraColumnWidth=_extraColumnWidth;
@property(nonatomic) int currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) int numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(nonatomic) int numberOfPages; // @synthesize numberOfPages=_numberOfPages;
@property(nonatomic) int numberOfItemsPerPage; // @synthesize numberOfItemsPerPage=_numberOfItemsPerPage;
@property(nonatomic) int numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(nonatomic) __weak AFHorizontalTableView *horizontalTableView; // @synthesize horizontalTableView=_horizontalTableView;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)itemIndexForCell:(id)arg1;
- (int)itemIndexForIndexPath:(id)arg1;
- (BOOL)isIndexPathBookend:(id)arg1;
- (void)updateCurrentPage;
- (void)layoutSubviews;
- (void)prepareView;

@end

