//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AFProcessor : NSObject
{
    float _scaleFactor;
}

+ (id)processorWithBitmapBlock:(CDUnknownBlockType)arg1;
@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
- (void)setDefaults;
- (id)init;
- (struct CGSize)outputSizeForInputSize:(struct CGSize)arg1;
@property(readonly, nonatomic) CDUnknownBlockType moaBitmapBlock; // @dynamic moaBitmapBlock;
@property(readonly, nonatomic) CDUnknownBlockType bitmapBlock; // @dynamic bitmapBlock;

@end

