//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFResetOverlayView;

@protocol AFResetOverlayViewDelegate <NSObject>
- (void)resetOverlay:(AFResetOverlayView *)arg1 pressedButtonAtIndex:(unsigned int)arg2;
@end

