//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFView.h"

#import "UIScrollViewDelegate.h"

@class AFPageControl, NSMutableDictionary, NSMutableSet, UIScrollView;

@interface AFScrollBarView : AFView <UIScrollViewDelegate>
{
    int firstVisiblePageIndexBeforeRotation;
    float percentScrolledIntoFirstVisiblePage;
    BOOL _extraPage;
    UIScrollView *_scrollView;
    NSMutableSet *_recycledPages;
    NSMutableSet *_visiblePages;
    NSMutableDictionary *_recycledItems;
    unsigned int _numberOfPages;
    unsigned int _numberOfColumnsPerPage;
    unsigned int _maxNumberOfColumnsPerPage;
    unsigned int _currentPage;
    id <AFScrollBarViewDelegate> _delegate;
    AFPageControl *_pageControl;
    unsigned int _numberOfColumns;
    float _columnWidth;
}

@property(nonatomic) BOOL extraPage; // @synthesize extraPage=_extraPage;
@property(nonatomic) float columnWidth; // @synthesize columnWidth=_columnWidth;
@property(nonatomic) unsigned int numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(nonatomic) __weak AFPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) __weak id <AFScrollBarViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) unsigned int maxNumberOfColumnsPerPage; // @synthesize maxNumberOfColumnsPerPage=_maxNumberOfColumnsPerPage;
@property(nonatomic) unsigned int numberOfColumnsPerPage; // @synthesize numberOfColumnsPerPage=_numberOfColumnsPerPage;
@property(retain, nonatomic) NSMutableDictionary *recycledItems; // @synthesize recycledItems=_recycledItems;
@property(retain, nonatomic) NSMutableSet *visiblePages; // @synthesize visiblePages=_visiblePages;
@property(retain, nonatomic) NSMutableSet *recycledPages; // @synthesize recycledPages=_recycledPages;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)reloadPagesAndGoToPage:(int)arg1 offsetInPage:(float)arg2;
- (void)goToPage:(int)arg1;
- (void)goToPage:(int)arg1 offsetInPage:(float)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (struct CGSize)contentSizeForScrollView;
- (struct CGRect)frameForPageAtIndex:(unsigned int)arg1;
- (struct CGRect)frameForScrollView;
@property(readonly, nonatomic) float pageItemOffset; // @dynamic pageItemOffset;
- (void)configurePage:(id)arg1 forIndex:(unsigned int)arg2;
- (BOOL)isDisplayingPageForIndex:(unsigned int)arg1;
- (id)dequeueRecycledPage;
- (void)tilePages;
- (id)dequeueReusableItemWithIdentifier:(id)arg1;
- (void)enqueueReusableItem:(id)arg1;
- (void)layoutSubviews;
- (void)setNeedsReload;
@property(nonatomic) unsigned int numberOfPages; // @synthesize numberOfPages=_numberOfPages;
- (void)prepareView;

@end

