//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFScrollBarPageItemView, AFScrollBarView, UIView;

@protocol AFScrollBarViewDelegate <NSObject>
- (AFScrollBarPageItemView *)scrollBar:(AFScrollBarView *)arg1 itemViewForColumnAtIndex:(unsigned int)arg2;
- (unsigned int)numberOfItemsInScrollBar:(AFScrollBarView *)arg1;

@optional
- (void)scrollBar:(AFScrollBarView *)arg1 didScrollToPage:(int)arg2;
- (void)scrollBar:(AFScrollBarView *)arg1 willScrollToPage:(int)arg2;
- (UIView *)viewForExtraPageInScrollBar:(AFScrollBarView *)arg1;
@end

