//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFView.h"

@class AFScrollBarView, NSMutableArray;

@interface AFScrollBarPageView : AFView
{
    NSMutableArray *_items;
    AFScrollBarView *_scrollBar;
    unsigned int _index;
}

@property(nonatomic) unsigned int index; // @synthesize index=_index;
@property(readonly, nonatomic) AFScrollBarView *scrollBar; // @synthesize scrollBar=_scrollBar;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)reloadItems;
- (void)updateWithItemsForIndex:(unsigned int)arg1;
- (void)prepareView;
- (id)initWithScrollBar:(id)arg1;

@end

