//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFView.h"

@class UIImageView;

@interface AFScalableViewHandle : AFView
{
    int _handleMask;
    int _handleType;
    UIImageView *_knobView;
}

@property(retain, nonatomic) UIImageView *knobView; // @synthesize knobView=_knobView;
@property(nonatomic) int handleType; // @synthesize handleType=_handleType;
@property(nonatomic) int handleMask; // @synthesize handleMask=_handleMask;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)prepareView;

@end

