//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class AFSegmentedControl, UIImageView;

@interface AFSegmentButton : UIButton
{
    AFSegmentedControl *_segmentedControl;
    UIImageView *_iconImageView;
    UIImageView *_backgroundImageView;
    int _style;
}

@property(nonatomic) int style; // @synthesize style=_style;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak AFSegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
- (void).cxx_destruct;
- (void)setSelected:(BOOL)arg1;
- (void)layoutSubviews;
- (id)imageForStyle:(int)arg1 highlighted:(BOOL)arg2;
- (id)initWithFrame:(struct CGRect)arg1 style:(int)arg2 defaultIcon:(id)arg3 highlightedIcon:(id)arg4;

@end

