//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFBrushViewController.h"

@class AFSelectiveBrushProcessor;

@interface AFSelectiveBrushViewController : AFBrushViewController
{
    BOOL _didDrawImage;
    AFSelectiveBrushProcessor *_processor;
}

@property(nonatomic) BOOL didDrawImage; // @synthesize didDrawImage=_didDrawImage;
@property(retain, nonatomic) AFSelectiveBrushProcessor *processor; // @synthesize processor=_processor;
- (void).cxx_destruct;
- (void)processStroke:(id)arg1;
- (id)outputModuleWithStrokes:(id)arg1;
- (void)didFinishStroke:(id)arg1;
- (void)didBeginStroke:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithGLInstance:(id)arg1 processor:(id)arg2;

@end

