//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFProcessor.h"

@class AFOpenGLInstance, AFOpenGLInstanceRenderingObjects, NSArray;

@interface AFSelectiveBrushProcessor : AFProcessor
{
    BOOL _isHires;
    NSArray *_brushStrokes;
    AFOpenGLInstance *_glInstance;
    AFOpenGLInstanceRenderingObjects *_processedTextureRenderingObjects;
    AFOpenGLInstanceRenderingObjects *_maskTextureRenderingObjects;
    struct CGSize _maskSize;
}

@property(retain, nonatomic) AFOpenGLInstanceRenderingObjects *maskTextureRenderingObjects; // @synthesize maskTextureRenderingObjects=_maskTextureRenderingObjects;
@property(retain, nonatomic) AFOpenGLInstanceRenderingObjects *processedTextureRenderingObjects; // @synthesize processedTextureRenderingObjects=_processedTextureRenderingObjects;
@property(retain, nonatomic) AFOpenGLInstance *glInstance; // @synthesize glInstance=_glInstance;
@property(nonatomic) BOOL isHires; // @synthesize isHires=_isHires;
@property(nonatomic) struct CGSize maskSize; // @synthesize maskSize=_maskSize;
@property(retain, nonatomic) NSArray *brushStrokes; // @synthesize brushStrokes=_brushStrokes;
- (void).cxx_destruct;
- (float)brushAlpha;
- (BOOL)effectedImageOnTop;
- (BOOL)shouldRenderWithNoStrokes;
- (int)moaCPUToolType;
- (unsigned int)runMoaPreprocessFunction:(struct MoaBitmap *)arg1;
- (void)dealloc;
- (void)drawPointsGPU:(id)arg1 withStroke:(id)arg2 targetColorIfApplicable:(struct MoaColor_rgba *)arg3 onBitmap:(struct MoaBitmap *)arg4 withMaskSize:(struct CGSize)arg5;
- (void)drawPointsCPU:(id)arg1 onBitmap:(struct MoaBitmap *)arg2 mask:(struct MoaBitmap *)arg3 drawParams:(struct MoaToolDrawParams *)arg4 withMaskSize:(struct CGSize)arg5;
- (void)addEndingLineSegmentFromPoint:(struct CGPoint)arg1 toMidpointWithPoint:(struct CGPoint)arg2 maxSeparation:(float)arg3 toArray:(id)arg4 withMaskSize:(struct CGSize)arg5;
- (void)addBezierQuadCurveFromPoint1:(struct CGPoint)arg1 point2:(struct CGPoint)arg2 point3:(struct CGPoint)arg3 maxSeparation:(float)arg4 toArray:(id)arg5 withMaskSize:(struct CGSize)arg6;
- (void)addBeginningLineSegmentFromPoint:(struct CGPoint)arg1 toMidpointWithPoint:(struct CGPoint)arg2 maxSeparation:(float)arg3 toArray:(id)arg4 withMaskSize:(struct CGSize)arg5;
- (void)setStrokeColor:(id)arg1 fromBitmap:(struct MoaBitmap *)arg2 withGLInstance:(id)arg3;
- (CDUnknownBlockType)moaBitmapBlock;

@end

