//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray;

@interface AFSegmentedControl : UIView
{
    BOOL _momentary;
    BOOL _allowsDeselection;
    id <AFSegmentedControlDelegate> _delegate;
    int _selectedIndex;
    NSMutableArray *_segmentItems;
    UIView *_buttonView;
    NSArray *_buttons;
    NSArray *_defaultNames;
    NSArray *_highlightedNames;
}

@property(retain, nonatomic) NSArray *highlightedNames; // @synthesize highlightedNames=_highlightedNames;
@property(retain, nonatomic) NSArray *defaultNames; // @synthesize defaultNames=_defaultNames;
@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(retain, nonatomic) UIView *buttonView; // @synthesize buttonView=_buttonView;
@property(retain, nonatomic) NSMutableArray *segmentItems; // @synthesize segmentItems=_segmentItems;
@property(nonatomic) BOOL allowsDeselection; // @synthesize allowsDeselection=_allowsDeselection;
@property(nonatomic, getter=isMomentary) BOOL momentary; // @synthesize momentary=_momentary;
@property(nonatomic) int selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) __weak id <AFSegmentedControlDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)buttonPressed:(id)arg1;
- (void)deselectAll;
- (void)pressButtonAtIndex:(int)arg1;
- (void)buttonUnpressed:(id)arg1;
- (void)layoutSubviews;
- (void)prepareView;
- (id)initWithFrame:(struct CGRect)arg1 defaultIconNames:(id)arg2 highlightedIconNames:(id)arg3;

@end

