//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "UIGestureRecognizerDelegate.h"

@class AFView, UIImageView;

@interface AFSlider : UIControl <UIGestureRecognizerDelegate>
{
    float _maximumValue;
    float _minimumValue;
    UIImageView *_centerImageView;
    UIImageView *_rightStretchableImageView;
    UIImageView *_rightCapImageView;
    UIImageView *_leftStretchableImageView;
    UIImageView *_leftCapImageView;
    UIImageView *_rightGooImageView;
    UIImageView *_rightGooImageViewActive;
    UIImageView *_leftGooImageView;
    UIImageView *_leftGooImageViewActive;
    float _sliderPosition;
    AFView *_handleContainerView;
    struct CGPoint _beginTouchPoint;
}

@property(nonatomic) struct CGPoint beginTouchPoint; // @synthesize beginTouchPoint=_beginTouchPoint;
@property(retain, nonatomic) AFView *handleContainerView; // @synthesize handleContainerView=_handleContainerView;
@property(nonatomic) float sliderPosition; // @synthesize sliderPosition=_sliderPosition;
@property(retain, nonatomic) UIImageView *leftGooImageViewActive; // @synthesize leftGooImageViewActive=_leftGooImageViewActive;
@property(retain, nonatomic) UIImageView *leftGooImageView; // @synthesize leftGooImageView=_leftGooImageView;
@property(retain, nonatomic) UIImageView *rightGooImageViewActive; // @synthesize rightGooImageViewActive=_rightGooImageViewActive;
@property(retain, nonatomic) UIImageView *rightGooImageView; // @synthesize rightGooImageView=_rightGooImageView;
@property(retain, nonatomic) UIImageView *leftCapImageView; // @synthesize leftCapImageView=_leftCapImageView;
@property(retain, nonatomic) UIImageView *leftStretchableImageView; // @synthesize leftStretchableImageView=_leftStretchableImageView;
@property(retain, nonatomic) UIImageView *rightCapImageView; // @synthesize rightCapImageView=_rightCapImageView;
@property(retain, nonatomic) UIImageView *rightStretchableImageView; // @synthesize rightStretchableImageView=_rightStretchableImageView;
@property(retain, nonatomic) UIImageView *centerImageView; // @synthesize centerImageView=_centerImageView;
@property(nonatomic) float minimumValue; // @synthesize minimumValue=_minimumValue;
@property(nonatomic) float maximumValue; // @synthesize maximumValue=_maximumValue;
- (void).cxx_destruct;
@property(nonatomic) float value; // @dynamic value;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)doubleTapDetected:(id)arg1;
- (void)longPressDetected:(id)arg1;
- (void)panDetected:(id)arg1;
- (void)updateSliderHandleAndGooAnimated:(BOOL)arg1;
- (void)layoutSubviews;
- (void)prepareView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

