//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIImageView;

@interface AFSpotEditingZoomButton : UIControl
{
    BOOL _visible;
    BOOL _zoomEnabled;
    UIImageView *_zoomImageView;
}

@property(retain, nonatomic) UIImageView *zoomImageView; // @synthesize zoomImageView=_zoomImageView;
@property(nonatomic, getter=isZoomEnabled) BOOL zoomEnabled; // @synthesize zoomEnabled=_zoomEnabled;
@property(nonatomic, getter=isVisible) BOOL visible; // @synthesize visible=_visible;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setVisible:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)prepareView;

@end

