//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackDetailIAPViewController.h"

@interface AFStickerContentPackDetailIAPViewController : AFContentPackDetailIAPViewController
{
}

+ (id)countDescriptor;
+ (id)titleDescriptor;
- (void)viewDidAppear:(BOOL)arg1;
- (int)numberOfRows;
- (int)numberOfColumnsPerPage;

@end

