//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIImageView;

@interface AFStraightenHandle : UIControl
{
    UIImageView *_knobView;
    struct CGPoint _offset;
}

@property(nonatomic) struct CGPoint offset; // @synthesize offset=_offset;
@property(retain, nonatomic) UIImageView *knobView; // @synthesize knobView=_knobView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)prepareView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

