//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFOverlayView.h"

@class NSMutableArray;

@interface AFStickersOverlayView : AFOverlayView
{
    id <AFStickersOverlayViewDelegate> _delegate;
    NSMutableArray *_stickerViews;
    NSMutableArray *_stickerViewRotationInfos;
    struct CGRect _preRotationImageRect;
}

@property(nonatomic) struct CGRect preRotationImageRect; // @synthesize preRotationImageRect=_preRotationImageRect;
@property(retain, nonatomic) NSMutableArray *stickerViewRotationInfos; // @synthesize stickerViewRotationInfos=_stickerViewRotationInfos;
@property(retain, nonatomic) NSMutableArray *stickerViews; // @synthesize stickerViews=_stickerViews;
@property(nonatomic) __weak id <AFStickersOverlayViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reportStickerDeleted:(id)arg1;
- (void)stickerViewBecameActive:(id)arg1;
- (void)closeButtonPressed:(id)arg1;
- (void)removeAllStickers;
- (void)removeStickerView:(id)arg1;
- (void)addStickerView:(id)arg1;
- (void)addNewStickerView:(id)arg1;
- (void)updateActiveSticker;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (id)rotationInfoForStickerView:(id)arg1 imageRect:(struct CGRect)arg2;
- (void)prepareView;

@end

