//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFContentPackDownloadSelectionViewCell.h"

@class UIImageView;

@interface AFStickerContentPackListSelectionViewCell : AFContentPackDownloadSelectionViewCell
{
    UIImageView *_packView;
}

@property(retain, nonatomic) UIImageView *packView; // @synthesize packView=_packView;
- (void).cxx_destruct;
- (void)setContentPackItem:(id)arg1;
- (void)setContentPack:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

