//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@interface AFTableView : UITableView
{
    id <AFTableViewDelegate> _af_touchDelegate;
    CDUnknownBlockType _drawRectBlock;
}

@property(copy, nonatomic) CDUnknownBlockType drawRectBlock; // @synthesize drawRectBlock=_drawRectBlock;
@property(nonatomic) __weak id <AFTableViewDelegate> touchDelegate; // @synthesize touchDelegate=_af_touchDelegate;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)touchesShouldCancelInContentView:(id)arg1;

@end

