//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFView.h"

@interface AFTextFieldCursorView : AFView
{
    float _scale;
    struct CGRect _cursorBounds;
}

@property(nonatomic) float scale; // @synthesize scale=_scale;
@property(nonatomic) struct CGRect cursorBounds; // @synthesize cursorBounds=_cursorBounds;
- (void)setBlinkEnabled:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)prepareView;

@end

