//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFScalableViewHandle.h"

@class UILongPressGestureRecognizer;

@interface AFTextViewHandle : AFScalableViewHandle
{
    UILongPressGestureRecognizer *_longPressRecognizer;
}

@property(retain, nonatomic) UILongPressGestureRecognizer *longPressRecognizer; // @synthesize longPressRecognizer=_longPressRecognizer;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)handleTouched:(id)arg1;
- (void)registerTextViewRecognizer:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)prepareView;

@end

