//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFTextOverlayView;

@protocol AFTextOverlayViewDelegate <NSObject>
- (struct CGRect)rectForImageInTextOverlayView:(AFTextOverlayView *)arg1;
- (void)textOverlayViewDidEndEditing:(AFTextOverlayView *)arg1;
- (void)textOverlayViewDidBeginEditing:(AFTextOverlayView *)arg1;
@end

