//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFProcessor.h"

@class NSString, UIColor, UIFont;

@interface AFTextProcessor : AFProcessor
{
    NSString *_text;
    UIColor *_foregroundColor;
    UIColor *_backgroundColor;
    UIFont *_font;
    float _scale;
    float _rotation;
    struct CGRect _rect;
}

@property(nonatomic) float rotation; // @synthesize rotation=_rotation;
@property(nonatomic) float scale; // @synthesize scale=_scale;
@property(nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) UIColor *foregroundColor; // @synthesize foregroundColor=_foregroundColor;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (CDUnknownBlockType)moaBitmapBlock;
- (CDUnknownBlockType)bitmapBlock;

@end

