//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFOverlayView.h"

@class UIView<AFTiltShiftOverlayProtocol>;

@interface AFTiltShiftOverlayView : AFOverlayView
{
    int _tiltShiftStyle;
    float _rotation;
    float _radius;
    id <AFTiltShiftOverlayViewDelegate> _delegate;
    UIView<AFTiltShiftOverlayProtocol> *_helperView;
    unsigned int _helperViewRenderbuffer;
    struct CGPoint _tiltShiftCenter;
}

@property(nonatomic) unsigned int helperViewRenderbuffer; // @synthesize helperViewRenderbuffer=_helperViewRenderbuffer;
@property(retain, nonatomic) UIView<AFTiltShiftOverlayProtocol> *helperView; // @synthesize helperView=_helperView;
@property(nonatomic) __weak id <AFTiltShiftOverlayViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) float radius; // @synthesize radius=_radius;
@property(nonatomic) float rotation; // @synthesize rotation=_rotation;
@property(nonatomic) struct CGPoint tiltShiftCenter; // @synthesize tiltShiftCenter=_tiltShiftCenter;
@property(nonatomic) int tiltShiftStyle; // @synthesize tiltShiftStyle=_tiltShiftStyle;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)updateGuide;
- (void)setGuideAlpha:(float)arg1;
- (void)prepareView;

@end

