//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHorizontalTableViewCell.h"

@class UIImageView, UILabel;

@interface AFToolSelectionViewCell : AFHorizontalTableViewCell
{
    BOOL _shouldDisplayBadge;
    UILabel *_label;
    UIImageView *_iconView;
    UIImageView *_badgeView;
}

@property(retain, nonatomic) UIImageView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) BOOL shouldDisplayBadge; // @synthesize shouldDisplayBadge=_shouldDisplayBadge;
- (void).cxx_destruct;
- (void)setHighlighedIcon:(id)arg1;
- (void)setIcon:(id)arg1;
- (void)setToolName:(id)arg1;
- (void)animateBadge;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)arg1;

@end

