//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFViewController.h"

#import "AFModuleRendering.h"
#import "AFScrollingImageViewDelegate.h"
#import "UIAlertViewDelegate.h"

@class AFHUDView, AFImageServer, AFModule, AFOpenGLInstance, AFProgressHUDView, AFScrollingImageView, AFStyleSheet, AFView, NSDate, NSDictionary, NSString, NSTimer, UIAlertView, UIBarButtonItem, UIImage, UINavigationBar;

@interface AFToolViewController : AFViewController <UIAlertViewDelegate, AFScrollingImageViewDelegate, AFModuleRendering>
{
    BOOL _rotating;
    BOOL _zoomEnabled;
    BOOL _readyToApply;
    BOOL _successfullyApplied;
    BOOL _shouldWaitForGLCommit;
    BOOL _willHandleImageViewResizing;
    BOOL _bordersEnabled;
    BOOL _backButtonPressed;
    BOOL _quickLaunch;
    UIImage *_inputImage;
    UIImage *_outputImage;
    AFModule *_outputModule;
    id <AFToolViewControllerDelegate> _delegate;
    UINavigationBar *_navigationBar;
    AFScrollingImageView *_scrollableImageView;
    AFView *_staticOverlayView;
    AFView *_scrollableOverlayView;
    float _targetViewHeight;
    AFImageServer *_lowResolutionServer;
    AFImageServer *_highResolutionServer;
    NSDictionary *_settings;
    UIBarButtonItem *_applyButton;
    UIBarButtonItem *_backButton;
    UIBarButtonItem *_restoreButton;
    unsigned int _applyType;
    NSString *_analyticsKey;
    AFProgressHUDView *_progressHUDView;
    float _lowResScaleFactor;
    AFStyleSheet *_stylesheet;
    AFOpenGLInstance *_glInstance;
    UIBarButtonItem *_editButton;
    AFHUDView *_hudView;
    NSTimer *_hudTimer;
    NSDate *_renderStartDate;
    NSDate *_renderEndDate;
    UIAlertView *_quickLaunchAlertView;
    struct CGRect _overlayRect;
}

+ (id)editButtonConfirmationPrompt;
+ (id)customizationKeyPath;
+ (BOOL)needsLayoutOnFailure;
+ (BOOL)needsLayoutOnSuccess;
+ (BOOL)usesStaticImageView;
+ (Class)staticOverlayViewClass;
+ (Class)scrollableOverlayViewClass;
@property(retain, nonatomic) UIAlertView *quickLaunchAlertView; // @synthesize quickLaunchAlertView=_quickLaunchAlertView;
@property(nonatomic, getter=isQuickLaunch) BOOL quickLaunch; // @synthesize quickLaunch=_quickLaunch;
@property(retain, nonatomic) NSDate *renderEndDate; // @synthesize renderEndDate=_renderEndDate;
@property(retain, nonatomic) NSDate *renderStartDate; // @synthesize renderStartDate=_renderStartDate;
@property(retain, nonatomic) NSTimer *hudTimer; // @synthesize hudTimer=_hudTimer;
@property(nonatomic) __weak AFHUDView *hudView; // @synthesize hudView=_hudView;
@property(nonatomic) BOOL backButtonPressed; // @synthesize backButtonPressed=_backButtonPressed;
@property(retain, nonatomic) UIBarButtonItem *editButton; // @synthesize editButton=_editButton;
@property(nonatomic) __weak AFOpenGLInstance *glInstance; // @synthesize glInstance=_glInstance;
@property(nonatomic) BOOL bordersEnabled; // @synthesize bordersEnabled=_bordersEnabled;
@property(retain, nonatomic) AFStyleSheet *stylesheet; // @synthesize stylesheet=_stylesheet;
@property(nonatomic) BOOL willHandleImageViewResizing; // @synthesize willHandleImageViewResizing=_willHandleImageViewResizing;
@property(nonatomic) BOOL shouldWaitForGLCommit; // @synthesize shouldWaitForGLCommit=_shouldWaitForGLCommit;
@property(nonatomic) BOOL successfullyApplied; // @synthesize successfullyApplied=_successfullyApplied;
@property(nonatomic) float lowResScaleFactor; // @synthesize lowResScaleFactor=_lowResScaleFactor;
@property(retain, nonatomic) AFProgressHUDView *progressHUDView; // @synthesize progressHUDView=_progressHUDView;
@property(copy, nonatomic) NSString *analyticsKey; // @synthesize analyticsKey=_analyticsKey;
@property(nonatomic) struct CGRect overlayRect; // @synthesize overlayRect=_overlayRect;
@property(nonatomic) unsigned int applyType; // @synthesize applyType=_applyType;
@property(nonatomic, getter=isReadyToApply) BOOL readyToApply; // @synthesize readyToApply=_readyToApply;
@property(retain, nonatomic) UIBarButtonItem *restoreButton; // @synthesize restoreButton=_restoreButton;
@property(retain, nonatomic) UIBarButtonItem *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UIBarButtonItem *applyButton; // @synthesize applyButton=_applyButton;
@property(retain, nonatomic) NSDictionary *settings; // @synthesize settings=_settings;
@property(retain, nonatomic) AFImageServer *highResolutionServer; // @synthesize highResolutionServer=_highResolutionServer;
@property(retain, nonatomic) AFImageServer *lowResolutionServer; // @synthesize lowResolutionServer=_lowResolutionServer;
@property(nonatomic, getter=isZoomEnabled) BOOL zoomEnabled; // @synthesize zoomEnabled=_zoomEnabled;
@property(nonatomic, getter=isRotating) BOOL rotating; // @synthesize rotating=_rotating;
@property(nonatomic) float targetViewHeight; // @synthesize targetViewHeight=_targetViewHeight;
@property(retain, nonatomic) AFView *scrollableOverlayView; // @synthesize scrollableOverlayView=_scrollableOverlayView;
@property(retain, nonatomic) AFView *staticOverlayView; // @synthesize staticOverlayView=_staticOverlayView;
@property(nonatomic) __weak AFScrollingImageView *scrollableImageView; // @synthesize scrollableImageView=_scrollableImageView;
@property(nonatomic) __weak UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(nonatomic) __weak id <AFToolViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AFModule *outputModule; // @synthesize outputModule=_outputModule;
@property(retain, nonatomic) UIImage *outputImage; // @synthesize outputImage=_outputImage;
@property(retain, nonatomic) UIImage *inputImage; // @synthesize inputImage=_inputImage;
- (void).cxx_destruct;
- (void)setTopBarButtonsEnabled:(BOOL)arg1;
- (id)createRestoreButton;
- (id)createApplyButtonQuickLaunched:(BOOL)arg1;
- (id)createBackButtonQuickLaunched:(BOOL)arg1;
- (void)createNavButtons;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)reportApplied;
- (void)reportApplied:(id)arg1;
- (void)reportAppliedWithRenderTime:(double)arg1 attributes:(id)arg2;
- (void)reportCancelled;
- (void)reportOpened;
- (void)reportEvent:(id)arg1;
- (void)reportEvent:(id)arg1 attributes:(id)arg2;
@property(readonly, nonatomic) double renderTime; // @dynamic renderTime;
- (void)setRenderEndDate;
- (void)setRenderStartDate;
- (void)showCurrent;
- (void)showOriginal;
- (BOOL)supportsViewOriginalWithTouch;
- (void)renderModule:(id)arg1 atResolution:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateUIAndNotifyDelegateOfFinish;
- (void)finishApplying;
- (void)hideHUDView;
- (void)displayHUDView:(id)arg1 hideAutomatically:(BOOL)arg2;
- (void)restoreButtonPressed:(id)arg1;
- (BOOL)editButttonShouldPrompt;
- (void)editButtonPressed:(id)arg1;
- (void)applyButtonPressed:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)imageViewDidZoom:(id)arg1;
- (void)imageViewStoppedDragging:(id)arg1;
- (void)imageViewBeganDragging:(id)arg1;
- (void)imageViewStoppedZooming:(id)arg1;
- (void)imageViewBeganZooming:(id)arg1;
@property(readonly, nonatomic) float lowResScale; // @dynamic lowResScale;
@property(readonly, nonatomic) float zoomScale; // @dynamic zoomScale;
@property(readonly, nonatomic) struct CGAffineTransform imageViewTransform; // @dynamic imageViewTransform;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithGLInstance:(id)arg1 settings:(id)arg2 quickLaunch:(BOOL)arg3;
- (id)initWithGLInstance:(id)arg1;
- (id)customizationBackgroundColor;
- (id)customizationAccentColor;
- (id)customizationOptionForKey:(id)arg1;

@end

