//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AFHorizontalTableView, NSArray;

@interface AFToolSelectionView : AFView <UITableViewDataSource, UITableViewDelegate>
{
    BOOL _shouldShowFeedback;
    BOOL _animateBadge;
    id <AFToolSelectionViewDelegate> _delegate;
    NSArray *_tools;
    AFHorizontalTableView *_horizontalTableView;
}

@property(nonatomic, getter=shouldAnimateBadge) BOOL animateBadge; // @synthesize animateBadge=_animateBadge;
@property(retain, nonatomic) AFHorizontalTableView *horizontalTableView; // @synthesize horizontalTableView=_horizontalTableView;
@property(nonatomic) BOOL shouldShowFeedback; // @synthesize shouldShowFeedback=_shouldShowFeedback;
@property(retain, nonatomic) NSArray *tools; // @synthesize tools=_tools;
@property(nonatomic) __weak id <AFToolSelectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)reloadDataAnimated:(BOOL)arg1;
- (void)prepareView;

@end

