//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFManagedObject.h"

@class NSSet, NSString;

@interface AFTranslationKey : AFManagedObject
{
}

+ (id)uniqueKeyAttribute;
+ (id)entityName;

// Remaining properties
@property(retain, nonatomic) NSSet *translations; // @dynamic translations;
@property(retain, nonatomic) NSString *value; // @dynamic value;

@end

