//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ARCoordinate.h"

@class CLLocation;

@interface ARGeoCoordinate : ARCoordinate
{
    CLLocation *geoLocation;
}

+ (id)coordinateWithLocation:(id)arg1 fromOrigin:(id)arg2;
+ (id)coordinateWithLocation:(id)arg1;
@property(retain, nonatomic) CLLocation *geoLocation; // @synthesize geoLocation;
- (void)calibrateUsingOrigin:(id)arg1;
- (float)angleFromCoordinate:(CDStruct_2c43369c)arg1 toCoordinate:(CDStruct_2c43369c)arg2;

@end

