//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ATMHud;

@protocol ATMHudDelegate

@optional
- (void)hudDidDisappear:(ATMHud *)arg1;
- (void)hudWillDisappear:(ATMHud *)arg1;
- (void)hudDidUpdate:(ATMHud *)arg1;
- (void)hudWillUpdate:(ATMHud *)arg1;
- (void)hudDidAppear:(ATMHud *)arg1;
- (void)hudWillAppear:(ATMHud *)arg1;
- (void)userDidTapHud:(ATMHud *)arg1;
@end

