//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface ATMHudQueueItem : NSObject
{
    NSString *caption;
    UIImage *image;
    BOOL showActivity;
    int accessoryPosition;
    int activityStyle;
}

@property(nonatomic) int activityStyle; // @synthesize activityStyle;
@property(nonatomic) int accessoryPosition; // @synthesize accessoryPosition;
@property(nonatomic) BOOL showActivity; // @synthesize showActivity;
@property(retain, nonatomic) UIImage *image; // @synthesize image;
@property(retain, nonatomic) NSString *caption; // @synthesize caption;
- (void)dealloc;
- (id)init;

@end

