//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class ATMHudView, ATMSoundFX, NSMutableArray, NSString;

@interface ATMHud : UIViewController
{
    float margin;
    float padding;
    float alpha;
    float appearScaleFactor;
    float disappearScaleFactor;
    float progressBorderRadius;
    float progressBorderWidth;
    float progressBarRadius;
    float progressBarInset;
    struct CGPoint center;
    BOOL shadowEnabled;
    BOOL blockTouches;
    BOOL allowSuperviewInteraction;
    NSString *showSound;
    NSString *updateSound;
    NSString *hideSound;
    id <ATMHudDelegate> delegate;
    int accessoryPosition;
    ATMHudView *__view;
    ATMSoundFX *sound;
    NSMutableArray *displayQueue;
    int queuePosition;
}

+ (id)buildInfo;
@property(nonatomic) int queuePosition; // @synthesize queuePosition;
@property(retain, nonatomic) NSMutableArray *displayQueue; // @synthesize displayQueue;
@property(retain, nonatomic) ATMSoundFX *sound; // @synthesize sound;
@property(retain, nonatomic) ATMHudView *__view; // @synthesize __view;
@property(retain, nonatomic) NSString *hideSound; // @synthesize hideSound;
@property(retain, nonatomic) NSString *updateSound; // @synthesize updateSound;
@property(retain, nonatomic) NSString *showSound; // @synthesize showSound;
@property(nonatomic) BOOL allowSuperviewInteraction; // @synthesize allowSuperviewInteraction;
@property(nonatomic) BOOL blockTouches; // @synthesize blockTouches;
@property(nonatomic) BOOL shadowEnabled; // @synthesize shadowEnabled;
@property(nonatomic) struct CGPoint center; // @synthesize center;
@property(nonatomic) int accessoryPosition; // @synthesize accessoryPosition;
@property(nonatomic) id <ATMHudDelegate> delegate; // @synthesize delegate;
@property(nonatomic) float progressBarInset; // @synthesize progressBarInset;
@property(nonatomic) float progressBarRadius; // @synthesize progressBarRadius;
@property(nonatomic) float progressBorderWidth; // @synthesize progressBorderWidth;
@property(nonatomic) float progressBorderRadius; // @synthesize progressBorderRadius;
@property(nonatomic) float disappearScaleFactor; // @synthesize disappearScaleFactor;
@property(nonatomic) float appearScaleFactor; // @synthesize appearScaleFactor;
@property(nonatomic) float alpha; // @synthesize alpha;
@property(nonatomic) float padding; // @synthesize padding;
@property(nonatomic) float margin; // @synthesize margin;
- (void)playSound:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)construct;
- (void)hideAfter:(double)arg1;
- (void)hide;
- (void)update;
- (void)show;
- (void)showQueueAtIndex:(int)arg1;
- (void)showNextInQueue;
- (void)startQueue;
- (void)clearQueue;
- (void)addQueueItems:(id)arg1;
- (void)addQueueItem:(id)arg1;
- (void)setProgress:(float)arg1;
- (void)setFixedSize:(struct CGSize)arg1;
- (void)setActivityStyle:(int)arg1;
- (void)setActivity:(BOOL)arg1;
- (void)setImage:(id)arg1;
- (void)setCaption:(id)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithDelegate:(id)arg1;
- (id)init;

@end

