//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface ATMProgressLayer : CALayer
{
    float theProgress;
    float progressBorderWidth;
    float progressBorderRadius;
    float progressBarRadius;
    float progressBarInset;
}

@property(nonatomic) float progressBarInset; // @synthesize progressBarInset;
@property(nonatomic) float progressBarRadius; // @synthesize progressBarRadius;
@property(nonatomic) float progressBorderRadius; // @synthesize progressBorderRadius;
@property(nonatomic) float progressBorderWidth; // @synthesize progressBorderWidth;
@property(nonatomic) float theProgress; // @synthesize theProgress;
- (void)drawInContext:(struct CGContext *)arg1;

@end

