//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class NSString;

@interface ATMTextLayer : CALayer
{
    NSString *caption;
}

+ (BOOL)needsDisplayForKey:(id)arg1;
@property(retain, nonatomic) NSString *caption; // @synthesize caption;
- (void)dealloc;
- (void)drawInContext:(struct CGContext *)arg1;
- (id)initWithLayer:(id)arg1;

@end

