//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSNumber, NSString;

@interface BWApp : NSObject
{
    NSString *name_;
    NSString *version_;
    NSString *shortVersion_;
    NSString *notes_;
    NSDate *date_;
    NSNumber *size_;
    NSNumber *mandatory_;
}

+ (id)appFromDict:(id)arg1;
@property(copy, nonatomic) NSNumber *mandatory; // @synthesize mandatory=mandatory_;
@property(copy, nonatomic) NSNumber *size; // @synthesize size=size_;
@property(copy, nonatomic) NSDate *date; // @synthesize date=date_;
@property(copy, nonatomic) NSString *notes; // @synthesize notes=notes_;
@property(copy, nonatomic) NSString *shortVersion; // @synthesize shortVersion=shortVersion_;
@property(copy, nonatomic) NSString *version; // @synthesize version=version_;
@property(copy, nonatomic) NSString *name; // @synthesize name=name_;
- (BOOL)isValid;
- (id)notesOrEmptyString;
- (void)setDateWithTimestamp:(double)arg1;
- (id)sizeInMB;
- (id)dateString;
- (id)versionString;
- (id)nameAndVersionString;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (BOOL)isEqualToBWApp:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;

@end

