//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FleksyAPIManager;

@interface FLDictionaryManager : NSObject
{
    FleksyAPIManager *_apiManager;
}

+ (id)sharedManager;
@property(nonatomic) FleksyAPIManager *apiManager; // @synthesize apiManager=_apiManager;
- (id)stripPrefix:(id)arg1 fromKey:(id)arg2;
- (BOOL)removeWord:(id)arg1;
- (BOOL)importWord:(id)arg1;
- (void)removeDeletedFLWords:(id)arg1 FromDataStore:(id)arg2;
- (void)dictionaryModifiedWithWord:(id)arg1 learned:(BOOL)arg2;

@end

