//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@interface FleksyEditMenuManager : NSObject <UIAlertViewDelegate>
{
    BOOL isKeyboardShowing;
}

+ (void)askUpdateFleksyWithDelegateToBeSpecified;
+ (void)askInstallFleksyWithDelegateToBeSpecified;
+ (id)sharedManager;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)askUpdateFleksyWithDelegateToBeSpecified;
- (void)askInstallFleksyWithDelegateToBeSpecified;
- (void)forceShowEditMenu:(id)arg1;
- (void)removeFleksyFromEditMenu;
- (void)installFleksyInEditMenu:(BOOL)arg1;
- (void)installFleksyInEditMenu;
- (id)fleksyMenuItem:(BOOL)arg1;
- (id)nonFleksyEditMenuItems;
- (BOOL)isFleksyMenuItem:(id)arg1;
- (void)applicationDidBecomeActive;
- (void)didHideKeyboard;
- (void)didShowKeyboard;
- (id)init;
- (BOOL)includesFleksyMenuItem;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

