//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FSKeyboard, FleksyPasteboardManager, TwoConditionObserver;

@interface FleksyKeyboard : NSObject
{
    FSKeyboard *kb;
    FleksyPasteboardManager *pasteboardManager;
    TwoConditionObserver *twoConditionObserver;
    BOOL isSettingsPushForServerSync;
}

+ (void)stopSpeakingInternal;
+ (void)stopSpeaking;
+ (void)speakCurrentTextInternal:(id)arg1;
+ (void)speakCurrentText:(id)arg1;
+ (id)getLastAppSwitchVersionForLanguage:(id)arg1;
+ (id)getLastAppSwitchVersionKeyForLanguage:(id)arg1;
+ (id)sdkVersion;
+ (void)_install;
+ (id)fleksyRelatedURLSchemes;
+ (void)checkLoadedStatus;
+ (BOOL)isFleksyLoaded;
+ (void)install;
+ (void)resetFleksy;
+ (void)unloadFleksy;
+ (void)_loadFleksy;
+ (void)loadFleksy;
+ (void)saveFleksyEnabledState:(BOOL)arg1 loaded:(BOOL)arg2;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)dealloc;
- (void)showDeleteLanguagePackAlert;
- (void)setSpacebarRowVisibility:(BOOL)arg1;
- (void)setKeyboardInvisible:(BOOL)arg1;
- (void)setIsReceivingDataInternal:(BOOL)arg1;
- (void)setIsReceivingData:(BOOL)arg1;
- (void)setVoiceFeedback:(BOOL)arg1;
- (void)setFastDelete:(BOOL)arg1;
- (void)setUserAutoCorrection:(BOOL)arg1;
- (BOOL)needToPerformResourceAppSwitchForLanguage:(id)arg1;
- (void)performAppSwitchForLanguageResource:(id)arg1;
- (void)didFailResourceDownload:(id)arg1;
- (void)didPerformAppSwitchForLanguageResource;
- (id)sdkVersion;
- (void)voiceOverStatusChanged;
- (void)applySettingNamed:(id)arg1 loadingLanguage:(BOOL)arg2;
- (void)applySettingNamed:(id)arg1;
- (void)configureKeyboardVisibilitySetting;
- (void)changedSetting:(id)arg1;
- (void)applyAllSettingsAfterLanguagePackLoaded;
- (void)applyAllSettings;
- (void)pullSettings;
- (void)setLanguagePack:(id)arg1;
- (void)loadUserDictionary;
- (void)applicationWillResignActive:(id)arg1;
- (void)loadKeyboard:(BOOL)arg1;
- (id)init;

@end

