//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FleksyAPIManager : NSObject
{
    struct FleksyAPI *_api;
    struct FleksyListenerImplC *_apiListener;
    BOOL _resourceLoaded;
    BOOL _performingBatchEdit;
    BOOL _pendingSessionRestart;
    BOOL _lastReplaceFailed;
    NSString *_loadedLanguage;
    id <FleksyAPIManagerDelegate> _fsClient;
}

@property(nonatomic) __weak id <FleksyAPIManagerDelegate> fsClient; // @synthesize fsClient=_fsClient;
- (void).cxx_destruct;
- (void)_onEndBatchEdit;
- (void)_onBeginBatchEdit;
- (void)_sendToClientReplaceComposingText:(const struct FLUnicodeString *)arg1;
- (int)getFieldAction;
- (BOOL)isShifted;
- (int)getActiveKeyboardID;
- (int)getCapitalizationMode;
- (map_b5835894)getKeymapForKeyboard:(int)arg1 withAccents:(BOOL)arg2;
- (map_b5835894)getKeymapForKeyboard:(int)arg1;
- (struct FLUnicodeString)getNearestCharForPoint:(struct CGPoint)arg1 forKeyboard:(int)arg2;
- (struct FleksyAPIpImpl *)getPrivateApi;
- (struct FleksyAPI *)getApi;
- (id)getSdkVersion;
- (void)toggleShift;
- (void)longPress:(int)arg1;
- (void)enter:(float)arg1;
- (void)enter;
- (void)nextSuggestion;
- (void)previousSuggestion;
- (void)backspace:(float)arg1;
- (void)space:(float)arg1;
- (void)sendTapPont:(struct CGPoint)arg1;
- (void)_cursorSelectionFrom:(int)arg1 to:(int)arg2;
- (void)selectionDidChange:(BOOL)arg1 forRange:(struct _NSRange)arg2;
- (int)removeWordFromDictionary:(id)arg1;
- (int)addWordToDictionary:(id)arg1;
- (void)endTypingSession;
- (void)_startTypingSession:(BOOL)arg1;
- (void)startTypingSession:(BOOL)arg1;
- (void)setBlindMode:(BOOL)arg1;
- (void)setSpaceBreaksEnabled:(BOOL)arg1;
- (void)setPunctuationSpaceMode:(int)arg1;
- (void)setDeleteMode:(int)arg1;
- (void)setCorrectionMode:(int)arg1;
- (void)setTextFieldType:(int)arg1;
- (void)setFieldAction:(int)arg1;
- (void)setCapitalizationMode:(int)arg1;
- (void)setPlatformKeyboardSize:(struct CGSize)arg1;
- (void)setActiveKeyboard:(int)arg1;
- (void)setFleksyVoiceFeedback:(BOOL)arg1;
- (void)setFleksyUserAutoCorrection:(BOOL)arg1;
- (void)_initEngine;
- (void)_deallocEngine;
- (void)_reloadResources:(id)arg1;
- (BOOL)doesWordExists:(id)arg1;
- (BOOL)hasResourceLoaded;
- (void)_loadAPIResourceFile:(id)arg1;
- (void)loadAPIForLanguage:(id)arg1 withResourceFile:(id)arg2;
- (void)dealloc;
- (id)initWithClient:(id)arg1;

@end

