//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<FleksyResponderDelegate>, NSString, UIResponder<UITextInput>, UIView;

@interface FleksyResponder : NSObject
{
    UIView *_view;
    UIResponder<UITextInput> *_responder;
    BOOL expectingTextChange;
    BOOL expectingSelectionChange;
    NSObject<FleksyResponderDelegate> *_responderDelegate;
}

@property __weak NSObject<FleksyResponderDelegate> *responderDelegate; // @synthesize responderDelegate=_responderDelegate;
- (void).cxx_destruct;
@property(readonly) BOOL hasResponder;
- (id)keyboardResponderForResponder:(id)arg1;
@property(readonly, nonatomic) UIResponder<UITextInput> *responder;
- (void)dealloc;
- (void)tearDown;
@property(readonly) struct _NSRange selectedRange;
@property(readonly, nonatomic) NSString *text;
- (id)fullRange;
- (id)textInRange:(struct _NSRange)arg1;
- (id)selectionRectsForRange:(struct _NSRange)arg1;
- (BOOL)_replaceRange:(struct _NSRange)arg1 withText:(id)arg2;
- (BOOL)replaceRange:(struct _NSRange)arg1 withText:(id)arg2;
- (void)sendReturnKey;
- (struct _NSRange)rangeFromTextRange:(id)arg1;
- (id)textRangeFromRange:(struct _NSRange)arg1;
- (void)textDidChange;
- (void)selectionDidChange;
- (void)configureNewResponder:(id)arg1;
- (void)_cleanupPreviousResponder:(id)arg1;
- (void)cleanupPreviousResponder:(id)arg1;
- (void)removeCustomInputViewMethodFromResponder:(id)arg1;
- (void)addCustomInputViewMethodToResponder:(id)arg1;
- (void)_changeFleksyResponder:(id)arg1;
- (void)changeFleksyResponder:(id)arg1;
- (void)searchForInitialResponder;
- (id)initWithFleksyResponderDelegate:(id)arg1 forView:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

