//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FSIPadLayerCommonControlFlow.h"

@protocol FSIControlPadControlFlow <FSIPadLayerCommonControlFlow>
- (void)buildControlPadWithBounds:(struct CGRect)arg1;
- (void)setEnableReturnKey:(BOOL)arg1;
- (void)configureEnablesReturnKeyAutomatically:(BOOL)arg1;
- (void)configureEnterKeyFieldAction:(int)arg1;
@end

