//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface FSIControlPadView : UIView
{
    id <FSIControlPadControlFlow> _controller;
}

@property(nonatomic) id <FSIControlPadControlFlow> controller; // @synthesize controller=_controller;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

