//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSMutableSet, UIColor;

@interface FSIControlKey : UIButton
{
    UIColor *normalColor;
    float _scaleFactor;
    NSMutableSet *currentTouches;
    BOOL _firing;
    id <FSIControlKeyProtocol> _delegate;
}

@property(nonatomic) BOOL firing; // @synthesize firing=_firing;
@property(nonatomic) id <FSIControlKeyProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)normalBackgroundColor;
- (void)highlightedBackgroundColor;
- (void)resetBackgroundColor:(id)arg1;
- (void)setImage:(id)arg1 forState:(unsigned int)arg2 scaleFactor:(float)arg3;
- (void)setImage:(id)arg1 forState:(unsigned int)arg2;
- (id)initWithFrame:(struct CGRect)arg1 withImage:(id)arg2 withBackgroundColor:(id)arg3 scaleFactor:(float)arg4;

@end

