//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FSIControlKey.h"

@interface FSIEnterKey : FSIControlKey
{
    BOOL _enabledByController;
    BOOL _enablesReturnKeyAutomatically;
}

@property(nonatomic, getter=isEnablesReturnKeyAutomatically) BOOL enablesReturnKeyAutomatically; // @synthesize enablesReturnKeyAutomatically=_enablesReturnKeyAutomatically;
@property(nonatomic, getter=isEnabledByController) BOOL enabledByController; // @synthesize enabledByController=_enabledByController;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

@end

