//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FSIPadLayerCommonControlFlow.h"

@class NSArray;

@protocol FSIKeyPadControlFlow <FSIPadLayerCommonControlFlow>

@optional
- (void)forwardSelectSuggestionWithIndex:(int)arg1;
- (void)forwardShowSuggestions:(NSArray *)arg1 selectedIndex:(int)arg2;
- (void)keyMapIsReady:(NSArray *)arg1 keyPadSize:(struct CGSize)arg2 maxRows:(int)arg3 keyboardID:(int)arg4;
@end

