//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "FSIKeyPadControlFlow.h"

@class FLSuggestionsView, FSIKeyPadView;

@interface FSIKeyPadController : UIViewController <FSIKeyPadControlFlow>
{
    FSIKeyPadView *keyPadView;
    FLSuggestionsView *_suggestionsView;
    int keyboardState;
    int keyboardID;
    int _currentIndex;
}

@property(nonatomic) int currentIndex; // @synthesize currentIndex=_currentIndex;
@property(readonly) FLSuggestionsView *suggestionsView; // @synthesize suggestionsView=_suggestionsView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)forwardSelectSuggestionWithIndex:(int)arg1;
- (void)forwardShowSuggestions:(id)arg1 selectedIndex:(int)arg2;
- (int)getKeyboardState;
- (void)keyMapWithID:(int)arg1;
- (void)keyMapIsInState:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1 keyboard:(id)arg2;

@end

