//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FSIControlFlow.h"

@class UITouch;

@protocol FSIMasterGestureHandlerListener <FSIControlFlow>
- (void)hoverStopped;
- (void)hoverStarted;
- (void)previousKeyboardLayoutOrPerformFunction;
- (void)nextKeyboardLayoutOrPerformFunction;
- (void)previousKeyboardID;
- (void)nextKeyboardID;
- (void)sendPreviousSuggestion;
- (void)sendNextSuggestion;
- (void)sendButtonTappedWithPoint:(struct CGPoint)arg1;
- (void)sendButtonTappedWithTouch:(UITouch *)arg1;
@end

