//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class FSIKeyboardController, NSMutableArray, NSMutableDictionary, UITouch, UIView;

@interface FSIMasterGestureHandler : NSObject <UIGestureRecognizerDelegate>
{
    BOOL hoverMode;
    UITouch *lastTouchDown;
    double lastTouchUpTime;
    struct FLUnicodeString lastChar;
    struct FLUnicodeString pendingChar;
    BOOL clearTouches;
    NSMutableArray *_currentTouches;
    NSMutableDictionary *swipeAnalyzers;
    UIView *_listenerView;
    id <FSIMasterGestureHandlerListener> _listener;
    FSIKeyboardController *_keyboardController;
}

@property(nonatomic) __weak FSIKeyboardController *keyboardController; // @synthesize keyboardController=_keyboardController;
@property(nonatomic) id <FSIMasterGestureHandlerListener> listener; // @synthesize listener=_listener;
@property(nonatomic) UIView *listenerView; // @synthesize listenerView=_listenerView;
@property(readonly) BOOL hoverMode; // @synthesize hoverMode;
@property(readonly) struct FLUnicodeString lastChar; // @synthesize lastChar;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)setState:(int)arg1;
- (void)twoFingerAction:(id)arg1 fromSelector:(SEL)arg2 withSelector:(SEL)arg3;
- (void)twoFingerSwipeRight:(id)arg1;
- (void)twoFingerSwipeLeft:(id)arg1;
- (void)twoFingerSwipeDown:(id)arg1;
- (void)twoFingerSwipeUp:(id)arg1;
- (void)setNewChar:(id)arg1;
- (void)stopHover;
- (void)updateHoverChar:(id)arg1;
- (void)startHover;
- (void)_handleLongPressFrom:(id)arg1;
- (void)handleLongPressFrom:(id)arg1;
- (void)handleSwipeDirection:(unsigned int)arg1 fromTouch:(id)arg2 caller:(id)arg3;
- (void)handleSwipe:(id)arg1;
- (void)handleSwipeAndHold:(id)arg1;
- (BOOL)handleTouch:(id)arg1 forced:(BOOL)arg2;
- (void)stopTrackingTouch:(id)arg1 forced:(BOOL)arg2;
- (unsigned int)getDirectionForTouch:(id)arg1;
- (void)forceTouchesBeforeTouch:(id)arg1;
- (void)consumeTouch:(id)arg1;
- (void)playTockForTouch:(id)arg1;
- (void)queueTap:(id)arg1;
- (void)touchStatus:(id)arg1;
- (void)removePendingTouches;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)clearTouches;
- (void)handleKeyboardDidDisable:(id)arg1;
- (id)initWithListener:(id)arg1 withView:(id)arg2 keyboardController:(id)arg3;

@end

