//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

#import "UIActionSheetDelegate.h"

@interface IFTweetButton : UIButton <UIActionSheetDelegate>
{
    BOOL _cancelTouches;
    id root;
}

@property(retain, nonatomic) id root; // @synthesize root;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)cancelTapNHold;
- (void)tapNHoldFired;

@end

