//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@interface IMTWebView : UIWebView
{
    id <IMTWebViewProgressDelegate> progressDelegate;
    int resourceCount;
    int resourceCompletedCount;
}

@property(nonatomic) int resourceCompletedCount; // @synthesize resourceCompletedCount;
@property(nonatomic) int resourceCount; // @synthesize resourceCount;
@property(nonatomic) id <IMTWebViewProgressDelegate> progressDelegate; // @synthesize progressDelegate;
- (void)webView:(id)arg1 resource:(id)arg2 didFinishLoadingFromDataSource:(id)arg3;
- (void)webView:(id)arg1 resource:(id)arg2 didFailLoadingWithError:(id)arg3 fromDataSource:(id)arg4;
- (id)webView:(id)arg1 identifierForInitialRequest:(id)arg2 fromDataSource:(id)arg3;

@end

