//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "KKPasscodeViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"

@class UISwitch;

@interface KKPasscodeSettingsViewController : UITableViewController <UIActionSheetDelegate, KKPasscodeViewControllerDelegate>
{
    id <KKPasscodeSettingsViewControllerDelegate> _delegate;
    UISwitch *_eraseDataSwitch;
    BOOL _passcodeLockOn;
    BOOL _eraseDataOn;
}

@property(nonatomic) id <KKPasscodeSettingsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didSettingsChanged:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)eraseDataSwitchChanged:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;

@end

