//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class KKPasscodeViewController;

@protocol KKPasscodeViewControllerDelegate <NSObject>

@optional
- (void)didSettingsChanged:(KKPasscodeViewController *)arg1;
- (void)shouldEraseApplicationData:(KKPasscodeViewController *)arg1;
- (void)didPasscodeEnteredIncorrectly:(KKPasscodeViewController *)arg1;
- (void)didPasscodeEnteredCorrectly:(KKPasscodeViewController *)arg1;
@end

