//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface LevelMeter : UIView
{
    unsigned int _numLights;
    float _level;
    float _peakLevel;
    struct LevelMeterColorThreshold *_colorThresholds;
    unsigned int _numColorThresholds;
    BOOL _vertical;
    BOOL _variableLightIntensity;
    UIColor *_bgColor;
    UIColor *_borderColor;
}

@property BOOL variableLightIntensity; // @synthesize variableLightIntensity=_variableLightIntensity;
@property(retain) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(retain) UIColor *bgColor; // @synthesize bgColor=_bgColor;
@property(getter=isVertical) BOOL vertical; // @synthesize vertical=_vertical;
- (void)setColorThresholds:(struct LevelMeterColorThreshold *)arg1 count:(unsigned int)arg2;
- (struct LevelMeterColorThreshold *)colorThresholds:(unsigned int *)arg1;
@property unsigned int numLights;
@property float peakLevel;
@property float level;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_performInit;

@end

