//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIColor;

@interface MapViewButton : UIButton
{
    UIColor *arrowColor;
    BOOL noArrow;
    id parentView;
}

@property(retain, nonatomic) id parentView; // @synthesize parentView;
@property(nonatomic) BOOL noArrow; // @synthesize noArrow;
@property(retain, nonatomic) UIColor *arrowColor; // @synthesize arrowColor;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;

@end

