//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MNColorWheelViewDelegate.h"
#import "UITextFieldDelegate.h"

@class MNBrightnessView, MNColorView, MNColorWheelView, UIButton, UIColor, UITextField;

@interface MNColorPicker : UIViewController <MNColorWheelViewDelegate, UITextFieldDelegate>
{
    id <MNColorPickerDelegate> _delegate;
    MNColorView *_colorView;
    MNColorWheelView *_colorWheelView;
    MNBrightnessView *_brightnessView;
    UIColor *_color;
    BOOL _continuous;
    UIButton *copyButton;
    UIButton *pasteButton;
    UIButton *clearButton;
    UITextField *rField;
    UITextField *gField;
    UITextField *bField;
}

@property(getter=isContinuous) BOOL continuous; // @synthesize continuous=_continuous;
@property(retain) UIColor *color; // @synthesize color=_color;
@property(nonatomic) id <MNColorPickerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UITextField *bField; // @synthesize bField;
@property(retain, nonatomic) UITextField *gField; // @synthesize gField;
@property(retain, nonatomic) UITextField *rField; // @synthesize rField;
@property(retain, nonatomic) UIButton *clearButton; // @synthesize clearButton;
@property(retain, nonatomic) UIButton *pasteButton; // @synthesize pasteButton;
@property(retain, nonatomic) UIButton *copyButton; // @synthesize copyButton;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (BOOL)textFieldShouldEndEditing:(id)arg1;
- (void)updateColorPositionFromRGB;
- (void)colorWheelView:(id)arg1 didChangeColor:(id)arg2;
- (void)clearButton:(id)arg1;
- (void)didPressCancel;
- (void)didPressDone;
- (void)_layoutViewsForInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (void)pasteButton:(id)arg1;
- (void)copyButton:(id)arg1;
- (void)doneButton:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)addButtonToKeyboard;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)updateRGBFields:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

