//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIScrollViewDelegate.h"

@class MBProgressHUD, NSArray, NSMutableArray, NSMutableSet, NSTimer, UIActionSheet, UIActivityViewController, UIBarButtonItem, UIColor, UIImage, UIScrollView, UIToolbar;

@interface MWPhotoBrowser : UIViewController <UIScrollViewDelegate, UIActionSheetDelegate, MFMailComposeViewControllerDelegate>
{
    unsigned int _photoCount;
    NSMutableArray *_photos;
    NSArray *_depreciatedPhotoData;
    UIScrollView *_pagingScrollView;
    NSMutableSet *_visiblePages;
    NSMutableSet *_recycledPages;
    unsigned int _currentPageIndex;
    unsigned int _pageIndexBeforeRotation;
    UIToolbar *_toolbar;
    NSTimer *_controlVisibilityTimer;
    UIBarButtonItem *_previousButton;
    UIBarButtonItem *_nextButton;
    UIBarButtonItem *_actionButton;
    MBProgressHUD *_progressHUD;
    UIActionSheet *_actionsSheet;
    BOOL _previousNavBarHidden;
    BOOL _previousNavToolbarHidden;
    int _previousNavBarStyle;
    int _previousStatusBarStyle;
    UIColor *_previousNavBarTintColor;
    UIColor *_previousNavBarBarTintColor;
    UIBarButtonItem *_previousViewControllerBackButton;
    UIImage *_previousNavigationBarBackgroundImageDefault;
    UIImage *_previousNavigationBarBackgroundImageLandscapePhone;
    BOOL _isVCBasedStatusBarAppearance;
    BOOL _statusBarShouldBeHidden;
    BOOL _displayActionButton;
    BOOL _leaveStatusBarAlone;
    BOOL _performingLayout;
    BOOL _rotating;
    BOOL _viewIsActive;
    BOOL _didSavePreviousStateOfNavBar;
    BOOL _zoomPhotosToFill;
    BOOL _displayNavArrows;
    id <MWPhotoBrowserDelegate> _delegate;
    unsigned int _currentIndex;
    UIActivityViewController *_activityViewController;
}

@property(retain, nonatomic) UIActivityViewController *activityViewController; // @synthesize activityViewController=_activityViewController;
@property(readonly, nonatomic) unsigned int currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) BOOL displayActionButton; // @synthesize displayActionButton=_displayActionButton;
@property(nonatomic) BOOL displayNavArrows; // @synthesize displayNavArrows=_displayNavArrows;
@property(nonatomic) BOOL zoomPhotosToFill; // @synthesize zoomPhotosToFill=_zoomPhotosToFill;
@property(nonatomic) __weak id <MWPhotoBrowserDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)actuallyEmailPhoto:(id)arg1;
- (void)emailPhoto;
- (void)actuallyCopyPhoto:(id)arg1;
- (void)copyPhoto;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)actuallySavePhoto:(id)arg1;
- (void)savePhoto;
- (void)showProgressHUDCompleteMessage:(id)arg1;
- (void)hideProgressHUD:(BOOL)arg1;
- (void)showProgressHUDWithMessage:(id)arg1;
- (id)progressHUD;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)actionButtonPressed:(id)arg1;
- (void)doneButtonPressed:(id)arg1;
- (void)setCurrentPhotoIndex:(unsigned int)arg1;
- (void)setInitialPageIndex:(unsigned int)arg1;
- (void)toggleControls;
- (void)hideControls;
- (BOOL)areControlsHidden;
- (void)hideControlsAfterDelay;
- (void)cancelControlHiding;
- (int)preferredStatusBarUpdateAnimation;
- (BOOL)prefersStatusBarHidden;
- (void)setControlsHidden:(BOOL)arg1 animated:(BOOL)arg2 permanent:(BOOL)arg3;
- (void)showNextPhotoAnimated:(BOOL)arg1;
- (void)showPreviousPhotoAnimated:(BOOL)arg1;
- (void)gotoNextPage;
- (void)gotoPreviousPage;
- (void)jumpToPageAtIndex:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)updateNavigation;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (struct CGRect)frameForCaptionView:(id)arg1 atIndex:(unsigned int)arg2;
- (struct CGRect)frameForToolbarAtOrientation:(int)arg1;
- (struct CGPoint)contentOffsetForPageAtIndex:(unsigned int)arg1;
- (struct CGSize)contentSizeForPagingScrollView;
- (struct CGRect)frameForPageAtIndex:(unsigned int)arg1;
- (struct CGRect)frameForPagingScrollView;
- (void)didStartViewingPageAtIndex:(unsigned int)arg1;
- (id)dequeueRecycledPage;
- (void)configurePage:(id)arg1 forIndex:(unsigned int)arg2;
- (id)pageDisplayingPhoto:(id)arg1;
- (id)pageDisplayedAtIndex:(unsigned int)arg1;
- (BOOL)isDisplayingPageForIndex:(unsigned int)arg1;
- (void)tilePages;
- (void)handleMWPhotoLoadingDidEndNotification:(id)arg1;
- (void)loadAdjacentPhotosIfNecessary:(id)arg1;
- (id)imageForPhoto:(id)arg1;
- (id)captionViewForPhotoAtIndex:(unsigned int)arg1;
- (id)photoAtIndex:(unsigned int)arg1;
- (unsigned int)numberOfPhotos;
- (void)reloadData;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewWillLayoutSubviews;
- (void)restorePreviousNavBarAppearance:(BOOL)arg1;
- (void)storePreviousNavBarAppearance;
- (void)setNavBarAppearance:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)presentingViewControllerPrefersStatusBarHidden;
- (void)viewDidUnload;
- (void)performLayout;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)releaseAllUnderlyingPhotos:(BOOL)arg1;
- (void)dealloc;
- (void)_initialisation;
- (void)performSwipe:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithPhotos:(id)arg1;
- (id)initWithDelegate:(id)arg1;
- (id)init;

@end

