//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "MWTapDetectingImageViewDelegate.h"
#import "MWTapDetectingViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class DACircularProgressView, MWCaptionView, MWPhotoBrowser, MWTapDetectingImageView, MWTapDetectingView;

@interface MWZoomingScrollView : UIScrollView <UIScrollViewDelegate, MWTapDetectingImageViewDelegate, MWTapDetectingViewDelegate>
{
    MWTapDetectingView *_tapView;
    MWTapDetectingImageView *_photoImageView;
    DACircularProgressView *_loadingIndicator;
    MWCaptionView *_captionView;
    id <MWPhoto> _photo;
    MWPhotoBrowser *_photoBrowser;
}

@property(nonatomic) __weak MWPhotoBrowser *photoBrowser; // @synthesize photoBrowser=_photoBrowser;
@property(retain, nonatomic) id <MWPhoto> photo; // @synthesize photo=_photo;
@property(retain, nonatomic) MWCaptionView *captionView; // @synthesize captionView=_captionView;
- (void).cxx_destruct;
- (void)view:(id)arg1 doubleTapDetected:(id)arg2;
- (void)view:(id)arg1 singleTapDetected:(id)arg2;
- (void)imageView:(id)arg1 doubleTapDetected:(id)arg2;
- (void)imageView:(id)arg1 singleTapDetected:(id)arg2;
- (void)handleDoubleTap:(struct CGPoint)arg1;
- (void)handleSingleTap:(struct CGPoint)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)layoutSubviews;
- (void)setMaxMinZoomScalesForCurrentBounds;
- (void)showLoadingIndicator;
- (void)hideLoadingIndicator;
- (void)setProgressFromNotification:(id)arg1;
- (void)displayImageFailure;
- (void)displayImage;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithPhotoBrowser:(id)arg1;

@end

