//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISwipeGestureRecognizer.h"

#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, NSMutableSet, NSSet, NSString;

@interface MySwipeGestureRecognizer : UISwipeGestureRecognizer <UIGestureRecognizerDelegate>
{
    NSMutableSet *_activeTouches;
    BOOL clearTouches;
    NSString *tag;
    NSMutableArray *disabledViews;
}

@property(retain) NSString *tag; // @synthesize tag;
- (void).cxx_destruct;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)reset;
- (void)clearTouches;
- (void)setState:(int)arg1;
@property(readonly) NSSet *activeTouches;
- (struct CGPoint)currentLocationInView:(id)arg1;
- (void)_touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)_touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)_touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

