//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableArray.h"

@interface NSMutableArray (AFDequeAdditions)
- (id)peekBack;
- (id)peekFront;
- (id)popBack;
- (id)popFront;
- (void)pushBack:(id)arg1;
- (void)pushFront:(id)arg1;
@end

