//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, UITextField;

@interface NTLMGoToUserController : UIViewController <UITextFieldDelegate>
{
    UITextField *textField;
    NSString *findUser;
}

@property(retain, nonatomic) NSString *findUser; // @synthesize findUser;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField;
- (id)createTextField;
- (void)findButtonPushed:(id)arg1;
- (void)setupNavigationBar;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)switchToUserSearchViewWithQuery:(id)arg1;
- (void)switchToUserViewWithScreenName:(id)arg1;
- (void)searchClick;
- (void)goToClick;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)dealloc;

@end

