//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@interface NTLNOAuthConsumer : NSObject
{
    UIViewController *rootViewController;
    id sender;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
+ (id)URLForTwitterOAuth;
- (void)accessTokenTicket:(id)arg1 didFailWithError:(id)arg2;
- (void)accessTokenTicket:(id)arg1 didFinishWithData:(id)arg2;
- (id)screenNameFromHTTPResponseBody:(id)arg1;
- (void)requestTokenTicket:(id)arg1 didFailWithError:(id)arg2;
- (void)requestTokenTicket:(id)arg1 didFinishWithData:(id)arg2;
- (void)dealloc;
- (void)accessToken:(id)arg1;
- (BOOL)isCallbackURL:(id)arg1;
- (void)requestToken:(id)arg1 from:(id)arg2;
- (void)requestToken:(id)arg1;
- (id)consumer;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)autorelease;
- (void)release;
- (unsigned int)retainCount;
- (id)retain;

@end

