//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTLNConfiguration : NSObject
{
    int fontSize;
    int textSize;
    int theme;
    int inlineImages;
    int rotate;
    int timeFormat;
    int displayName;
    int markReadHandler;
    BOOL boldUser;
    BOOL autoExpand;
    BOOL easterEggs;
    BOOL autoLinks;
    BOOL showMarker;
    BOOL scrollToMarker;
    BOOL autoLink;
    BOOL _timeShowScroller;
}

+ (int)fetchCount;
+ (int)refreshIntervalSeconds;
+ (float)getScreenHeight;
+ (float)getScreenWidth;
+ (id)instance;
@property(readonly) BOOL timeShowScroller; // @synthesize timeShowScroller=_timeShowScroller;
@property(readonly) BOOL showMarker; // @synthesize showMarker;
@property(readonly) BOOL scrollToMarker; // @synthesize scrollToMarker;
@property(readonly) int markReadHandler; // @synthesize markReadHandler;
@property(readonly) BOOL autoLink; // @synthesize autoLink;
@property(readonly) int textSize; // @synthesize textSize;
@property(readonly) BOOL easterEggs; // @synthesize easterEggs;
@property(readonly) BOOL autoExpand; // @synthesize autoExpand;
@property(readonly) int displayName; // @synthesize displayName;
@property(readonly) BOOL boldUser; // @synthesize boldUser;
@property(readonly) int rotate; // @synthesize rotate;
@property(readonly) int timeFormat; // @synthesize timeFormat;
@property(readonly) int theme; // @synthesize theme;
@property(readonly) int inlineImages; // @synthesize inlineImages;
@property(readonly) int fontSize; // @synthesize fontSize;
- (void)reload;
- (void)dealloc;
- (id)init;

@end

