//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSString, NTLNTimeline, NTLNTwitterClient;

@protocol NTLNTimelineDelegate
- (void)timeline:(NTLNTimeline *)arg1 clientFailed:(NTLNTwitterClient *)arg2 withError:(NSString *)arg3;
- (void)timeline:(NTLNTimeline *)arg1 clientFailed:(NTLNTwitterClient *)arg2;
- (void)timeline:(NTLNTimeline *)arg1 clientSucceeded:(NTLNTwitterClient *)arg2 insertedStatuses:(NSArray *)arg3;
- (void)timeline:(NTLNTimeline *)arg1 clientEnd:(NTLNTwitterClient *)arg2;
- (void)timeline:(NTLNTimeline *)arg1 clientBegin:(NTLNTwitterClient *)arg2;
- (void)timeline:(NTLNTimeline *)arg1 requestForPage:(int)arg2 since_id:(NSString *)arg3 max_id:(NSString *)arg4;
- (void)timeline:(NTLNTimeline *)arg1 requestForPage:(int)arg2 since_id:(NSString *)arg3;
@end

