//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICTableViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"

@interface NTLNAboutSettingsViewController : UICTableViewController <UIAlertViewDelegate, MFMailComposeViewControllerDelegate>
{
}

- (void)launchMailAppOnDevice;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)displayComposerSheet;
- (void)dealloc;
- (void)doneButtonPushed:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (id)initWithStyle:(int)arg1;
- (void)setupNavButtons;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (void)setupPrototypes;

@end

