//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "NTLNTwitterTrendsClientDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray;

@interface NTLNTrendsSelectionViewController : UITableViewController <UITableViewDelegate, UITableViewDataSource, NTLNTwitterTrendsClientDelegate>
{
    NSMutableArray *locations;
}

@property(retain) NSMutableArray *locations; // @synthesize locations;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)twitterTrendsClientFailed:(id)arg1;
- (void)saveArchive;
- (void)loadArchive;
- (void)twitterTrendsClientSucceeded:(id)arg1;
- (void)getLocations;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)setupTableView;
- (id)initWithStyle:(int)arg1;

@end

