//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NTLNPlace : NSObject
{
    NSString *place_id;
    NSString *name;
    NSString *country;
    NSString *country_code;
    NSString *full_name;
    NSString *place_type;
    NSString *street_address;
}

@property(copy) NSString *full_name; // @synthesize full_name;
@property(copy) NSString *street_address; // @synthesize street_address;
@property(copy) NSString *place_type; // @synthesize place_type;
@property(copy) NSString *country_code; // @synthesize country_code;
@property(copy) NSString *country; // @synthesize country;
@property(copy) NSString *name; // @synthesize name;
@property(copy) NSString *place_id; // @synthesize place_id;
- (void)dealloc;

@end

