//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NTLNListCell;

@interface NTLNListCellView : UIView
{
    NTLNListCell *cell;
}

+ (void)drawScreenName:(id)arg1 selected:(BOOL)arg2;
+ (void)drawText:(id)arg1 selected:(BOOL)arg2;
@property(nonatomic) NTLNListCell *cell; // @synthesize cell;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

