//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "NTLNTListClientDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UIView;

@interface NTLNTListCategoryViewController : UITableViewController <UITableViewDelegate, UITableViewDataSource, NTLNTListClientDelegate, UISearchBarDelegate>
{
    int currentPage;
    NSMutableArray *categories;
    UIView *loadingView;
    NSString *slug;
    NSString *keyword;
    BOOL paging;
    int level;
}

@property int level; // @synthesize level;
@property(retain) NSString *slug; // @synthesize slug;
@property(retain) NSMutableArray *categories; // @synthesize categories;
@property(retain) UIView *loadingView; // @synthesize loadingView;
- (void)tListClientFailed:(id)arg1;
- (void)tListClientSucceeded:(id)arg1;
- (void)getListInfoWithPage:(int)arg1;
- (void)getListInfo;
- (void)beginSearch;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)dealloc;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)helpAction:(id)arg1;
- (void)viewDidLoad;
- (void)setupTableView;
- (void)setupToolbar;
- (id)initWithStyle:(int)arg1;

@end

