//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "MKReverseGeocoderDelegate.h"
#import "NTLNLocationManagerDelegate.h"
#import "NTLNTwitterClientDelegate.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"

@class MKReverseGeocoder, NSMutableArray, NSString, NTLNLocationManager, UIActivityIndicatorView, UIImageView, UILabel, UIScrollView, UISearchBar, UISearchDisplayController, UIView;

@interface NTLNSearchMenuViewController : UITableViewController <UISearchDisplayDelegate, UISearchBarDelegate, NTLNTwitterClientDelegate, MKReverseGeocoderDelegate, NTLNLocationManagerDelegate>
{
    UISearchDisplayController *searchDisplayController;
    UISearchBar *searchBar;
    NSMutableArray *bookmarks;
    BOOL error_visible;
    UIView *errorView;
    UILabel *errorLabel;
    NSString *currentScreenName;
    UIActivityIndicatorView *activityView;
    NTLNLocationManager *locationManager;
    MKReverseGeocoder *geoCoder;
    NSString *currentLocationa;
    NSMutableArray *hashTags;
    NSMutableArray *users;
    NSMutableArray *filteredUsers;
    BOOL loc;
    UIScrollView *topTweetContainer;
    NSMutableArray *topTweets;
    UIImageView *containerbg;
}

@property(retain, nonatomic) UIImageView *containerbg; // @synthesize containerbg;
@property(retain, nonatomic) NSMutableArray *topTweets; // @synthesize topTweets;
@property(retain, nonatomic) UIScrollView *topTweetContainer; // @synthesize topTweetContainer;
@property(retain) NSMutableArray *filteredUsers; // @synthesize filteredUsers;
@property(retain) NSMutableArray *users; // @synthesize users;
@property(retain, nonatomic) NSString *currentLocationa; // @synthesize currentLocationa;
@property(retain) MKReverseGeocoder *geoCoder; // @synthesize geoCoder;
@property(retain) NTLNLocationManager *locationManager; // @synthesize locationManager;
@property(retain) UILabel *errorLabel; // @synthesize errorLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView;
@property(retain) UIView *errorView; // @synthesize errorView;
@property(retain) NSMutableArray *hashTags; // @synthesize hashTags;
@property(retain) NSMutableArray *bookmarks; // @synthesize bookmarks;
@property(retain) UISearchDisplayController *searchDisplayController; // @synthesize searchDisplayController;
@property(retain) UISearchBar *searchBar; // @synthesize searchBar;
- (void)iconUpdate:(id)arg1;
- (void)goToTweet:(id)arg1;
- (void)reloadTopTweets;
- (void)timeline:(id)arg1 clientSucceeded:(id)arg2 insertedStatuses:(id)arg3;
- (void)dealloc;
- (void)saveArchive;
- (void)loadArchive;
- (void)filterContentForUser:(id)arg1;
- (void)loadContactArchive;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)runSearch:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchScope:(int)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchDisplayController:(id)arg1 willUnloadSearchResultsTableView:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)hideErrorBar:(id)arg1;
- (void)showErrorBar:(id)arg1;
- (void)addErrorBar;
- (BOOL)findErrorBar;
- (void)twitterClientEnd:(id)arg1;
- (void)twitterClientBegin:(id)arg1;
- (void)twitterClientFailed:(id)arg1 withError:(id)arg2;
- (void)twitterClientFailed:(id)arg1;
- (void)twitterSearchClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)twitterClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)getBookmarks;
- (void)reverseGeocoder:(id)arg1 didFindPlacemark:(id)arg2;
- (void)reverseGeocoder:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManagerFailed:(id)arg1;
- (void)locationManagerSucceeded:(id)arg1 longitude:(double)arg2 latitude:(double)arg3;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)loadTopTweets;
- (void)editMode:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)postButton:(id)arg1;
- (void)viewDidLoad;

@end

