//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NTLNTListCategory : NSObject
{
    int subcategory_count;
    NSString *name;
    NSString *superlist_name;
    NSString *slug;
    int list_count;
    int category_id;
    NSString *path;
}

@property(copy) NSString *path; // @synthesize path;
@property int category_id; // @synthesize category_id;
@property int list_count; // @synthesize list_count;
@property(copy) NSString *slug; // @synthesize slug;
@property(copy) NSString *superlist_name; // @synthesize superlist_name;
@property(copy) NSString *name; // @synthesize name;
@property int subcategory_count; // @synthesize subcategory_count;
- (id)init;
- (void)dealloc;

@end

