//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNTimelineViewController.h"

#import "NTLNExternalServicesClientDelegate.h"
#import "NTLNTwitterListClientDelegate.h"
#import "NTLNTwitterUserClientDelegate.h"
#import "UIActionSheetDelegate.h"

@class NSString, NTLNList, UIBarButtonItem;

@interface NTLNListTimelineViewController : NTLNTimelineViewController <UIActionSheetDelegate, NTLNTwitterUserClientDelegate, NTLNTwitterListClientDelegate, NTLNExternalServicesClientDelegate>
{
    NSString *listName;
    NSString *listId;
    NSString *screenName;
    UIBarButtonItem *saveButton;
    NSString *subscriptionText;
    NSString *defaultText;
    NTLNList *list;
    struct sqlite3 *database;
    int position;
}

@property(nonatomic) int position; // @synthesize position;
@property(retain) NTLNList *list; // @synthesize list;
@property(retain) NSString *listId; // @synthesize listId;
@property(retain) NSString *screenName; // @synthesize screenName;
@property(retain) NSString *listName; // @synthesize listName;
- (void)externalServicesClientFailed:(id)arg1;
- (void)externalServicesClientSucceeded:(id)arg1;
- (void)updateSyncAndDisplay;
- (void)updateSync;
- (void)getSync;
- (void)disableButton;
- (void)enableButton;
- (void)twitterListClientFailed:(id)arg1;
- (void)twitterListClientSucceeded:(id)arg1;
- (void)twitterUserClientFailed:(id)arg1;
- (void)twitterUserClientSucceeded:(id)arg1;
- (void)getListInfo;
- (void)unsubscribeToList;
- (void)subscribeToList;
- (void)getUserInfo;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)saveButtonAction:(id)arg1;
- (void)hideReloadButton;
- (void)timeline:(id)arg1 clientSucceeded:(id)arg2 insertedStatuses:(id)arg3;
- (void)timeline:(id)arg1 requestForPage:(int)arg2 since_id:(id)arg3 max_id:(id)arg4;
- (void)timeline:(id)arg1 requestForPage:(int)arg2 since_id:(id)arg3;
- (void)loadView;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (id)initWithDetails:(id)arg1 name:(id)arg2 slug:(id)arg3 list:(id)arg4;
- (void)viewDidLoad;
- (void)updateBadge;
- (void)viewWillDisappear:(BOOL)arg1;
- (id)init;

@end

