//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NTLNTrend : NSObject
{
    NSString *query;
    NSString *name;
}

@property(copy) NSString *query; // @synthesize query;
@property(copy) NSString *name; // @synthesize name;
- (void)dealloc;

@end

