//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface NTLNSchedule : NSObject
{
    NSString *schedule_id;
    NSString *text;
    NSDate *time;
}

@property(copy) NSDate *time; // @synthesize time;
@property(copy) NSString *text; // @synthesize text;
@property(copy) NSString *schedule_id; // @synthesize schedule_id;
- (id)init;
- (void)dealloc;

@end

