//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNCell.h"

@class NSString;

@interface NTLNDescriptionCell : NTLNCell
{
    BOOL isEven;
    NSString *description;
    NSString *value;
}

+ (void)drawText:(id)arg1 description:(id)arg2 selected:(BOOL)arg3;
@property(readonly) NSString *value; // @synthesize value;
@property(readonly) NSString *description; // @synthesize description;
- (void)drawBackgroundRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateByNameAndDescriptionRoundBottom:(id)arg1 value:(id)arg2 isEven:(BOOL)arg3;
- (void)updateByNameAndDescriptionRoundTopPlain:(id)arg1 value:(id)arg2 isEven:(BOOL)arg3;
- (void)updateByNameAndDescriptionRounded:(id)arg1 value:(id)arg2 isEven:(BOOL)arg3;
- (void)updateByNameAndDescriptionRoundTop:(id)arg1 value:(id)arg2 isEven:(BOOL)arg3;
- (void)updateByNameAndDescriptionNoDisclosureFull:(id)arg1 value:(id)arg2 isEven:(BOOL)arg3;
- (void)updateByNameAndDescriptionNoDisclosure:(id)arg1 value:(id)arg2 isEven:(BOOL)arg3;
- (void)updateByNameAndDescriptionFull:(id)arg1 value:(id)arg2 isEven:(BOOL)arg3;
- (void)updateByNameAndDescription:(id)arg1 value:(id)arg2 isEven:(BOOL)arg3;
- (void)createCell;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 reuseIdentifier:(id)arg2;

@end

