//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNCell.h"

@class NTLNList, NTLNListCellView, UIImageView;

@interface NTLNListCell : NTLNCell
{
    NTLNList *list;
    BOOL isEven;
    UIImageView *iconView;
    NTLNListCellView *contentView;
}

@property(retain, nonatomic) NTLNListCellView *contentView; // @synthesize contentView;
@property(readonly) NTLNList *list; // @synthesize list;
- (void)updateIcon;
- (void)updateByListFull:(id)arg1 isEven:(BOOL)arg2;
- (void)updateByList:(id)arg1 isEven:(BOOL)arg2;
- (void)createCell;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 reuseIdentifier:(id)arg2;

@end

