//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NTLNResizedImageView, NTLNStatus;

@interface NTLNPhotoCell : UITableViewCell
{
    NTLNResizedImageView *iconView;
    NTLNStatus *status;
    int index;
    id root;
}

@property(retain, nonatomic) NTLNResizedImageView *iconView; // @synthesize iconView;
@property(retain, nonatomic) id root; // @synthesize root;
@property(readonly) NTLNStatus *status; // @synthesize status;
- (void)goToImage:(id)arg1;
- (void)handleSingleTap:(id)arg1;
- (void)drawImage:(id)arg1 isEntity:(BOOL)arg2;
- (void)setNeedsDisplay;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateImage:(id)arg1 url:(id)arg2;
- (void)updateCell:(id)arg1 withIndex:(int)arg2;
- (BOOL)isImage:(id)arg1;
- (BOOL)tweetContainsPhoto:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)init;
- (void)createCell;

@end

