//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface NTLNLinkObject : NSObject
{
    struct CGRect rect;
    NSString *link;
    UIColor *color;
}

@property(retain) UIColor *color; // @synthesize color;
@property(copy) NSString *link; // @synthesize link;
@property struct CGRect rect; // @synthesize rect;
- (void)dealloc;

@end

