//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NTLNAccountCell;

@interface NTLNAccountCellView : UIView
{
    NTLNAccountCell *cell;
}

+ (void)drawText:(id)arg1 user:(id)arg2 selected:(BOOL)arg3;
@property(nonatomic) NTLNAccountCell *cell; // @synthesize cell;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

