//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNTimelineViewController.h"

@class NSArray, NSString;

@interface NTLNUserTimelineViewController : NTLNTimelineViewController
{
    NSString *screenName;
    NSArray *screenNames;
}

@property(retain) NSArray *screenNames; // @synthesize screenNames;
@property(retain) NSString *screenName; // @synthesize screenName;
- (void)postButton:(id)arg1;
- (void)hideReloadButton;
- (void)timeline:(id)arg1 clientSucceeded:(id)arg2 insertedStatuses:(id)arg3;
- (void)timeline:(id)arg1 requestForPage:(int)arg2 since_id:(id)arg3;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

