//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "NTLNTwitterClientDelegate.h"

@class NSMutableArray, NTLNTweetPostViewController;

@interface NTLNTweetPostGeoViewController : UITableViewController <NTLNTwitterClientDelegate>
{
    NTLNTweetPostViewController *postViewController;
    CDStruct_2c43369c location;
    NSMutableArray *pois;
    NSMutableArray *locations;
}

@property(retain, nonatomic) NSMutableArray *locations; // @synthesize locations;
@property(retain, nonatomic) NSMutableArray *pois; // @synthesize pois;
@property(nonatomic) CDStruct_2c43369c location; // @synthesize location;
@property(nonatomic) NTLNTweetPostViewController *postViewController; // @synthesize postViewController;
- (void)twitterClientEnd:(id)arg1;
- (void)twitterClientBegin:(id)arg1;
- (void)twitterClientFailed:(id)arg1 withError:(id)arg2;
- (void)twitterClientFailed:(id)arg1;
- (void)twitterSearchClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)twitterClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)removeLocation:(id)arg1;
- (void)viewDidLoad;
- (void)getLocations;
- (void)getPoi;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithStyle:(int)arg1;

@end

