//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class NSObject<NTLNCacheCleanerDelegate>;

@interface NTLNCacheCleaner : NSObject <UIAlertViewDelegate>
{
    NSObject<NTLNCacheCleanerDelegate> *delegate;
}

+ (id)sharedCacheCleaner;
@property(retain) NSObject<NTLNCacheCleanerDelegate> *delegate; // @synthesize delegate;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)shutdown;
- (BOOL)bootup;
- (void)dealloc;

@end

