//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NTLNUser;

@interface NTLNList : NSObject
{
    NSString *list_id;
    NSString *name;
    NSString *list_name;
    NSString *description;
    NSString *slug;
    int subscriber_count;
    int member_count;
    NSString *mode;
    NSString *screen_name;
    NTLNUser *user;
}

@property(copy) NTLNUser *user; // @synthesize user;
@property(copy) NSString *description; // @synthesize description;
@property(copy) NSString *screen_name; // @synthesize screen_name;
@property(copy) NSString *mode; // @synthesize mode;
@property int member_count; // @synthesize member_count;
@property int subscriber_count; // @synthesize subscriber_count;
@property(copy) NSString *slug; // @synthesize slug;
@property(copy) NSString *list_name; // @synthesize list_name;
@property(copy) NSString *name; // @synthesize name;
@property(copy) NSString *list_id; // @synthesize list_id;
- (id)init;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

