//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNTimelineViewController.h"

#import "UIActionSheetDelegate.h"

@class NSMutableArray, NTLNDMInboxViewController, NTLNDMSentViewController;

@interface NTLNDMCombinedViewController : NTLNTimelineViewController <UIActionSheetDelegate>
{
    NTLNDMInboxViewController *inboxViewController;
    NTLNDMSentViewController *sentViewController;
    NSMutableArray *usersArray;
    NSMutableArray *idArray;
    NSMutableArray *convoArray;
    NSMutableArray *countArray;
    BOOL isLoaded;
}

@property(retain) NSMutableArray *countArray; // @synthesize countArray;
@property BOOL isLoaded; // @synthesize isLoaded;
@property(retain) NSMutableArray *convoArray; // @synthesize convoArray;
@property(retain) NSMutableArray *idArray; // @synthesize idArray;
@property(retain) NSMutableArray *usersArray; // @synthesize usersArray;
@property NTLNDMSentViewController *sentViewController; // @synthesize sentViewController;
@property NTLNDMInboxViewController *inboxViewController; // @synthesize inboxViewController;
- (void)updateSync;
- (void)clearButton:(id)arg1;
- (void)insertStatuses;
- (void)hideReloadButton;
- (BOOL)doReadTrack;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)pulldownRefresh;
- (void)viewWillAppear:(BOOL)arg1;
- (void)actionButtonAction:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)setupNavigationBar;
- (void)loadNextPage;
- (void)autopagerize;
- (void)updateFooterView;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)cellHeightForIndex:(int)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)postButton:(id)arg1;
- (void)fontSizeChanged:(id)arg1;
- (void)filterContentForSearchText:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (void)resetTimeline;
- (void)didReceiveMemoryWarning;
- (void)updateOffsets;
- (void)dealloc;

@end

