//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ATMHudDelegate.h"
#import "MNColorPickerDelegate.h"
#import "NTLNExternalServicesClientDelegate.h"
#import "NTLNImageClientDelegate.h"
#import "NTLNTwitterClientDelegate.h"
#import "NTLNTwitterUserClientDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ATMHud, NSArray, NSMutableArray, NSString, NTLNMessage, NTLNUser, PreviewImageView, UIButton, UIImage, UIImageView, UILabel, UITableView, UITextView, UIView;

@interface NTLNUserViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate, NTLNTwitterUserClientDelegate, NTLNTwitterClientDelegate, NTLNImageClientDelegate, UIImagePickerControllerDelegate, MNColorPickerDelegate, ATMHudDelegate, NTLNExternalServicesClientDelegate>
{
    NTLNMessage *message;
    NSString *followsMessage;
    NSString *passedName;
    BOOL myProfile;
    BOOL editing;
    int followRequests;
    NTLNUser *userInfo;
    UIButton *followButton;
    UIButton *followMain;
    UIImage *selectedPhoto;
    UIImageView *backgroundView;
    UIView *buttons;
    int tracking;
    float screenHeight;
    UIView *errorView;
    int firstLoad;
    PreviewImageView *bannerview;
    UIImageView *iconview;
    UIImageView *verifiedImage;
    UIImage *profileImage;
    ATMHud *overlay;
    BOOL friendshipExists;
    BOOL isBlocked;
    BOOL retweetsEnabled;
    UITextView *textView;
    UILabel *textName;
    UILabel *textScreenName;
    UILabel *userNumber;
    UIView *userView;
    UITableView *tv;
    NSArray *similarUsers;
    NSMutableArray *photos;
}

@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos;
@property(retain) UIView *errorView; // @synthesize errorView;
@property(retain) PreviewImageView *bannerview; // @synthesize bannerview;
@property(retain) NSArray *similarUsers; // @synthesize similarUsers;
@property(retain, nonatomic) UIView *buttons; // @synthesize buttons;
@property(retain, nonatomic) ATMHud *overlay; // @synthesize overlay;
@property(nonatomic) int followRequests; // @synthesize followRequests;
@property(retain) UIImageView *backgroundView; // @synthesize backgroundView;
@property(retain) UIImage *selectedPhoto; // @synthesize selectedPhoto;
@property(retain) UIView *userView; // @synthesize userView;
@property(retain) NTLNUser *userInfo; // @synthesize userInfo;
@property(retain) UIButton *followMain; // @synthesize followMain;
@property(retain) UILabel *userNumber; // @synthesize userNumber;
@property(retain) UILabel *textScreenName; // @synthesize textScreenName;
@property(retain) UILabel *textName; // @synthesize textName;
@property(retain) UIImageView *verifiedImage; // @synthesize verifiedImage;
@property(retain) UITableView *tv; // @synthesize tv;
@property BOOL myProfile; // @synthesize myProfile;
@property(retain) UITextView *textView; // @synthesize textView;
@property(retain) NSString *followsMessage; // @synthesize followsMessage;
@property BOOL friendshipExists; // @synthesize friendshipExists;
@property(retain) UIImage *profileImage; // @synthesize profileImage;
@property(retain) UIImageView *iconview; // @synthesize iconview;
@property(retain) UIButton *followButton; // @synthesize followButton;
@property(retain) NSString *passedName; // @synthesize passedName;
@property(retain) NTLNMessage *message; // @synthesize message;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)getSimilarUsers;
- (void)twitterClientEnd:(id)arg1;
- (void)twitterClientBegin:(id)arg1;
- (void)twitterClientFailed:(id)arg1 withError:(id)arg2;
- (void)twitterClientFailed:(id)arg1;
- (void)otherFlip:(id)arg1;
- (void)otherFlip2:(id)arg1;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)doneMode:(id)arg1;
- (void)editMode:(id)arg1;
- (void)muteUser:(id)arg1;
- (void)twitterSearchClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)twitterClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)twitterUserClientFailed:(id)arg1;
- (void)externalServicesClientFailed:(id)arg1;
- (void)externalServicesClientSucceeded:(id)arg1;
- (void)handleSwipeRight:(id)arg1;
- (void)twitterUserClientSucceeded:(id)arg1;
- (void)twitterUserClientSucceeded:(id)arg1 withDictionary:(id)arg2;
- (void)getUserInfo;
- (void)muteUser:(id)arg1 length:(id)arg2;
- (void)saveiCloud;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)didFinishSavingWithError:(id)arg1 contextInfo:(void *)arg2;
- (void)imageClientFailed:(id)arg1 withError:(id)arg2;
- (void)imageClientSucceeded:(id)arg1 withURL:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)showServicesMenu;
- (void)showBlockMenu;
- (void)colorPickerViewControllerCleared:(id)arg1;
- (void)colorPicker:(id)arg1 didFinishWithColor:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)goToListed;
- (void)goToLists;
- (void)goToMentions;
- (void)goToFavourites;
- (void)goToPhotos;
- (void)goToTweets;
- (void)goToFollowing;
- (void)goToFollowers;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)getTextboxHeight:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)friendshipButtonAction:(id)arg1;
- (void)iconButtonAction:(id)arg1;
- (void)bannerButtonAction:(id)arg1;
- (void)dmButtonAction:(id)arg1;
- (void)replyButtonAction:(id)arg1;
- (id)buttonCell;
- (void)checkFollowerCount;
- (void)checkFollowsBack;
- (void)checkFriendship;
- (void)checkPushTrack;
- (id)newUIImageWithURLString:(id)arg1;
- (void)dealloc;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)updateFooterView;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (void)setupTableView;
- (void)setupUserView;
- (void)updateUserView;
- (id)photoBrowser:(id)arg1 photoAtIndex:(unsigned int)arg2;
- (unsigned int)numberOfPhotosInPhotoBrowser:(id)arg1;
- (void)switchToPictureViewWithURL:(id)arg1;
- (void)switchToBrowserViewWithURL:(id)arg1;
- (void)colorButtonAction:(id)arg1;
- (void)addNavigationButtons;
- (id)init;

@end

