//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "NTLNTwitterListClientDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UIView;

@interface NTLNListViewController : UITableViewController <UITableViewDelegate, UITableViewDataSource, NTLNTwitterListClientDelegate>
{
    int currentPage;
    NSString *currentCursor;
    NSArray *lists;
    NSString *screenName;
    BOOL paging;
    BOOL mentions;
    UIView *loadingView;
}

@property BOOL mentions; // @synthesize mentions;
@property(retain) UIView *loadingView; // @synthesize loadingView;
@property(retain) NSString *currentCursor; // @synthesize currentCursor;
@property(retain) NSString *screenName; // @synthesize screenName;
- (void)iconUpdate:(id)arg1;
- (void)twitterListClientFailed:(id)arg1;
- (void)twitterListClientSucceeded:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)getListInfoWithCursor:(id)arg1;
- (void)getListInfo;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)dealloc;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)setupTableView;
- (id)initWithStyle:(int)arg1;

@end

