//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNCell.h"

@class NSString;

@interface NTLNPlainCell : NTLNCell
{
    BOOL isEven;
    NSString *currName;
    BOOL color;
    id passedObject;
}

+ (void)drawText:(id)arg1 color:(BOOL)arg2 selected:(BOOL)arg3;
@property(retain) id passedObject; // @synthesize passedObject;
@property(readonly) NSString *currName; // @synthesize currName;
- (void)drawBackgroundRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateByNameNoDisclosureFull:(id)arg1 isEven:(BOOL)arg2;
- (void)updateByNameNoDisclosure:(id)arg1 isEven:(BOOL)arg2;
- (void)updateByNameColorFull:(id)arg1 isEven:(BOOL)arg2;
- (void)updateByNameFull:(id)arg1 isEven:(BOOL)arg2;
- (void)updateByName:(id)arg1 isEven:(BOOL)arg2;
- (void)createCell;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 reuseIdentifier:(id)arg2;

@end

