//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "NTLNTwitterClientDelegate.h"
#import "NTLNTwitterTrendsClientDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CALayer, NSArray, NSMutableArray, NTLNTrendLocations, UIActivityIndicatorView, UILabel, UISegmentedControl;

@interface NTLNTrendsViewController : UITableViewController <UITableViewDelegate, UITableViewDataSource, NTLNTwitterClientDelegate, NTLNTwitterTrendsClientDelegate>
{
    NSMutableArray *trends;
    NSMutableArray *trendsOld;
    UISegmentedControl *buttonBarSegmentedControl;
    NTLNTrendLocations *currentLocation;
    CALayer *arrowImage;
    UIActivityIndicatorView *activityView;
    UILabel *statusLabel;
    UILabel *lastUpdatedLabel;
    BOOL playSound;
    BOOL _reload;
}

@property(retain, nonatomic) NTLNTrendLocations *currentLocation; // @synthesize currentLocation;
@property(retain) NSArray *trendsOld; // @synthesize trendsOld;
@property(retain) NSArray *trends; // @synthesize trends;
- (void)pulldownRefresh;
- (void)hideReloadButton;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)reloadView;
- (void)twitterClientEnd:(id)arg1;
- (void)twitterClientBegin:(id)arg1;
- (void)twitterClientFailed:(id)arg1 withError:(id)arg2;
- (void)twitterClientFailed:(id)arg1;
- (void)twitterTrendsClientFailed:(id)arg1;
- (void)twitterTrendsClientSucceeded:(id)arg1;
- (void)twitterSearchClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)twitterClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)togglePickers:(id)arg1;
- (void)getTrendsCurrentByLocation:(id)arg1;
- (void)getTrendsCurrent;
- (void)getTrendsWeekly;
- (void)getTrendsDaily;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)dealloc;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)editButtonAction:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)setupToolbarTrendType;
- (void)setupTableView;
- (id)initWithStyle:(int)arg1;

@end

