//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIPickerViewDelegate.h"

@class NTLNTweetPostViewController, UIDatePicker;

@interface NTLNScheduleViewController : UIViewController <UIPickerViewDelegate>
{
    NTLNTweetPostViewController *postViewController;
    UIDatePicker *datePickerView;
}

@property(nonatomic) NTLNTweetPostViewController *postViewController; // @synthesize postViewController;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)createDatePicker;
- (id)getUTCFormateDate:(id)arg1;
- (struct CGRect)pickerFrameWithSize:(struct CGSize)arg1;
- (void)scheduleButtonPushed:(id)arg1;
- (void)cancelButtonPushed:(id)arg1;
- (void)viewDidLoad;

@end

