//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNHttpClient.h"

@class NSObject<NTLNShortenerClientDelegate>, NSString;

@interface NTLNShortenerClient : NTLNHttpClient
{
    NSObject<NTLNShortenerClientDelegate> *delegate;
    NSString *originalUrl;
}

@property(retain, nonatomic) NSString *originalUrl; // @synthesize originalUrl;
@property(retain) NSObject<NTLNShortenerClientDelegate> *delegate; // @synthesize delegate;
- (void)requestFailed:(id)arg1;
- (void)requestSucceeded;
- (void)shortenAndAppend:(id)arg1;
- (void)shorten:(id)arg1;
- (id)encodeURL:(id)arg1;
- (void)dealloc;

@end

