//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NTLNSuggestedCategory : NSObject
{
    NSString *name;
    NSString *slug;
}

@property(copy) NSString *slug; // @synthesize slug;
@property(copy) NSString *name; // @synthesize name;
- (void)dealloc;

@end

