//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NTLNSchedulerClient;

@protocol NTLNSchedulerClientDelegate
- (void)schedulerClientFailed:(NTLNSchedulerClient *)arg1;
- (void)schedulerClientSucceeded:(NTLNSchedulerClient *)arg1 messages:(NSArray *)arg2;
@end

