//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NTLNTweetPostViewController;

@interface NTLNDraftsViewController : UITableViewController <UITableViewDelegate, UITableViewDataSource>
{
    NTLNTweetPostViewController *postViewController;
    struct sqlite3 *database;
    NSMutableArray *draftId;
    NSMutableArray *draftTitle;
    NSMutableArray *draftCreated;
}

@property(retain) NSMutableArray *draftCreated; // @synthesize draftCreated;
@property(retain) NSMutableArray *draftTitle; // @synthesize draftTitle;
@property(retain) NSMutableArray *draftId; // @synthesize draftId;
@property(nonatomic) NTLNTweetPostViewController *postViewController; // @synthesize postViewController;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)doneButtonPushed:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)saveDraft:(id)arg1;
- (void)getDrafts;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)setupTableView;
- (id)initWithStyle:(int)arg1;

@end

