//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNOAuthHttpClient.h"

@class NSObject<NTLNVideoClientDelegate>;

@interface NTLNVideoClient : NTLNOAuthHttpClient
{
    NSObject<NTLNVideoClientDelegate> *delegate;
    BOOL audio;
    BOOL auth;
}

@property(retain) NSObject<NTLNVideoClientDelegate> *delegate; // @synthesize delegate;
- (void)requestFailed:(id)arg1;
- (void)requestSucceeded;
- (id)nameValString2:(id)arg1;
- (id)nameValString:(id)arg1;
- (void)auth;
- (void)uploadAudio:(id)arg1 message:(id)arg2;
- (void)upload:(id)arg1 message:(id)arg2;
- (void)upload:(id)arg1 token:(id)arg2 message:(id)arg3;
- (void)dealloc;

@end

