//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "NTLNCellBackgroundDelegate.h"

@class UIColor;

@interface NTLNCell : UITableViewCell <NTLNCellBackgroundDelegate>
{
    int cellType;
    UIColor *bgcolor;
    struct CGGradient *gradientForNormal;
}

@property UIColor *bgcolor; // @synthesize bgcolor;
@property int cellType; // @synthesize cellType;
- (void)drawSelectedBackgroundRect:(struct CGRect)arg1;
- (void)drawBackgroundRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawBackgroundGradientImpl:(struct CGRect)arg1 gradient:(struct CGGradient *)arg2;
- (void)drawBackgroundImpl:(struct CGRect)arg1 color:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 reuseIdentifier:(id)arg2;

@end

