//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNTimelineViewController.h"

#import "NTLNExternalServicesClientDelegate.h"

@class NSString, UIBarButtonItem, UISegmentedControl, UIToolbar;

@interface NTLNDirectMessageViewController : NTLNTimelineViewController <NTLNExternalServicesClientDelegate>
{
    UISegmentedControl *buttonBarSegmentedControl;
    UIBarButtonItem *reloadButton;
    UIBarButtonItem *reloadingButton;
    UIBarButtonItem *spacer;
    UIBarButtonItem *segItem;
    UIToolbar *toolbar;
    NSString *inboxFileName;
    NSString *sentFileName;
    BOOL inbox;
}

@property(retain, nonatomic) UISegmentedControl *buttonBarSegmentedControl; // @synthesize buttonBarSegmentedControl;
@property(retain, nonatomic) NSString *sentFileName; // @synthesize sentFileName;
@property(retain, nonatomic) NSString *inboxFileName; // @synthesize inboxFileName;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar;
@property(retain, nonatomic) UIBarButtonItem *segItem; // @synthesize segItem;
@property(retain, nonatomic) UIBarButtonItem *spacer; // @synthesize spacer;
@property(retain, nonatomic) UIBarButtonItem *reloadingButton; // @synthesize reloadingButton;
@property(retain, nonatomic) UIBarButtonItem *reloadButton; // @synthesize reloadButton;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)hideReloadButton;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)timeline:(id)arg1 clientFailed:(id)arg2 withError:(id)arg3;
- (void)timeline:(id)arg1 clientFailed:(id)arg2;
- (void)timeline:(id)arg1 clientSucceeded:(id)arg2 insertedStatuses:(id)arg3;
- (void)timeline:(id)arg1 requestForPage:(int)arg2 since_id:(id)arg3 max_id:(id)arg4;
- (void)timeline:(id)arg1 requestForPage:(int)arg2 since_id:(id)arg3;
- (void)allRead;
- (void)setupNavigationBar;
- (void)toggleFolder:(id)arg1;
- (void)reloadButton:(id)arg1;
- (void)setupToolbar;
- (void)externalServicesClientFailed:(id)arg1;
- (void)externalServicesClientSucceeded:(id)arg1;
- (void)updatePush;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)resetTimeline;
- (BOOL)isTimelineActive;
- (void)didReceiveMemoryWarning;
- (id)init;

@end

