//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NTLNTwitLongerPost : NSObject
{
    NSString *content;
    NSString *link_id;
    NSString *link;
    NSString *link_short;
}

@property(copy) NSString *link_short; // @synthesize link_short;
@property(copy) NSString *link; // @synthesize link;
@property(copy) NSString *link_id; // @synthesize link_id;
@property(copy) NSString *content; // @synthesize content;
- (void)dealloc;

@end

