//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSObject<NTLNLocationManagerDelegate>;

@interface NTLNLocationManager : NSObject <CLLocationManagerDelegate>
{
    NSObject<NTLNLocationManagerDelegate> *delegate;
    CLLocationManager *locationManager;
}

@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager;
@property(retain) NSObject<NTLNLocationManagerDelegate> *delegate; // @synthesize delegate;
- (void)enableUpdating;
- (void)disableUpdating;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)stop;
- (void)begin;
- (void)dealloc;

@end

