//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, OAToken;

@interface NTLNAccount : NSObject
{
    OAToken *userToken;
    NSString *screenName;
    NSString *password;
    NSString *tppassword;
}

+ (id)userTokenForAccount:(id)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (void)setWaitForOAuthCallback:(BOOL)arg1;
- (BOOL)waitForOAuthCallback;
- (void)setUserToken:(id)arg1;
- (id)userToken;
- (BOOL)valid;
- (id)footer;
- (id)password;
- (id)tppassword;
- (void)setTwitPicPassword:(id)arg1;
- (void)setPassword:(id)arg1;
- (id)screenName;
- (void)setScreenName:(id)arg1;
- (void)dealloc;
- (void)updatetp;
- (void)update;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)autorelease;
- (void)release;
- (unsigned int)retainCount;
- (id)retain;

@end

