//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "NTLNTimelineDelegate.h"

@class NSArray, NSMutableArray, NSString, NTLNTimeline, UIView;

@interface NTLNUserPhotoTimelineViewController : UITableViewController <NTLNTimelineDelegate>
{
    NSString *screenName;
    NSArray *screenNames;
    NTLNTimeline *timeline;
    NSMutableArray *filteredTimeline;
    NSMutableArray *photos;
    UIView *nowloadingView;
}

@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos;
@property(retain, nonatomic) NSMutableArray *filteredTimeline; // @synthesize filteredTimeline;
@property(readonly) NTLNTimeline *timeline; // @synthesize timeline;
@property(retain) NSArray *screenNames; // @synthesize screenNames;
@property(retain) NSString *screenName; // @synthesize screenName;
- (void)timeline:(id)arg1 clientFailed:(id)arg2 withError:(id)arg3;
- (void)timeline:(id)arg1 clientFailed:(id)arg2;
- (void)timeline:(id)arg1 clientEnd:(id)arg2;
- (void)timeline:(id)arg1 clientBegin:(id)arg2;
- (void)timeline:(id)arg1 requestForPage:(int)arg2 since_id:(id)arg3 max_id:(id)arg4;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)removeNowloadingView;
- (void)insertNowloadingViewIfNeeds;
- (id)nowloadingView;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)timeline:(id)arg1 clientSucceeded:(id)arg2 insertedStatuses:(id)arg3;
- (void)timeline:(id)arg1 requestForPage:(int)arg2 since_id:(id)arg3;
- (id)convertImage:(id)arg1;
- (void)goToPage:(id)arg1 tweet:(id)arg2;
- (void)goToPage:(id)arg1;
- (id)photoBrowser:(id)arg1 photoAtIndex:(unsigned int)arg2;
- (unsigned int)numberOfPhotosInPhotoBrowser:(id)arg1;
- (void)goToPage:(id)arg1 link:(id)arg2;
- (BOOL)isImage:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)iconUpdate:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

