//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MKMapViewDelegate.h"

@class MKMapView, NSString, NTLNTweetPostGeoViewController, NTLNTweetPostViewController, UIImage, UISegmentedControl, windowOverlay;

@interface NTLNLocationViewController : UIViewController <MKMapViewDelegate>
{
    MKMapView *mapView;
    NSString *screenName;
    NSString *userLocation;
    UIImage *userImage;
    UISegmentedControl *buttonBarSegmentedControl;
    windowOverlay *overlay;
    NTLNTweetPostViewController *postViewController;
    NTLNTweetPostGeoViewController *geoViewController;
}

@property(nonatomic) NTLNTweetPostGeoViewController *geoViewController; // @synthesize geoViewController;
@property(nonatomic) NTLNTweetPostViewController *postViewController; // @synthesize postViewController;
@property(retain) UIImage *userImage; // @synthesize userImage;
@property(retain) NSString *userLocation; // @synthesize userLocation;
@property(retain) NSString *screenName; // @synthesize screenName;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (CDStruct_2c43369c)addressLocation;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)togglePickers:(id)arg1;
- (void)setupToolbarMapType;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)goToGoogleMaps:(id)arg1;
- (void)viewDidLoad;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)hideLoading;
- (void)showLoading;
- (void)changeMap;
- (void)getLocation;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
- (void)setLocation:(id)arg1;
- (void)setProfileImage:(id)arg1;
- (void)setUsername:(id)arg1;

@end

