//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNTimelineViewController.h"

@class NSMutableArray, NSString, NTLNDMInboxViewController, NTLNDMSentViewController;

@interface NTLNDMConversationViewController : NTLNTimelineViewController
{
    NTLNDMInboxViewController *inboxViewController;
    NTLNDMSentViewController *sentViewController;
    NSString *passedUser;
    NSMutableArray *convoArray;
}

@property(retain) NSMutableArray *convoArray; // @synthesize convoArray;
@property(retain) NSString *passedUser; // @synthesize passedUser;
@property NTLNDMSentViewController *sentViewController; // @synthesize sentViewController;
@property NTLNDMInboxViewController *inboxViewController; // @synthesize inboxViewController;
- (void)clearButton:(id)arg1;
- (void)hideReloadButton;
- (BOOL)doReadTrack;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)postButton:(id)arg1;
- (void)pulldownRefresh;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setupNavigationBar;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)cellHeightForIndex:(int)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)viewDidLoad;
- (void)resetTimeline;
- (void)setupTableView;
- (void)updateOffsets;
- (void)dealloc;

@end

