//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSString, UIColor, UIImage;

@interface NTLNResizedImageView : UIView <UIScrollViewDelegate>
{
    UIImage *image;
    float roundSize;
    NSString *passedString;
    BOOL addInsetShadow;
    UIColor *arrowColor;
    BOOL addScroll;
    BOOL addParallax;
}

@property(nonatomic) BOOL addParallax; // @synthesize addParallax;
@property(nonatomic) BOOL addScroll; // @synthesize addScroll;
@property(retain, nonatomic) UIColor *arrowColor; // @synthesize arrowColor;
@property(nonatomic) BOOL addInsetShadow; // @synthesize addInsetShadow;
@property(retain) NSString *passedString; // @synthesize passedString;
- (void)setImage:(id)arg1;
- (void)updateOffsets:(float)arg1;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 image:(id)arg2 round:(float)arg3;

@end

