//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTLNCache : NSObject
{
}

+ (void)removeCachedDrafts;
+ (void)removeCachedTimelines;
+ (void)removeThemeCache;
+ (void)removeUserCache;
+ (void)removeCachedImages;
+ (void)removeCachedIcons;
+ (void)removeAllCachedData;
+ (id)loadWithFilename:(id)arg1;
+ (BOOL)fileExists:(id)arg1;
+ (void)saveWithFilename:(id)arg1 data:(id)arg2;
+ (id)createTextCacheDirectory;
+ (id)createArchiverCacheDirectory;
+ (id)createOldImageCacheDirectory;
+ (id)createPhotoCacheDirectory;
+ (id)createImageCacheDirectory;
+ (id)createUserCacheDirectory;
+ (id)createThemeCacheDirectory;
+ (id)createOldIconCacheDirectory;
+ (id)createIconCacheDirectory;
+ (id)createTemporaryCacheDirectoryWithName:(id)arg1;
+ (id)createCacheDirectoryWithName:(id)arg1;
+ (BOOL)copyPlistFromiCloud:(id)arg1 path:(id)arg2;
+ (BOOL)copyPlistToiCloud:(id)arg1 path:(id)arg2;
+ (BOOL)isiCloudSupported;

@end

