//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableArray, NSMutableData, NSString, NSURLConnection, NTLNDebugObject;

@interface NTLNHttpClient : NSObject
{
    NSURLConnection *connection;
    NSMutableData *recievedData;
    int statusCode;
    BOOL contentTypeIsXml;
    BOOL contentTypeIsHtml;
    BOOL contentTypeIsJson;
    BOOL contentTypeIsJS;
    BOOL contentTypeIsText;
    int rate_limit;
    int rate_limit_remaining;
    NSString *access_level;
    NSDate *rate_limit_reset;
    NSMutableArray *debugObjs;
    NTLNDebugObject *debugObj;
}

+ (id)stringOfAuthorizationHeaderWithUsername:(id)arg1 password:(id)arg2;
+ (id)stringEncodedWithBase64:(id)arg1;
@property(readonly, retain) NTLNDebugObject *debugObj; // @synthesize debugObj;
@property(readonly, retain) NSMutableArray *debugObjs; // @synthesize debugObjs;
@property(readonly) int statusCode; // @synthesize statusCode;
@property(readonly) NSMutableData *recievedData; // @synthesize recievedData;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (void)requestFailed:(id)arg1;
- (void)requestSucceeded;
- (void)cancel;
- (void)requestPOST:(id)arg1 body:(id)arg2 username:(id)arg3 password:(id)arg4;
- (void)requestDELETE:(id)arg1 body:(id)arg2 username:(id)arg3 password:(id)arg4;
- (void)requestDELETE:(id)arg1 username:(id)arg2 password:(id)arg3;
- (void)requestGET:(id)arg1 username:(id)arg2 password:(id)arg3;
- (void)requestPOST:(id)arg1 data:(id)arg2;
- (void)requestPOST:(id)arg1 body:(id)arg2;
- (void)requestPOST:(id)arg1;
- (void)requestDELETE:(id)arg1 body:(id)arg2;
- (void)requestDELETE:(id)arg1;
- (void)requestGET:(id)arg1;
- (void)requestGET:(id)arg1 withRunLoop:(BOOL)arg2;
- (void)prepareWithRequestEcho:(id)arg1;
- (void)prepareWithRequest:(id)arg1;
- (void)reset;
- (id)makeRequest:(id)arg1 username:(id)arg2 password:(id)arg3;
- (id)makeRequest:(id)arg1;
- (void)saveDebugCache;
- (void)loadDebugCache;
- (void)dealloc;
- (id)init;

@end

