//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActionSheet.h"

@class NSString, NTLNMessage;

@interface NTLNActionSheet : UIActionSheet
{
    NTLNMessage *message;
    NSString *screenName;
}

@property(retain, nonatomic) NSString *screenName; // @synthesize screenName;
@property(retain, nonatomic) NTLNMessage *message; // @synthesize message;
- (void)dealloc;

@end

