//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface NTLNTheme : NSObject
{
    NSString *title;
    NSString *creator;
    BOOL isDark;
    BOOL isDarkNavBar;
    UIColor *homeColorTop;
    UIColor *homeColorBottom;
    UIColor *mentionColorTop;
    UIColor *mentionColorBottom;
    UIColor *dmColorTop;
    UIColor *dmColorBottom;
    UIColor *timelineSeperatorColor;
    UIColor *textColor;
    UIColor *highlightTextColor;
    UIColor *timeColor;
    UIColor *composeColorTop;
    UIColor *composeColorBottom;
    UIColor *composeTextColor;
    UIColor *navBarColor;
    UIColor *linkColor;
    UIColor *mentionTextColor;
    UIColor *dmTextColor;
    UIColor *timelineBackground;
    UIColor *annotationColor;
    UIColor *homeNameColor;
    UIColor *mentionNameColor;
    UIColor *dmNameColor;
    UIColor *textMention;
    UIColor *textDm;
    UIColor *timeMention;
    UIColor *timeDm;
    UIColor *navBarBackground;
}

@property(retain) UIColor *navBarBackground; // @synthesize navBarBackground;
@property(retain) UIColor *timeDm; // @synthesize timeDm;
@property(retain) UIColor *timeMention; // @synthesize timeMention;
@property(retain) UIColor *textDm; // @synthesize textDm;
@property(retain) UIColor *textMention; // @synthesize textMention;
@property(retain) UIColor *dmNameColor; // @synthesize dmNameColor;
@property(retain) UIColor *mentionNameColor; // @synthesize mentionNameColor;
@property(retain) UIColor *homeNameColor; // @synthesize homeNameColor;
@property(retain) UIColor *annotationColor; // @synthesize annotationColor;
@property(retain) UIColor *timelineBackground; // @synthesize timelineBackground;
@property(retain) UIColor *dmTextColor; // @synthesize dmTextColor;
@property(retain) UIColor *mentionTextColor; // @synthesize mentionTextColor;
@property(retain) UIColor *linkColor; // @synthesize linkColor;
@property(retain) UIColor *navBarColor; // @synthesize navBarColor;
@property(retain) UIColor *composeTextColor; // @synthesize composeTextColor;
@property(retain) UIColor *composeColorBottom; // @synthesize composeColorBottom;
@property(retain) UIColor *composeColorTop; // @synthesize composeColorTop;
@property(retain) UIColor *timeColor; // @synthesize timeColor;
@property(retain) UIColor *highlightTextColor; // @synthesize highlightTextColor;
@property(retain) UIColor *textColor; // @synthesize textColor;
@property(retain) UIColor *timelineSeperatorColor; // @synthesize timelineSeperatorColor;
@property(retain) UIColor *dmColorBottom; // @synthesize dmColorBottom;
@property(retain) UIColor *dmColorTop; // @synthesize dmColorTop;
@property(retain) UIColor *mentionColorBottom; // @synthesize mentionColorBottom;
@property(retain) UIColor *mentionColorTop; // @synthesize mentionColorTop;
@property(retain) UIColor *homeColorBottom; // @synthesize homeColorBottom;
@property(retain) UIColor *homeColorTop; // @synthesize homeColorTop;
@property BOOL isDarkNavBar; // @synthesize isDarkNavBar;
@property BOOL isDark; // @synthesize isDark;
@property(copy) NSString *creator; // @synthesize creator;
@property(copy) NSString *title; // @synthesize title;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

