//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNCell.h"

@class NSString, UIWebView;

@interface NTLNLinkTweetCell : NTLNCell
{
    NSString *text;
    UIWebView *webView;
    NSString *footer;
    float textHeight;
}

+ (void)drawText:(id)arg1 footer:(id)arg2 textHeight:(float)arg3 selected:(BOOL)arg4;
- (void)drawSelectedBackgroundRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)createCellWithWebView:(id)arg1 footer:(id)arg2 textHeight:(float)arg3;
- (void)createCellWithText:(id)arg1 footer:(id)arg2 textHeight:(float)arg3;
- (void)dealloc;

@end

