//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNTimelineViewController.h"

@class NTLNDMInboxViewController, NTLNDirectMessageViewController, NTLNFriendsViewController, NTLNMentionsViewController;

@interface NTLNUnreadsViewController : NTLNTimelineViewController
{
    NTLNFriendsViewController *friendsViewController;
    NTLNMentionsViewController *replysViewController;
    NTLNDirectMessageViewController *directMessageViewController;
    NTLNDMInboxViewController *inboxViewController;
}

@property NTLNDMInboxViewController *inboxViewController; // @synthesize inboxViewController;
@property NTLNDirectMessageViewController *directMessageViewController; // @synthesize directMessageViewController;
@property NTLNMentionsViewController *replysViewController; // @synthesize replysViewController;
@property NTLNFriendsViewController *friendsViewController; // @synthesize friendsViewController;
- (void)clearButton:(id)arg1;
- (void)hideReloadButton;
- (BOOL)doReadTrack;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setupNavigationBar;
- (void)dealloc;

@end

