//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TapDetectingImageViewDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSMutableArray, NSString, TapDetectingImageView, UIBarButtonItem, UIImage, UIScrollView, UITextView, UIToolbar, windowOverlay;

@interface NTLNPhotoViewController : UIViewController <UIScrollViewDelegate, TapDetectingImageViewDelegate, UIActionSheetDelegate>
{
    NSString *url;
    NSString *fixedurl;
    NSString *preUser;
    NSString *preTitle;
    UIScrollView *imageScrollView;
    TapDetectingImageView *imageView;
    UIToolbar *toobarBottom;
    UITextView *textView;
    windowOverlay *overlay;
    BOOL loading;
    BOOL zoomed;
    UIImage *passedImage;
    NSString *originalURL;
    UIBarButtonItem *title;
    NSMutableArray *toobarTopItems;
}

@property(retain) NSString *originalURL; // @synthesize originalURL;
@property(retain) UIImage *passedImage; // @synthesize passedImage;
@property(retain) NSString *fixedurl; // @synthesize fixedurl;
@property(retain) NSString *preTitle; // @synthesize preTitle;
@property(retain) NSString *preUser; // @synthesize preUser;
@property(retain) NSString *url; // @synthesize url;
- (id)imageWithImage:(id)arg1 scaledToSizeWithSameAspectRatio:(struct CGSize)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)showAction:(id)arg1;
- (void)nextButtonPushed:(id)arg1;
- (void)prevButtonPushed:(id)arg1;
- (void)hideButtonPushed:(id)arg1;
- (void)doneButtonPushed:(id)arg1;
- (void)reloadButtonPushed:(id)arg1;
- (void)setupToolbarBottom;
- (void)setupToolbarTop;
- (void)dealloc;
- (void)viewDidUnload;
- (struct CGRect)zoomRectForScale:(float)arg1 withCenter:(struct CGPoint)arg2;
- (void)tapDetectingImageView:(id)arg1 gotTwoFingerTapAtPoint:(struct CGPoint)arg2;
- (void)tapDetectingImageView:(id)arg1 gotDoubleTapAtPoint:(struct CGPoint)arg2;
- (void)tapDetectingImageView:(id)arg1 gotSingleTapAtPoint:(struct CGPoint)arg2;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3;
- (id)viewForZoomingInScrollView:(id)arg1;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)getImage;
- (void)receivedRotate:(id)arg1;
- (void)resizeViewControllerToFitScreen;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)handleTimer:(id)arg1;
- (void)viewDidLoad;
- (void)toggleUI;
- (void)updateToolbars:(id)arg1;
- (void)loadView;
- (id)initWithPicture:(id)arg1;

@end

