//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNTimelineViewController.h"

@class NSString, NTLNTweetShowViewController;

@interface NTLNRelatedTweetsViewController : NTLNTimelineViewController
{
    NSString *statusId;
    NTLNTweetShowViewController *tweetShowViewController;
}

@property(nonatomic) NTLNTweetShowViewController *tweetShowViewController; // @synthesize tweetShowViewController;
- (void)hideReloadButton;
- (void)timeline:(id)arg1 clientSucceeded:(id)arg2 insertedStatuses:(id)arg3;
- (void)timeline:(id)arg1 requestForPage:(int)arg2 since_id:(id)arg3 max_id:(id)arg4;
- (void)timeline:(id)arg1 requestForPage:(int)arg2 since_id:(id)arg3;
- (void)setupNavigationBar;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithStatusId:(id)arg1;

@end

