//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNOAuthHttpClient.h"

@class NSMutableArray, NSObject<NTLNTwitterTrendsClientDelegate>, NSString;

@interface NTLNTwitterTrendsClient : NTLNOAuthHttpClient
{
    NSObject<NTLNTwitterTrendsClientDelegate> *delegate;
    NSMutableArray *trends;
    NSMutableArray *locations;
    NSString *definition;
    BOOL isLocation;
    BOOL isDefinition;
}

+ (id)URLForTwitterWithAccount;
@property(readonly) NSString *definition; // @synthesize definition;
@property(readonly) NSMutableArray *locations; // @synthesize locations;
@property(readonly) NSMutableArray *trends; // @synthesize trends;
@property(retain) NSObject<NTLNTwitterTrendsClientDelegate> *delegate; // @synthesize delegate;
- (void)requestFailed:(id)arg1;
- (void)requestSucceeded;
- (void)getTrendLocations;
- (void)getTrendsForWoeId:(id)arg1;
- (void)getTrendDefinition:(id)arg1;
- (void)dealloc;

@end

