//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "NTLNTwitterUserClientDelegate.h"

@class NSMutableArray, UIActivityIndicatorView;

@interface NTLNSuggestedCategoryViewController : UITableViewController <NTLNTwitterUserClientDelegate>
{
    NSMutableArray *categories;
    UIActivityIndicatorView *activityView;
}

@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView;
@property(retain) NSMutableArray *categories; // @synthesize categories;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)twitterUserClientFailed:(id)arg1;
- (void)twitterUserClientSucceeded:(id)arg1;
- (void)getCategories;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLoad;

@end

