//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSMutableArray, NTLNDebugObject;

@interface NTLNDebugViewController : UITableViewController
{
    NSMutableArray *debugObjs;
    NTLNDebugObject *debugObj;
}

@property(readonly, retain) NSMutableArray *debugObjs; // @synthesize debugObjs;
@property(readonly, retain) NTLNDebugObject *debugObj; // @synthesize debugObj;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)saveDebugCache;
- (void)loadDebugCache;
- (void)clearButtonPushed:(id)arg1;
- (void)viewDidLoad;

@end

