//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNCell.h"

@class NTLNStatus, UIActivityIndicatorView, UIImageView;

@interface NTLNGapCell : NTLNCell
{
    BOOL isEven;
    BOOL color;
    NTLNStatus *status;
    UIActivityIndicatorView *activityView;
    UIImageView *reloadIcon;
}

+ (void)drawImage:(id)arg1 rect:(struct CGRect)arg2 color:(id)arg3 selected:(BOOL)arg4;
@property(readonly) UIImageView *reloadIcon; // @synthesize reloadIcon;
@property(readonly) UIActivityIndicatorView *activityView; // @synthesize activityView;
@property(readonly) NTLNStatus *status; // @synthesize status;
- (void)removeSwipeMenu;
- (void)drawBackgroundRect:(struct CGRect)arg1;
- (void)updateBackgroundColor;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateFull:(id)arg1 isEven:(BOOL)arg2;
- (void)update:(id)arg1 isEven:(BOOL)arg2;
- (void)updateTL;
- (void)createCell;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 reuseIdentifier:(id)arg2;

@end

