//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "NTLNExternalServicesClientDelegate.h"
#import "NTLNTwitterClientDelegate.h"
#import "TwitLongerClientDelegate.h"
#import "UIActionSheetDelegate.h"

@class NSString, NTLNRoundedIconView, NTLNStatus, UIButton, UIImageView, UILabel, UIView, windowOverlay;

@interface NTLNStatusCell : UITableViewCell <TwitLongerClientDelegate, UIActionSheetDelegate, NTLNTwitterClientDelegate, NTLNExternalServicesClientDelegate>
{
    NTLNRoundedIconView *iconView;
    NTLNRoundedIconView *iconView2;
    UIImageView *unreadView;
    UIImageView *starView;
    UIImageView *photoView;
    UIImageView *reTweetView;
    UIImageView *geoLocationView;
    UIImageView *fsqView;
    UIImageView *convoView;
    NTLNStatus *status;
    BOOL disableColorize;
    BOOL isEven;
    BOOL _cancelTouches;
    windowOverlay *overlay;
    UILabel *tweet;
    UIButton *replyButton;
    UIButton *rtButton;
    UIButton *favButton;
    UIButton *transButton;
    UIButton *userButton;
    UIButton *linkButton;
    struct CGPoint gestureStartPoint;
    UIView *swipeMenu;
    id root;
    BOOL reDisplay;
    BOOL noGestures;
    int currentHeightPosition;
    int currentWidthPosition;
    BOOL imageLoaded;
    BOOL pinchBegan;
    int callSwipeCount;
    NSString *selectedLink;
    UIButton *_linkButton;
}

+ (BOOL)textContainsPhoto:(id)arg1;
+ (void)drawTexts:(id)arg1 selected:(BOOL)arg2;
+ (void)drawTexts:(id)arg1 disableColorize:(BOOL)arg2 selected:(BOOL)arg3;
+ (float)getTextboxHeight:(id)arg1 media:(BOOL)arg2;
+ (float)getScreenWidth;
+ (id)metaFont2;
+ (id)metaFont;
+ (id)textFont;
@property(retain) UIButton *linkButton; // @synthesize linkButton=_linkButton;
@property BOOL noGestures; // @synthesize noGestures;
@property BOOL reDisplay; // @synthesize reDisplay;
@property(retain, nonatomic) NSString *selectedLink; // @synthesize selectedLink;
@property(retain, nonatomic) id root; // @synthesize root;
@property(retain) UIButton *userButton; // @synthesize userButton;
@property(retain) UIButton *rtButton; // @synthesize rtButton;
@property(retain) UIButton *replyButton; // @synthesize replyButton;
@property(retain) UIButton *transButton; // @synthesize transButton;
@property(retain) UIButton *favButton; // @synthesize favButton;
@property(retain, nonatomic) UIView *swipeMenu; // @synthesize swipeMenu;
@property(nonatomic) struct CGPoint gestureStartPoint; // @synthesize gestureStartPoint;
@property(readonly) NTLNStatus *status; // @synthesize status;
- (void)goToImage:(id)arg1;
- (void)drawImage:(id)arg1 isEntity:(BOOL)arg2;
- (void)swipeMenuHide:(id)arg1 finished:(BOOL)arg2 context:(void *)arg3;
- (void)removeSwipeMenu;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)swipeMenuBounce:(id)arg1 finished:(BOOL)arg2 context:(void *)arg3;
- (void)zoomAction:(id)arg1;
- (void)zoomLink:(id)arg1;
- (void)zoomUser:(id)arg1;
- (void)zoomFav:(id)arg1;
- (void)zoomRt:(id)arg1;
- (void)zoomReply:(id)arg1;
- (void)swipeMenuAppear:(id)arg1 finished:(BOOL)arg2 context:(void *)arg3;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)loadMenu;
- (void)performSwipe:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)twitterClientFailed:(id)arg1 withError:(id)arg2;
- (void)twitterClientFailed:(id)arg1;
- (void)twitterClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)twitterClientEnd:(id)arg1;
- (void)twitterClientBegin:(id)arg1;
- (void)externalServicesClientFailed:(id)arg1;
- (void)externalServicesClientSucceeded:(id)arg1;
- (void)twitLongerClientDidFail:(id)arg1 error:(id)arg2 detail:(id)arg3;
- (void)twitLongerClientDidPost:(id)arg1 returnText:(id)arg2;
- (void)updateTL;
- (void)menuRt:(id)arg1;
- (void)menuQuote:(id)arg1;
- (void)swipeLeft:(id)arg1;
- (void)menuReply:(id)arg1;
- (void)menuTrans:(id)arg1;
- (void)menuUser:(id)arg1;
- (void)menuFav:(id)arg1;
- (void)readItLaterSignupFinished:(id)arg1 error:(id)arg2;
- (void)readItLaterLoginFinished:(id)arg1 error:(id)arg2;
- (void)readItLaterSaveFinished:(id)arg1 error:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)menuLink:(id)arg1;
- (void)menuCancel:(id)arg1;
- (void)setDisableColorize;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateImage:(id)arg1 url:(id)arg2;
- (void)updateIcon;
- (void)updateCell:(id)arg1 isEven:(BOOL)arg2;
- (BOOL)isImage:(id)arg1;
- (BOOL)tweetContainsPhoto:(id)arg1;
- (void)iconButtonPushed:(id)arg1;
- (void)cancelTapNHold;
- (void)tapNHoldFired;
- (void)updateBackgroundColor;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithIsEven:(BOOL)arg1;
- (void)performPinch:(id)arg1;
- (void)createCell;
- (id)imageForBackground2;
- (id)imageForBackground;
- (id)colorForBackground;

@end

