//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNHttpClient.h"

@class NSMutableArray, NSObject<NTLNTListClientDelegate>, NSString;

@interface NTLNTListClient : NTLNHttpClient
{
    NSObject<NTLNTListClientDelegate> *delegate;
    NSMutableArray *categories;
    NSString *returnText;
    BOOL category;
    BOOL getlists;
    BOOL list;
    NSMutableArray *lists;
}

@property(readonly) NSString *returnText; // @synthesize returnText;
@property(readonly) NSMutableArray *lists; // @synthesize lists;
@property(readonly) NSMutableArray *categories; // @synthesize categories;
@property(retain) NSObject<NTLNTListClientDelegate> *delegate; // @synthesize delegate;
- (void)requestFailed:(id)arg1;
- (void)requestSucceeded;
- (void)getListsWithPhrase:(id)arg1 page:(int)arg2;
- (void)getListsWithSlug:(id)arg1 page:(int)arg2;
- (void)getCategoryWithSlug:(id)arg1 page:(int)arg2;
- (void)dealloc;

@end

