//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, UIImageView, UILabel;

@interface NTLNErrorViewController : UIViewController
{
    UIImageView *errorImage;
    UILabel *errorTitle;
    UILabel *errorDetail;
    NSString *mode;
}

@property(retain) NSString *mode; // @synthesize mode;
@property(retain) UILabel *errorDetail; // @synthesize errorDetail;
@property(retain) UILabel *errorTitle; // @synthesize errorTitle;
@property(retain) UIImageView *errorImage; // @synthesize errorImage;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLoad;

@end

