//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIActionSheetDelegate.h"
#import "UIWebViewDelegate.h"

@class NSMutableArray, NSString, NTLNWebView, RoundedRectView, UIBarButtonItem, UITextView, UIToolbar;

@interface NTLNPictureViewController : UIViewController <UIWebViewDelegate, UIActionSheetDelegate>
{
    NSString *url;
    NSString *preUser;
    NSString *preTitle;
    NTLNWebView *webView;
    UIToolbar *toobarTop;
    UIToolbar *toobarBottom;
    UITextView *textView;
    RoundedRectView *overlay;
    BOOL loading;
    UIBarButtonItem *title;
    UIBarButtonItem *reloadButton;
    UIBarButtonItem *prevButton;
    UIBarButtonItem *nextButton;
    NSMutableArray *toobarTopItems;
}

@property(retain) NSString *preTitle; // @synthesize preTitle;
@property(retain) NSString *preUser; // @synthesize preUser;
@property(retain) RoundedRectView *overlay; // @synthesize overlay;
@property(retain) NSString *url; // @synthesize url;
- (void)updateReloadButton;
- (void)updatePrevNextButton;
- (void)tweetURLButtonPushed;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)showAction:(id)arg1;
- (void)nextButtonPushed:(id)arg1;
- (void)prevButtonPushed:(id)arg1;
- (void)doneButtonPushed:(id)arg1;
- (void)reloadButtonPushed:(id)arg1;
- (void)setupToolbarBottom;
- (void)setupToolbarTop;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)dealloc;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)handleTimer:(id)arg1;
- (void)viewDidLoad;
- (void)toggleUI;
- (void)updateToolbars:(id)arg1;
- (void)loadView;

@end

