//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "JSCoreTextViewDelegate.h"
#import "NTLNExternalServicesClientDelegate.h"
#import "NTLNTwitterClientDelegate.h"
#import "ReadabilityOAuthHttpClientDelegate.h"
#import "TwitLongerClientDelegate.h"
#import "UIActionSheetDelegate.h"

@class JSTwitterCoreTextView, NSString, NTLNStatus, NTLNStatusAltCellView, PreviewImageView, UIButton, UIImageView, UILabel, UIView, windowOverlay;

@interface NTLNStatusAltCell : UITableViewCell <UIActionSheetDelegate, TwitLongerClientDelegate, NTLNTwitterClientDelegate, NTLNExternalServicesClientDelegate, JSCoreTextViewDelegate, ReadabilityOAuthHttpClientDelegate>
{
    UIImageView *iconView;
    PreviewImageView *previewView;
    UIImageView *additionalOverlay;
    UIImageView *unreadView;
    UIImageView *starView;
    UIImageView *photoView;
    UIImageView *geoLocationView;
    UIImageView *convoView;
    UIImageView *markerView;
    UIImageView *rtView;
    NTLNStatus *status;
    NSString *selectedLink;
    BOOL disableColorize;
    BOOL isEven;
    BOOL _cancelTouches;
    BOOL autoExpand;
    windowOverlay *overlay;
    UILabel *tweet;
    UIButton *replyButton;
    UIButton *rtButton;
    UIButton *favButton;
    UIButton *transButton;
    UIButton *userButton;
    UIButton *linkButton;
    struct CGPoint gestureStartPoint;
    UIView *swipeMenu;
    id root;
    BOOL reDisplay;
    BOOL marker;
    NSString *counter;
    NTLNStatusAltCellView *contentView;
    int currentHeightPosition;
    int theme;
    int currentWidthPosition;
    int inlinePhotos;
    BOOL imageLoaded;
    BOOL supportLazyLoading;
    BOOL pinchBegan;
    BOOL hitLink;
    int callSwipeCount;
    int index;
    BOOL noGestures;
    BOOL cancelTouches;
    JSTwitterCoreTextView *textView;
    float fontSize;
    float textHeight;
    float textHeightWithoutImages;
    float textHeightMedia;
}

+ (id)foregroundColor:(id)arg1 disablecolor:(BOOL)arg2 theme:(int)arg3;
+ (id)linkColor:(id)arg1 disablecolor:(BOOL)arg2 theme:(int)arg3;
+ (id)bgColor:(id)arg1 disablecolor:(BOOL)arg2;
+ (BOOL)isCutout:(id)arg1;
+ (BOOL)isImage:(id)arg1;
+ (BOOL)tweetContainsPhoto:(id)arg1;
+ (BOOL)textContainsPhoto:(id)arg1;
+ (void)drawTexts:(id)arg1 selected:(BOOL)arg2 inlinePhotos:(int)arg3 font:(int)arg4 marker:(BOOL)arg5;
+ (void)drawTexts:(id)arg1 disableColorize:(BOOL)arg2 selected:(BOOL)arg3 theme:(int)arg4 marker:(BOOL)arg5 font:(int)arg6 inlinePhotos:(int)arg7;
+ (float)getTextboxHeightWithoutImages:(id)arg1 inlinePhotos:(int)arg2 font:(int)arg3;
+ (float)getTextboxHeight:(id)arg1 media:(BOOL)arg2 inlinePhotos:(int)arg3 font:(int)arg4;
+ (float)getTextboxHeight:(id)arg1 media:(BOOL)arg2;
+ (float)getTextboxHeight:(id)arg1 rect:(struct CGRect)arg2;
+ (float)getScreenWidth;
+ (id)metaFont2;
+ (id)metaFont;
+ (id)nameFont;
+ (id)textFont;
@property(retain, nonatomic) PreviewImageView *previewView; // @synthesize previewView;
@property(retain, nonatomic) NTLNStatusAltCellView *contentView; // @synthesize contentView;
@property(nonatomic) int index; // @synthesize index;
@property(nonatomic) int inlinePhotos; // @synthesize inlinePhotos;
@property(nonatomic) float fontSize; // @synthesize fontSize;
@property BOOL autoExpand; // @synthesize autoExpand;
@property(retain, nonatomic) JSTwitterCoreTextView *textView; // @synthesize textView;
@property BOOL cancelTouches; // @synthesize cancelTouches;
@property BOOL marker; // @synthesize marker;
@property(nonatomic) int theme; // @synthesize theme;
@property BOOL noGestures; // @synthesize noGestures;
@property(retain) NSString *counter; // @synthesize counter;
@property BOOL reDisplay; // @synthesize reDisplay;
@property(retain, nonatomic) NSString *selectedLink; // @synthesize selectedLink;
@property(retain, nonatomic) id root; // @synthesize root;
@property(retain) UIButton *userButton; // @synthesize userButton;
@property(retain) UIButton *rtButton; // @synthesize rtButton;
@property(retain) UIButton *linkButton; // @synthesize linkButton;
@property(retain) UIButton *replyButton; // @synthesize replyButton;
@property(retain) UIButton *transButton; // @synthesize transButton;
@property(retain) UIButton *favButton; // @synthesize favButton;
@property BOOL disableColorize; // @synthesize disableColorize;
@property(retain, nonatomic) UIView *swipeMenu; // @synthesize swipeMenu;
@property(nonatomic) struct CGPoint gestureStartPoint; // @synthesize gestureStartPoint;
@property(readonly) NTLNStatus *status; // @synthesize status;
- (void)fireVisitLink:(id)arg1;
- (void)iconButtonMenu:(id)arg1;
- (void)fireLink:(id)arg1;
- (void)updateOffsets:(float)arg1;
- (void)drawImage:(id)arg1 isEntity:(BOOL)arg2;
- (void)drawImage:(id)arg1 isEntity:(BOOL)arg2 imageCount:(int)arg3;
- (void)swipeMenuHide:(id)arg1 finished:(BOOL)arg2 context:(void *)arg3;
- (void)removeSwipeMenu;
- (void)swipeMenuBounce:(id)arg1 finished:(BOOL)arg2 context:(void *)arg3;
- (void)zoomAction:(id)arg1;
- (void)zoomLink:(id)arg1;
- (void)zoomUser:(id)arg1;
- (void)zoomFav:(id)arg1;
- (void)zoomRt:(id)arg1;
- (void)zoomReply:(id)arg1;
- (void)swipeMenuAppear:(id)arg1 finished:(BOOL)arg2 context:(void *)arg3;
- (void)performSwipe:(id)arg1;
- (void)loadMenu;
- (void)twitterClientFailed:(id)arg1 withError:(id)arg2;
- (void)twitterClientFailed:(id)arg1;
- (void)twitterClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)twitterClientEnd:(id)arg1;
- (void)twitterClientBegin:(id)arg1;
- (void)externalServicesClientFailed:(id)arg1;
- (void)hideOverlay:(id)arg1;
- (void)externalServicesClientSucceeded:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)menuRt:(id)arg1;
- (id)myCustomAuth;
- (void)menuQuote:(id)arg1;
- (void)swipeLeft:(id)arg1;
- (void)menuReply:(id)arg1;
- (void)menuTrans:(id)arg1;
- (void)menuUser:(id)arg1;
- (void)menuFavLong:(id)arg1;
- (void)menuFav:(id)arg1;
- (void)readItLaterSignupFinished:(id)arg1 error:(id)arg2;
- (void)readItLaterLoginFinished:(id)arg1 error:(id)arg2;
- (void)readItLaterSaveFinished:(id)arg1 error:(id)arg2;
- (void)readabilityOAuthHttpClientFailed:(id)arg1;
- (void)readabilityOAuthHttpClientSucceeded:(id)arg1;
- (void)postLink:(id)arg1;
- (void)openLink:(id)arg1;
- (void)readLater:(id)arg1;
- (void)menuLink:(id)arg1;
- (void)menuCancel:(id)arg1;
- (void)setDisableColorize;
- (void)setNeedsDisplay;
- (void)updateTL;
- (void)twitLongerClientDidFail:(id)arg1 error:(id)arg2 detail:(id)arg3;
- (void)twitLongerClientDidPost:(id)arg1 returnText:(id)arg2;
- (void)textView:(id)arg1 linkHeld:(id)arg2;
- (void)textView:(id)arg1 linkTapped:(id)arg2;
- (void)updateCell:(id)arg1 isEven:(BOOL)arg2;
- (void)updateColorGroup:(id)arg1;
- (BOOL)isImage:(id)arg1;
- (BOOL)tweetContainsPhoto:(id)arg1;
- (void)iconButtonPushed:(id)arg1;
- (void)updateBackgroundColor;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithIsEven:(BOOL)arg1;
- (void)performPinch:(id)arg1;
- (void)layoutSubviews;
- (void)createPreview:(struct CGRect)arg1 round:(float)arg2;
- (void)goToImage:(id)arg1;
- (void)handleSingleTap:(id)arg1;
- (void)handleIconSingleTap:(id)arg1;
- (void)createPreview:(struct CGRect)arg1;
- (void)createCell;
- (struct CGGradient *)gradientForBackground;
- (id)imageForBackground2;
- (id)imageForBackground;
- (id)colorForBackground;
- (float)getTextboxHeightWithoutImages:(id)arg1;
- (float)getTextboxHeight:(id)arg1 media:(BOOL)arg2;
- (float)getTextboxHeight:(id)arg1 rect:(struct CGRect)arg2;

@end

