//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "ATMHudDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"

@class ATMHud, NSMutableArray, NSURL, NTLNTheme;

@interface NTLNThemeListViewController : UITableViewController <UIActionSheetDelegate, UIAlertViewDelegate, ATMHudDelegate>
{
    NSMutableArray *themes;
    NTLNTheme *currentTheme;
    NSURL *installUrl;
    ATMHud *overlay;
    BOOL preview;
}

@property(retain, nonatomic) ATMHud *overlay; // @synthesize overlay;
@property(nonatomic) BOOL preview; // @synthesize preview;
@property(retain, nonatomic) NSURL *installUrl; // @synthesize installUrl;
@property(retain, nonatomic) NTLNTheme *currentTheme; // @synthesize currentTheme;
@property(retain, nonatomic) NSMutableArray *themes; // @synthesize themes;
- (void)duplicateTheme:(id)arg1;
- (void)selectTheme:(id)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)getThemeContents;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)getFileContents;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadCurrentTheme;
- (void)saveCurrentTheme:(id)arg1;
- (void)saveArchive;
- (void)loadArchive;
- (void)addButton:(id)arg1;
- (void)viewDidLoad;

@end

