//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NTLNTwitterClientDelegate.h"

@class NSMutableArray, NSString, NTLNMessage, UIImage;

@interface NTLNTwitterPost : NSObject <NTLNTwitterClientDelegate>
{
    NSString *text;
    NSString *backupFilename;
    NTLNMessage *replyMessage;
    NSString *userId;
    id delegate;
    BOOL isDM;
    BOOL scheduled;
    NSString *messageTo;
    UIImage *image;
    BOOL isEdit;
    NSMutableArray *media;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shardInstance;
@property(readonly) UIImage *image; // @synthesize image;
@property(readonly) NSString *messageTo; // @synthesize messageTo;
@property id <NTLNTwitterClientDelegate> delegate; // @synthesize delegate;
@property(readonly) NTLNMessage *replyMessage; // @synthesize replyMessage;
- (void)twitterClientEnd:(id)arg1;
- (void)twitterClientBegin:(id)arg1;
- (void)twitterClientFailed:(id)arg1 withError:(id)arg2;
- (void)twitterClientFailed:(id)arg1;
- (void)twitterSearchClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)twitterClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)dealloc;
- (id)text;
- (void)updateText:(id)arg1;
- (void)setMedia:(id)arg1;
- (void)setUserIdentifier:(id)arg1;
- (void)backupText;
- (void)retweet:(id)arg1;
- (void)postWithSchedule:(id)arg1 longitude:(id)arg2 schedule:(id)arg3 displayCoords:(BOOL)arg4;
- (void)postWithSchedule:(id)arg1 longitude:(id)arg2 schedule:(id)arg3;
- (void)post:(id)arg1 longitude:(id)arg2 displayCoords:(BOOL)arg3;
- (void)postWithPlaceId:(id)arg1;
- (void)post:(id)arg1 longitude:(id)arg2;
- (void)postWithSchedule:(id)arg1;
- (void)post;
- (void)setPostDelegate:(id)arg1;
- (BOOL)isValidInReplyToScreenName:(id)arg1;
- (BOOL)isDirectMessage;
- (BOOL)isNewDirectMessage;
- (BOOL)isEdit;
- (void)setImage:(id)arg1;
- (void)createDMPost:(id)arg1 reset:(BOOL)arg2;
- (void)createDMPost:(id)arg1;
- (BOOL)hasImage;
- (void)resetDM;
- (void)setDM:(BOOL)arg1;
- (void)createDMPost:(id)arg1 withReplyMessage:(id)arg2;
- (void)createReplyPost:(id)arg1 withReplyMessage:(id)arg2;
- (void)editPost:(id)arg1;
- (BOOL)silenced;
- (id)init;
- (id)autorelease;
- (void)release;
- (unsigned int)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

