//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICTableViewController.h"

#import "ATMHudDelegate.h"
#import "NTLNExternalServicesClientDelegate.h"

@class ATMHud;

@interface NTLNPushSleepViewController : UICTableViewController <NTLNExternalServicesClientDelegate, ATMHudDelegate>
{
    ATMHud *overlay;
    struct sqlite3 *database;
}

@property(retain, nonatomic) ATMHud *overlay; // @synthesize overlay;
- (void)dealloc;
- (void)pickerViewControllerDidDisappear:(id)arg1 mode:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (id)initWithStyle:(int)arg1;
- (void)externalServicesClientFailed:(id)arg1;
- (void)externalServicesClientSucceeded:(id)arg1;
- (void)doneButtonPushed:(id)arg1;
- (void)setupNavButtons;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (void)setupPrototypes;

@end

