//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SKProductsRequestDelegate.h"
#import "UIWebViewDelegate.h"

@class NSMutableArray, UITextView, UIWebView;

@interface NTLNInAppPurchaseViewController : UIViewController <SKProductsRequestDelegate, UIWebViewDelegate>
{
    NSMutableArray *purchasableObjects;
    UIWebView *webView;
    UITextView *price;
    double priceSet;
}

@property(retain, nonatomic) UITextView *price; // @synthesize price;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView;
@property(retain, nonatomic) NSMutableArray *purchasableObjects; // @synthesize purchasableObjects;
- (void)viewWillAppear:(BOOL)arg1;
- (void)buyButtonPushed:(id)arg1;
- (void)updatePrice;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)requestProductData;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)dealloc;
- (id)init;

@end

