//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTLNOAuthHttpClient.h"

@class NSMutableArray, NSObject<NTLNTwitterListClientDelegate>, NSString;

@interface NTLNTwitterListClient : NTLNOAuthHttpClient
{
    NSObject<NTLNTwitterListClientDelegate> *delegate;
    NSMutableArray *lists;
    NSMutableArray *users;
    NSString *nextCursor;
    NSString *previousCursor;
    NSString *returnText;
    BOOL parseUserInfo;
    BOOL dontParse;
    BOOL isLists;
}

+ (id)URLForTwitterWithAccount;
@property(readonly) NSString *returnText; // @synthesize returnText;
@property(readonly) NSString *previousCursor; // @synthesize previousCursor;
@property(readonly) NSString *nextCursor; // @synthesize nextCursor;
@property(readonly) NSMutableArray *users; // @synthesize users;
@property(readonly) NSMutableArray *lists; // @synthesize lists;
@property(retain) NSObject<NTLNTwitterListClientDelegate> *delegate; // @synthesize delegate;
- (void)requestFailed:(id)arg1;
- (void)requestSucceeded;
- (void)getListMentionsWithScreenName:(id)arg1 cursor:(id)arg2;
- (void)unsubscribeToList:(id)arg1 listName:(id)arg2;
- (void)unsubscribeUserToList:(id)arg1 screen_name:(id)arg2 userid:(id)arg3;
- (void)subscribeUserToList:(id)arg1 screen_name:(id)arg2 userid:(id)arg3;
- (void)subscribeUserToList:(id)arg1 screen_name:(id)arg2 userName:(id)arg3;
- (void)createListWithNameAndTypeAndDescription:(id)arg1 screen_name:(id)arg2 privateMode:(BOOL)arg3 description:(id)arg4;
- (void)createListWithNameAndType:(id)arg1 screen_name:(id)arg2 privateMode:(BOOL)arg3;
- (void)deleteListWithNameAndType:(id)arg1 screen_name:(id)arg2;
- (void)subscribeToList:(id)arg1 listName:(id)arg2;
- (void)getSubscribedToListWithScreenName:(id)arg1 listName:(id)arg2 userId:(id)arg3;
- (void)getListsSubscribedWithScreenName:(id)arg1 cursor:(id)arg2;
- (void)getListsWithScreenName:(id)arg1 cursor:(id)arg2;
- (void)dealloc;

@end

