//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError, NSURLConnection, NSURLResponse, OAMutableURLRequest;

@interface OADataFetcher : NSObject
{
    OAMutableURLRequest *request;
    NSURLResponse *response;
    NSURLConnection *connection;
    NSError *error;
    NSData *responseData;
    id delegate;
    SEL didFinishSelector;
    SEL didFailSelector;
}

- (void)fetchDataWithRequest:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4;

@end

