//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface OAToken : NSObject
{
    NSString *key;
    NSString *secret;
    NSString *verifier;
}

@property(retain) NSString *verifier; // @synthesize verifier;
@property(retain) NSString *secret; // @synthesize secret;
@property(retain) NSString *key; // @synthesize key;
- (id)description;
- (int)storeInUserDefaultsWithServiceProviderName:(id)arg1 prefix:(id)arg2;
- (void)dealloc;
- (id)initWithUserDefaultsUsingServiceProviderName:(id)arg1 prefix:(id)arg2;
- (id)initWithHTTPResponseBody:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithKey:(id)arg1 secret:(id)arg2;
- (id)init;

@end

