//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MKAnnotation.h"

@class NSString, NTLNMessage, UIImage;

@interface ParkPlaceMark : NSObject <MKAnnotation>
{
    CDStruct_2c43369c coordinate;
    NSString *subtitletext;
    NSString *titletext;
    UIImage *titleimage;
    NTLNMessage *messageStatus;
    int tagId;
}

@property(retain) NTLNMessage *messageStatus; // @synthesize messageStatus;
@property(retain) UIImage *titleimage; // @synthesize titleimage;
@property(retain) NSString *subtitletext; // @synthesize subtitletext;
@property(retain) NSString *titletext; // @synthesize titletext;
@property(readonly, nonatomic) CDStruct_2c43369c coordinate; // @synthesize coordinate;
- (id)initWithCoordinate:(CDStruct_2c43369c)arg1;
- (void)setImage:(id)arg1;
- (void)setSubTitle:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setMessage:(id)arg1;
- (void)setTagId:(int)arg1;
- (id)image;
@property(readonly, copy, nonatomic) NSString *title;
- (int)getTagId;
@property(readonly, copy, nonatomic) NSString *subtitle;

@end

