//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImagePickerController.h"

@class NTLNTweetPostViewController;

@interface PostImagePickerController : UIImagePickerController
{
    NTLNTweetPostViewController *postViewController;
}

@property(nonatomic) NTLNTweetPostViewController *postViewController; // @synthesize postViewController;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)arg1;

@end

