//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSString, UIColor, UIImageView;

@interface PreviewImageView : UIView <UIScrollViewDelegate>
{
    UIImageView *imageView;
    float roundSize;
    NSString *passedString;
    NSString *url;
    BOOL addInsetShadow;
    UIColor *arrowColor;
    BOOL addScroll;
    BOOL addParallax;
}

@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
@property(nonatomic) BOOL addParallax; // @synthesize addParallax;
@property(nonatomic) BOOL addScroll; // @synthesize addScroll;
@property(retain, nonatomic) UIColor *arrowColor; // @synthesize arrowColor;
@property(nonatomic) BOOL addInsetShadow; // @synthesize addInsetShadow;
@property(retain, nonatomic) NSString *url; // @synthesize url;
@property(retain, nonatomic) NSString *passedString; // @synthesize passedString;
- (void)forceAddParallax;
- (void)createView;
- (void)dealloc;
- (void)setNeedsDisplay;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

