//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class CAGradientLayer, PSStoreButtonData;

@interface PSStoreButton : UIButton
{
    PSStoreButtonData *buttonData_;
    id <PSStoreButtonDelegate> buttonDelegate_;
    CAGradientLayer *gradient_;
    struct CGPoint customPadding_;
}

+ (id)appStoreGrayColor;
+ (id)appStoreBlueColor;
+ (id)appStoreGreenColor;
@property(nonatomic) struct CGPoint customPadding; // @synthesize customPadding=customPadding_;
@property(nonatomic) id <PSStoreButtonDelegate> buttonDelegate; // @synthesize buttonDelegate=buttonDelegate_;
@property(retain, nonatomic) PSStoreButtonData *buttonData; // @synthesize buttonData=buttonData_;
- (void)setButtonData:(id)arg1 animated:(BOOL)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)dealloc;
- (id)initWithPadding:(struct CGPoint)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)alignToSuperview;
- (void)updateButtonAnimated:(BOOL)arg1;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)buttonPressed:(id)arg1;
- (void)touchedUpOutside:(id)arg1;

@end

