//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UIWebViewDelegate.h"

@class NSString, UIColor, UIWebView;

@interface PSWebTableViewCell : UITableViewCell <UIWebViewDelegate>
{
    UIWebView *webView_;
    NSString *webViewContent_;
    struct CGSize webViewSize_;
    UIColor *cellBackgroundColor_;
}

@property(retain, nonatomic) UIColor *cellBackgroundColor; // @synthesize cellBackgroundColor=cellBackgroundColor_;
@property(nonatomic) struct CGSize webViewSize; // @synthesize webViewSize=webViewSize_;
@property(copy, nonatomic) NSString *webViewContent; // @synthesize webViewContent=webViewContent_;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=webView_;
- (void)webViewDidFinishLoad:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)prepareForReuse;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)removeWebView;
- (void)showWebView;
- (void)addWebView;

@end

