//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAGradientLayer;

@interface SwipeFeedbackView : UIView
{
    BOOL swipeRecognized;
    UIView *staticSubview;
    CAGradientLayer *gradient;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)____drawRect2:(struct CGRect)arg1;
- (void)dismiss;
- (void)swipeRecognized2:(unsigned int)arg1 padding:(BOOL)arg2 delay:(float)arg3;
- (void)swipeRecognized:(unsigned int)arg1 padding:(BOOL)arg2;
- (void)animationDidStop:(float)arg1;
- (void)handleThemeDidChange:(id)arg1;
- (void)updateGradientColors;
- (id)init;

@end

