//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TapDetectingImageView;

@protocol TapDetectingImageViewDelegate <NSObject>

@optional
- (void)tapDetectingImageView:(TapDetectingImageView *)arg1 gotTwoFingerTapAtPoint:(struct CGPoint)arg2;
- (void)tapDetectingImageView:(TapDetectingImageView *)arg1 gotDoubleTapAtPoint:(struct CGPoint)arg2;
- (void)tapDetectingImageView:(TapDetectingImageView *)arg1 gotSingleTapAtPoint:(struct CGPoint)arg2;
@end

