//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData, NSString, NSURLConnection, OAConsumer, OAHMAC_SHA1SignatureProvider;

@interface TWConnection : NSObject
{
    id delegate;
    NSString *requestURL;
    NSURLConnection *connection;
    NSMutableData *buf;
    int statusCode;
    BOOL needAuth;
    OAHMAC_SHA1SignatureProvider *signatureProvider;
    OAConsumer *consumer;
}

@property(copy, nonatomic) NSString *requestURL; // @synthesize requestURL;
@property(nonatomic) int statusCode; // @synthesize statusCode;
@property(readonly, nonatomic) NSMutableData *buf; // @synthesize buf;
- (void)TWConnectionDidFinishLoading:(id)arg1;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)TWConnectionDidFailWithError:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)cancel;
- (void)postEcho:(id)arg1 data:(id)arg2;
- (void)post:(id)arg1 data:(id)arg2;
- (void)postEcho:(id)arg1 body:(id)arg2;
- (void)post:(id)arg1 body:(id)arg2;
- (id)getEchos:(id)arg1;
- (id)getEchoSignature;
- (id)makeRequestEcho:(id)arg1;
- (void)getEcho:(id)arg1;
- (void)get:(id)arg1;
- (void)addAuthHeader:(id)arg1;
- (void)dealloc;
- (void)prepareWithRequest:(id)arg1;
- (id)makeRequest:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

