//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NTLNCacheCleanerDelegate.h"
#import "NTLNExternalServicesClientDelegate.h"
#import "NTLNTwitterStreamClientDelegate.h"
#import "UIApplicationDelegate.h"
#import "UITabBarControllerDelegate.h"

@class NSMutableArray, NTLNDMCombinedViewController, NTLNDMInboxViewController, NTLNDMSentViewController, NTLNFavoriteViewController, NTLNFriendsViewController, NTLNListMineViewController, NTLNMentionsViewController, NTLNMutedTweetsViewController, NTLNReTweetViewController, NTLNSearchMenuViewController, NTLNSettingViewController, NTLNTrendsViewController, NTLNTwitterStreamClient, NTLNUnreadsViewController, NTLNUserViewController, Reachability, RotatingTabBarController, UIWindow;

@interface TweetingsAppDelegate : NSObject <UIApplicationDelegate, UITabBarControllerDelegate, NTLNCacheCleanerDelegate, NTLNTwitterStreamClientDelegate, NTLNExternalServicesClientDelegate>
{
    UIWindow *window;
    RotatingTabBarController *tabBarController;
    NTLNFriendsViewController *friendsViewController;
    NTLNMentionsViewController *replysViewController;
    NTLNUnreadsViewController *unreadsViewController;
    NTLNSettingViewController *settingViewController;
    NTLNReTweetViewController *retweetViewController;
    NTLNMutedTweetsViewController *mutedViewController;
    NTLNFavoriteViewController *favoriteViewController;
    NTLNListMineViewController *listViewController;
    NTLNUserViewController *profileViewController;
    NTLNSearchMenuViewController *searchViewController;
    NTLNTrendsViewController *trendsViewController;
    NTLNDMInboxViewController *inboxViewController;
    NTLNDMCombinedViewController *combinedViewController;
    NTLNDMSentViewController *sentViewController;
    NTLNTwitterStreamClient *streamClient;
    BOOL dontResetUI;
    BOOL requestReset;
    BOOL applicationActive;
    BOOL memoryReset;
    Reachability *wifiReach;
    struct sqlite3 *database;
    BOOL wasBackgrounded;
    NSMutableArray *bookmarks;
    NSMutableArray *lists;
    unsigned int bti;
}

+ (void)openInChrome:(id)arg1;
+ (id)tabbarControllers;
+ (id)getAppDelegate;
@property(nonatomic) BOOL dontResetUI; // @synthesize dontResetUI;
@property(retain, nonatomic) NTLNMutedTweetsViewController *mutedViewController; // @synthesize mutedViewController;
@property(retain, nonatomic) NTLNFriendsViewController *friendsViewController; // @synthesize friendsViewController;
@property(retain, nonatomic) NSMutableArray *lists; // @synthesize lists;
@property(retain, nonatomic) NSMutableArray *bookmarks; // @synthesize bookmarks;
@property(readonly) BOOL memoryReset; // @synthesize memoryReset;
@property(retain, nonatomic) NTLNTwitterStreamClient *streamClient; // @synthesize streamClient;
@property BOOL requestReset; // @synthesize requestReset;
@property(readonly) BOOL applicationActive; // @synthesize applicationActive;
@property(retain, nonatomic) RotatingTabBarController *tabBarController; // @synthesize tabBarController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window;
- (unsigned int)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (BOOL)isFullScreen;
- (void)removeDropdown;
- (void)showInfo:(id)arg1 detail:(id)arg2;
- (void)showInfo:(id)arg1 detail:(id)arg2 delay:(float)arg3;
- (void)showError:(id)arg1 detail:(id)arg2;
- (void)addList:(id)arg1;
- (void)saveListArchive;
- (void)removeListFromTabBar:(id)arg1;
- (void)addListToTabBar:(id)arg1;
- (void)loadListArchive;
- (void)addSavedSearch:(id)arg1;
- (void)removeFromTabBar:(id)arg1;
- (void)addToTabBar:(id)arg1;
- (void)saveSearchArchive;
- (void)loadSearchArchive;
- (void)memoryWarning:(id)arg1;
- (void)resetUI;
- (void)twitterStreamClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)twitterStreamClientFailed:(id)arg1 withError:(id)arg2;
- (void)twitterStreamClientFailed:(id)arg1;
- (void)twitterStreamClientSendMessage:(id)arg1 message:(id)arg2;
- (void)twitterStreamClientEnd:(id)arg1;
- (void)twitterStreamClientBegin:(id)arg1;
- (void)setupAutoRefresh;
- (void)prefetch;
- (void)updateInterfaceWithReachability:(id)arg1;
- (void)streamingChanged:(id)arg1;
- (void)reachabilityChanged:(id)arg1;
- (void)resetAllTimelinesAndCache;
- (int)tabIdForName:(id)arg1;
- (BOOL)isInFav:(id)arg1;
- (BOOL)isInMoreTab:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)removeDM:(id)arg1;
- (void)removeTweet:(id)arg1;
- (void)removeFav:(id)arg1;
- (void)blockUser:(id)arg1;
- (void)addFilter:(id)arg1;
- (void)externalServicesClientFailed:(id)arg1;
- (void)externalServicesClientSucceeded:(id)arg1;
- (void)checkBackground:(id)arg1;
- (void)updateSync;
- (void)getSync;
- (void)handleTweetLongPressNotification:(id)arg1;
- (void)handleTweetNotification:(id)arg1;
- (void)themeChanged:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)dealloc;
- (void)resetTimelines;
- (void)changeTimelineTheme;
- (void)updateColorCategories;
- (void)updateListBadge:(int)arg1;
- (void)sendMessage:(id)arg1;
- (void)refreshFriends;
- (void)refreshTimelines;
- (BOOL)areTimelinesActive;
- (void)cacheCleanerAlertClosed;
- (void)reruniCloud;
- (void)recheckiCloud;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)twitterClientFailed:(id)arg1;
- (void)twitterClientFailed:(id)arg1 withError:(id)arg2;
- (void)twitterClientSucceeded:(id)arg1 messages:(id)arg2;
- (void)twitterClientEnd:(id)arg1;
- (void)twitterClientBegin:(id)arg1;
- (BOOL)application:(id)arg1 handleOpenURL:(id)arg2;
- (void)createEditableCopyOfDatabaseIfNeeded;
- (void)addAccount;
- (void)checkAccountsTableExists;
- (void)checkUserTableExists;
- (void)checkDraftsTableExists;
- (void)checkSearchTableExists;
- (void)checkHashTableExists;
- (void)checkFilterTableExists;
- (void)toggleNinjaMode:(BOOL)arg1;
- (void)startup;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)createViews;
- (void)addTabFav:(id)arg1;
- (void)saveTabOrder;
- (void)updateResetBool;
- (void)resetTabOrder;
- (void)checkNetwork;
- (void)setTabOrderIfSaved;

@end

