//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, TwitLongerClient;

@protocol TwitLongerClientDelegate
- (void)twitLongerClientDidFail:(TwitLongerClient *)arg1 error:(NSString *)arg2 detail:(NSString *)arg3;
- (void)twitLongerClientDidPost:(TwitLongerClient *)arg1 returnText:(NSString *)arg2;
@end

