//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FleksyLoadingView, FleksyPasteboardManager;

@interface TwoConditionObserver : NSObject
{
    FleksyLoadingView *loadingView;
    FleksyPasteboardManager *_pasteboardManager;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)fire;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)didFinishResourceDownload:(id)arg1;
- (id)initWithPasteboardManager:(id)arg1;

@end

