//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UICPrototypeTableCellSoundSelect, UILabel;

@interface UICTableViewCellSoundSelect : UITableViewCell
{
    UICPrototypeTableCellSoundSelect *prototype;
    UILabel *label;
}

- (void)updateWithPrototype:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 reuseIdentifier:(id)arg2;

@end

