//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UIGestureUtilities : NSObject
{
}

+ (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 disabledViews:(id)arg3;
+ (id)getStateString:(int)arg1;
+ (id)getDirectionString:(unsigned int)arg1;

@end

