//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class UIActivityIndicatorView;

@interface UIImageView (UIActivityIndicatorForSDWebImage)
- (void)setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned int)arg3 progress:(CDUnknownBlockType)arg4 completed:(CDUnknownBlockType)arg5 usingActivityIndicatorStyle:(int)arg6;
- (void)setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned int)arg3 completed:(CDUnknownBlockType)arg4 usingActivityIndicatorStyle:(int)arg5;
- (void)setImageWithURL:(id)arg1 placeholderImage:(id)arg2 completed:(CDUnknownBlockType)arg3 usingActivityIndicatorStyle:(int)arg4;
- (void)setImageWithURL:(id)arg1 completed:(CDUnknownBlockType)arg2 usingActivityIndicatorStyle:(int)arg3;
- (void)setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned int)arg3 usingActivityIndicatorStyle:(int)arg4;
- (void)setImageWithURL:(id)arg1 placeholderImage:(id)arg2 usingActivityIndicatorStyle:(int)arg3;
- (void)setImageWithURL:(id)arg1 usingActivityIndicatorStyle:(int)arg2;
- (void)removeActivityIndicator;
- (void)createActivityIndicatorWithStyle:(int)arg1;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @dynamic activityIndicator;
@end

