//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VariousUtilities : NSObject
{
}

+ (void)playFlickSound;
+ (void)playErrorSound;
+ (void)playTock;
+ (void)initSounds;
+ (id)soundURLForSound:(int)arg1;
+ (id)soundFilenameForSound:(int)arg1;
+ (void)vibrate;
+ (void)print:(id)arg1;
+ (void)_print:(id)arg1;
+ (id)onlyKeepAlphaFromString:(id)arg1;
+ (id)_onlyKeepAlphaFromString:(id)arg1;
+ (id)strictlyLettersSet;
+ (id)removeCharacters:(id)arg1 fromString:(id)arg2;
+ (BOOL)string:(id)arg1 containsAnyCharacterInString:(id)arg2;
+ (BOOL)string:(id)arg1 containsChar:(unsigned short)arg2;
+ (id)explodeString:(id)arg1;
+ (id)capitalizeString:(id)arg1 basedOn:(id)arg2;
+ (BOOL)charIsAlpha:(unsigned short)arg1;
+ (void)stopSpeaking;
+ (void)performAudioFeedbackFromString:(id)arg1;
+ (void)_performAudioFeedbackFromString:(id)arg1;
+ (id)getPhoneticStringFor:(id)arg1;
+ (void)recreateSpeechEngine;
+ (void)testEncoding:(id)arg1;
+ (id)decode:(id)arg1;
+ (id)encode:(id)arg1;
+ (id)obfuscate:(id)arg1 withKey:(id)arg2;
+ (id)descriptionForCharacter:(const struct FLUnicodeString *)arg1;

@end

