//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WEPopoverController;

@protocol WEPopoverControllerDelegate <NSObject>
- (BOOL)popoverControllerShouldDismissPopover:(WEPopoverController *)arg1;
- (void)popoverControllerDidDismissPopover:(WEPopoverController *)arg1;
@end

