//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RoundedRectView, UIActivityIndicatorView, UILabel, UIProgressView, UIView;

@interface windowOverlay : NSObject
{
    UIView *overlayView;
    UIActivityIndicatorView *indicator;
    UILabel *textView;
    RoundedRectView *roundedRect;
    UIProgressView *progress;
}

@property(retain, nonatomic) UIProgressView *progress; // @synthesize progress;
@property(retain) RoundedRectView *roundedRect; // @synthesize roundedRect;
@property(retain) UILabel *textView; // @synthesize textView;
@property(retain) UIActivityIndicatorView *indicator; // @synthesize indicator;
@property(retain) UIView *overlayView; // @synthesize overlayView;
- (void)dealloc;
- (void)hideWithoutAnimation;
- (void)hide;
- (void)showWithoutAnimation;
- (void)show;
- (void)setText:(id)arg1;
- (void)updateProgress:(float)arg1;
- (void)hideBackground:(BOOL)arg1;
- (id)initWithView:(id)arg1;

@end

