//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDate, NSObject<OS_dispatch_queue>, NSString, UIColor, UIImage, UIImageView, UILabel;

@interface YRDropdownView : UIView
{
    NSString *titleText;
    NSString *detailText;
    UILabel *titleLabel;
    UILabel *detailLabel;
    UIImageView *backgroundImageView;
    UIImageView *accessoryImageView;
    UIColor *titleLabelColor;
    UIColor *detailLabelColor;
    SEL onTouch;
    NSDate *showStarted;
    BOOL shouldAnimate;
    CDUnknownBlockType _tapBlock;
    NSObject<OS_dispatch_queue> *_tapQueue;
    float minHeight;
    UIImage *backgroundImage;
    UIImage *accessoryImage;
}

+ (BOOL)hideDropdownInView:(id)arg1 animated:(BOOL)arg2;
+ (BOOL)hideDropdownInView:(id)arg1;
+ (void)removeView;
+ (id)showDropdownInView:(id)arg1 title:(id)arg2 detail:(id)arg3 image:(id)arg4 backgroundImage:(id)arg5 titleLabelColor:(id)arg6 detailLabelColor:(id)arg7 animated:(BOOL)arg8 hideAfter:(float)arg9;
+ (id)showDropdownInView:(id)arg1 title:(id)arg2 detail:(id)arg3 image:(id)arg4 backgroundImage:(id)arg5 animated:(BOOL)arg6 hideAfter:(float)arg7;
+ (id)showDropdownInView:(id)arg1 title:(id)arg2 detail:(id)arg3 image:(id)arg4 animated:(BOOL)arg5 hideAfter:(float)arg6;
+ (id)showDropdownInView:(id)arg1 title:(id)arg2 detail:(id)arg3 image:(id)arg4 animated:(BOOL)arg5;
+ (id)showDropdownInView:(id)arg1 title:(id)arg2 detail:(id)arg3 animated:(BOOL)arg4;
+ (id)showDropdownInView:(id)arg1 title:(id)arg2 detail:(id)arg3;
+ (id)showDropdownInView:(id)arg1 title:(id)arg2;
+ (id)currentDropdownView;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
@property(retain) UIColor *detailLabelColor; // @synthesize detailLabelColor;
@property(retain) UIColor *titleLabelColor; // @synthesize titleLabelColor;
@property BOOL shouldAnimate; // @synthesize shouldAnimate;
@property(nonatomic) SEL onTouch; // @synthesize onTouch;
@property(retain, nonatomic) UIImage *accessoryImage; // @synthesize accessoryImage;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage;
@property float minHeight; // @synthesize minHeight;
- (void)setTapBlock:(CDUnknownBlockType)arg1 withQueue:(id)arg2;
- (void)layoutSubviews;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)done;
- (void)hideUsingAnimation:(id)arg1;
- (void)hide:(BOOL)arg1;
- (void)show:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (void)updateDetailLabel:(id)arg1;
- (void)updateTitleLabel:(id)arg1;
@property(copy) NSString *detailText; // @synthesize detailText;
@property(copy) NSString *titleText; // @synthesize titleText;

@end

